### ISSUE TITLE
Shares field issue

### ISSUE THREAD

**Issue by paullovachy** [kevinzg/facebook-scraper#1]
Sometimes the shares field returns 0 when in fact a post has been shared multiple times, just FYI.

**Comment by paullovachy** [comment]
Ah - you noted that my B

**Comment by kevinzg** [comment]
No problem, thanks for creating the issue. It's nice to see this project being used by other people.

About the shares counter, I think it is just the first page that doesn't include them, because the first page uses a different endpoint from the other pages.

**Comment by paullovachy** [comment]
No problem! Other than that, I haven't run into any issues, and it is a helpful library for analyzing FB engagement trends :)

**Comment by manfye** [comment]
likes and comment seem to be error too

**Comment by pitiphol** [comment]
> likes and comment seem to be error too

for me like and comments error due to it change html depends on which country you use it so if you want like and comment you have to look at return html and change **_likes_regex** and **_comments_regex** to the right format.

ps. this article footer doesn't return share count but it is in html code you need to write new function to get share count.

**Comment by manfye** [comment]
> > likes and comment seem to be error too
> 
> for me like and comments error due to it change html depends on which country you use it so if you want like and comment you have to look at return html and change **_likes_regex** and **_comments_regex** to the right format.
> 
> ps. this article footer doesn't return share count but it is in html code you need to write new function to get share count.

thank you very much

**Comment by bitthal** [comment]
> > likes and comment seem to be error too
> 
> for me like and comments error due to it change html depends on which country you use it so if you want like and comment you have to look at return html and change **_likes_regex** and **_comments_regex** to the right format.
> 
> ps. this article footer doesn't return share count but it is in html code you need to write new function to get share count.

can you provide me the code for share count? and how to include it in existing code

**Comment by sentiwise** [comment]
Any suggestions/recommendations on how to rectify the share count issue? Anyone done some decent investigation work or have a fix ready to go?

**Comment by kevinzg** [comment]
@sentiwise Try using the latest version and add the parameter `extra_info=True` to `get_posts`.

**Comment by sentiwise** [comment]
> @sentiwise Try using the latest version and add the parameter `extra_info=True` to `get_posts`.

Thanks, will try. I just looked at the source changes. Why do you need to drill into each post? I see the share counts on the missed posts. Isn't there an way to do another network request?

**Comment by sentiwise** [comment]
Hi, I just reread my last comment/question. The last sentence should have been this question: Isn't there any another way to get at the share count without doing another request and drill down into the actual post?

**Comment by Ting0887** [comment]
some posts that shares count still return 0

**Comment by neon-ninja** [comment]
Try with the latest version, should be fixed now
