### ISSUE TITLE
Having a problem with the option [post-text]

### ISSUE THREAD

**Issue by DiegoChito** [kevinzg/facebook-scraper#1006]
When I'm trying to scrap the text of the post of many pages they're like combine each other. Also at the end its like showing a lot of numbers and letters that I dont know what it is. 

"(function(){var n=now_inl();requireLazy(["__bigPipe"],function(bigPipe){bigPipe.beforePageletArrive("tlFeed",n);})})(); requireLazy(["__bigPipe"],(function(bigPipe){bigPipe.onPageletArrive({displayResources:["Q7npRpk","jMJUy0e","lWMrrKH","VlTh/BP","RzbQlJH","MmIV9rr","IN0FL4P","9mD2Jb8","PiOVcGT","hURtgcm","1zryJWw","FJqL2Al"],content:{tlFeed:{container_id:"u_0_2k_MK"}},id:"tlFeed",phase:4,last_in_phase:true,all_phases:[63,7,2,3,4],tti_phase:4,jsmods:{define:[["MUFIConfig",[],{hasIEMobileFixes:false,canReactToComment:true,hasUpdatedDock:false,photoComments:{dtsg:"NAcO-CTFoY5yn_gCFC0jCy-5tiF5_JGZT4NaZTnH1BfEOXSUfxWMeWw:34:1681851787",uploadDomain:"https://upload.facebook.com/",waterfallAppName:"web_m_touch",waterfallSource:"photo_comment"},vpvLoggingTimeout:300,actionSounds:{like:null}},669],["BackgroundSyncParameters",[],{shouldRecoverReactions:true,recoverReactionsQe:""},3506],["MqttWebDeviceID",[],{clientID:"f7d3060d-2b61-45c3-86f5-4aae87ba3053"},5003],["UFIReactionIcons",[],{"1":{"16":{sprited:1,spriteCssClass:"sx_be1fb3",spriteMapCssClass:"sp_f9OLn5Y9NX-",origPath:"images/ufi/reactions/v7_DO_NOT_USE_DIRECTLY/16x16/like.png"},"14":{sprited:1,spriteCssClass:"sx_fdc389",spriteMapCssClass:"sp_f9OLn5Y9NX-",origPath:"images/ufi/reactions/v7_DO_NOT_USE_DIRECTLY/14x14/like.png"}},"2":{"16":{sprited:1,spriteCssClass:"sx_1e87ed",spriteMapCssClass:"sp_f9OLn5Y9NX-",origPath:"images/ufi/reactions/v7_DO_NOT_USE_DIRECTLY/16x16/love.png"},"14":{sprited:1,spriteCssClass:"sx_2b8f86",spriteMapCssClass:"sp_f9OLn5Y9NX-",origPath:"images/ufi/reactions/v7_DO_NOT_USE_DIRECTLY/14x14/love.png"}},"16":{"16":{sprited:1,spriteCssClass:"sx_b73584",spriteMapCssClass:"sp_f9OLn5Y9NX-",origPath:"images/ufi/reactions/v7_DO_NOT_USE_DIRECTLY/16x16/support.png"},"14":{sprited:1,spriteCssClass:"sx_4431f0",spriteMapCssClass:"sp_f9OLn5Y9NX-",origPath:"images/ufi/reactions/v7_DO_NOT_USE_DIRECTLY/14x14/support.png"}},"4":{"16":{sprited:1,spriteCssClass:"sx_d85109",spriteMapCssClass:"sp_f9OLn5Y9NX-",origPath:"images/ufi/reactions/v7_DO_NOT_USE_DIRECTLY/16x16/haha.png"},"14":{sprited:1,spriteCssClass:"sx_2734e3",spriteMapCssClass:"sp_f9OLn5Y9NX-",origPath:"images/ufi/reactions/v7_DO_NOT_USE_DIRECTLY/14x14/haha.png"}},"3":{"16":{sprited:1,spriteCssClass:"sx_d98142",spriteMapCssClass:"sp_f9OLn5Y9NX-",origPath:"images/ufi/reactions/v7_DO_NOT_USE_DIRECTLY/16x16/wow.png"},"14":{sprited:1,spriteCssClass:"sx_0a5f12",spriteMapCssClass:"sp_f9OLn5Y9NX-",origPath:"images/ufi/reactions/v7_DO_NOT_USE_DIRECTLY/14x14/wow.png"}},"7":{"16":{sprited:1,spriteCssClass:"sx_39946a",spriteMapCssClass:"sp_f9OLn5Y9NX-",origPath:"images/ufi/reactions/v7_DO_NOT_USE_DIRECTLY/16x16/sorry.png"},"14":{sprited:1,spriteCssClass:"sx_9637c3",spriteMapCssClass:"sp_f9OLn5Y9NX-",origPath:"images/ufi/reactions/v7_DO_NOT_USE_DIRECTLY/14x14/sorry.png"}},"8":{"16":{sprited:1,spriteCssClass:"sx_6d8f5a",spriteMapCssClass:"sp_f9OLn5Y9NX-",origPath:"images/ufi/reactions/v7_DO_NOT_USE_DIRECTLY/16x16/anger.png"},"14":{sprited:1,spriteCssClass:"sx_63e454",spriteMapCssClass:"sp_f9OLn5Y9NX-",origPath:"images/ufi/reactions/v7_DO_NOT_USE_DIRECTLY/14x14/anger.png"}}},1059],["UFIReactionTypes",[],{LIKE:1,ordering:[1,2,16,4,3,7,8],NONE:0,reactions:{"1":{color:"#2078f4",display_name:"Me gusta",is_deprecated:false,is_visible:true,name:"like",type:1},"2":{color:"#f33e58",display_name:"Me encanta",is_deprecated:false,is_visible:true,name:"love",type:2},"13":{color:"#f0ba15",display_name:"Selfie",is_deprecated:false,is_visible:false,name:"selfie",type:13},"11":{color:"#7e64c4",display_name:"&#161;Gracias!",is_deprecated:false,is_visible:true,name:"dorothy",type:11},"12":{color:"#ec7ebd",display_name:"Orgullo",is_deprecated:false,is_visible:true,name:"toto",type:12},"4":{color:"#f7b125",display_name:"Me divierte",is_deprecated:false,is_visible:true,name:"haha",type:4},"5":{color:"#f0ba15",display_name:"Me alegra",is_deprecated:true,is_visible:false,name:"yay",type:5},"3":{color:"#f7b125",display_name:"Me asombra",is_deprecated:false,is_visible:true,name:"wow",type:3},"10":{color:"#f0ba15",display_name:"Me confunde",is_deprecated:true,is_visible:false,name:"confused",type:10},"16":{color:"#f7b125",display_name:"Me"

Something like that show me in [post-text].

Also this alerts appers in m python:

![image](https://user-images.githubusercontent.com/47165694/234920155-898dce3e-b5b8-4049-a6f5-0308e6e3f43a.png)

**Comment by neon-ninja** [comment]
Duplicate of https://github.com/kevinzg/facebook-scraper/discussions/1014
