### ISSUE TITLE
How to extract posts using a specific Keywords and Hashtag?

### ISSUE THREAD

**Issue by Nitigya-Handa** [kevinzg/facebook-scraper#101]
I wanted to get posts from a certain page only containing certain Keywords, Hashtags for my project. Is there a way to do that. Kindly Help.
By the way it is great project that you've made it has helped me a lot.
Thanks!

**Comment by kevinzg** [comment]
You would have to get all the posts and then filter them, currently there is no way to ask the server just for the posts you want.

**Comment by Nitigya-Handa** [comment]
Ok thanks nonetheless!🙂
