### ISSUE TITLE
How can set language from es_LA to en_us?

### ISSUE THREAD

**Issue by DiegoChito** [kevinzg/facebook-scraper#1016]
I don't know how to set the language of the scrapper to en_US. Please can give me an advice!!

**Comment by neon-ninja** [comment]
In your Facebook settings

**Comment by DiegoChito** [comment]
Can you show me where?? because I can't find it

**Comment by DiegoChito** [comment]
@neon-ninja Can you help me?

**Comment by DiegoChito** [comment]
@neon-ninja jaja thanks but what I mean was in this issue "@neon-ninja A few days back I also create a new issue with the option "Post-text". I dont know why but when a call that column all the post merge with each other. Maybe you know what's going on?" but thanks with the other one as well!

**Comment by DiegoChito** [comment]
THANKS A LOT!!

**Comment by neon-ninja** [comment]
Link to mentioned issue: https://github.com/kevinzg/facebook-scraper/issues/1006
