### ISSUE TITLE
Why are do all URLs use mobile Facebook?

### ISSUE THREAD

**Issue by TheMulti0** [kevinzg/facebook-scraper#103]
Hi there,
I do not understand why do all links begin with the old `https://m.facebook.com` instead of the new redesigned `https://facebook.com` that works for all platforms?
Thanks.

**Comment by kevinzg** [comment]
`m.facebook.com` had less JS and HTTP requests so it was easier to reason about.

**Comment by TheMulti0** [comment]
But cannot you build the posts' URLs with the newer `https://facebook.com`

**Comment by kevinzg** [comment]
Oh, my bad, I misread your question.
There is no special reason to use the mobile URL. I guess it would make more sense to return the standard one.

**Comment by TheMulti0** [comment]
Excellent. A PR is one the way!
