### ISSUE TITLE
04 Client Error: Not Found for url: https://m.facebook.com/jus.guessit/posts/

### ISSUE THREAD

**Issue by Stunez** [kevinzg/facebook-scraper#106]
i can't scrap example this guy 'jus.guessit', because "https://m.facebook.com/jus.guessit/posts/" does not exits. 
Can I scrap without word "/posts/"?
if yes, what i must do? or change?

**Comment by kevinzg** [comment]
The scraper works on public pages. I haven't tried it with people profiles, but it looks like the posts of that account are private.

**Comment by Gameye98** [comment]
I get the error message too...
It is public posts, but it couldn't work

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://m.facebook.com/Gameye98/posts/

**Comment by neon-ninja** [comment]
jus.guessit works fine if you pass cookies. Gameye98 doesn't seem to exist anymore.
