### ISSUE TITLE
No raw posts in get_posts

### ISSUE THREAD

**Issue by Saul-Github** [kevinzg/facebook-scraper#1075]
When I was trying to get posts by the following codes, I did not got error, or results. 
I only got WARNING: facebook_scraper.page_iterators:No raw posts (article elements) were found in this page
```

for post in get_posts(account='nintendo', cookies='/content/79c6ad1a-78ce-4348-949d-a581ff555f6b.txt', pages=5):
  print(post)
```

**Comment by moda20** [comment]
@Saul-Github check here : https://github.com/moda20/facebook-scraper/commit/14574499324bb425560085116eb5040c0db0aad7#commitcomment-134092869

and here : https://github.com/kevinzg/facebook-scraper/issues/1070

**Comment by TBKRK** [comment]
I have the same problem since December 2nd. Previously I could receive posts from one account, now I only receive empty []. Configuring start_url does not solve the problem.
I use cookies, but changing to "credentials", even with other user or different IP doesn't help.
Has Facebook made any changes?

**Comment by moda20** [comment]
@TBKRK  they did some changes, they always do in fact, regularly. be sure you are using the right credentials,

**Comment by qxuanson** [comment]
i had the same problem, a month ago it was still working

**Comment by HienNguyenPhan** [comment]
Does anyone here has any solution, maybe an alternative. I'm desperate

**Comment by TBKRK** [comment]
@moda20 credentials are fine... It just stopped working...

**Comment by volodkindv** [comment]
The same problem. First in FB's responses disappeared "top_level_post_id". Then disappeared something else, I don't understand yet.

**Comment by moda20** [comment]
@volodkindv Yes mbasic stopped returning "top_level_post_id", i updated my repo (https://github.com/moda20/facebook-scraper) to get the id form other places

**Comment by HienNguyenPhan** [comment]
@moda20 So hey I'm quite new how can I install and use your repo instead of the master one

**Comment by moda20** [comment]
@HienNguyenPhan remove the existent facebook-scrapper entry in you requirements.txt and replace it with this : 
`facebook-scraper @ git+https://github.com/moda20/facebook-scraper.git@master` and run the install command

or use pip to force update the repo like this : 
```
pip install --force-reinstall --no-deps git+https://github.com/moda20/facebook-scraper.git@master
```

**Comment by TBKRK** [comment]
@moda20 Hello, maybe it solves "top_level_post_id" problem but my script still doesn't work:
from facebook_scraper import get_posts

x = get_posts(account='mpkkrakow', cookies='cookies.json', pages=5)

print(x)

for post in x:
  print(post)

**Comment by moda20** [comment]
@TBKRK please do the research, you need to use teh start_url attribute to get the posts, the default url uses m.facebook which is not supported anymore for most regions and cookies , check here : https://github.com/kevinzg/facebook-scraper/issues/1070#issuecomment-1837606566

**Comment by TBKRK** [comment]
@moda20 still the same :( 

from facebook_scraper import get_posts

x = get_posts(account = "mpkkrakow", start_url="https://mbasic.facebook.com/mpkkrakow?v=timeline", cookies='cookies.json', pages=5)

print(x)

for post in x:
  print(post)

**Comment by TBKRK** [comment]
@moda20 wait... I changet to "credentials" and different user/password - it works!
Maybe my account is banned?

**Comment by moda20** [comment]
try to extract new cookies from the main website, visit all the 3 different websites (fb.com, m.fb.com, mbasic.fb.com) and then extract your new cookies in TXT format, old ones will not work. 
also be sure that you can access your cookies from where your script it being ran

**Comment by TBKRK** [comment]
@moda20 ok... It works with my old credentials.
I extracted new cookies - it also works!

Thank you!

**Comment by TBKRK** [comment]
@moda20 one more... please take a look at attached screen. Some posts have bigger font size. They are not get properly from the page (only part of the text is loaded) :(



![fb](https://github.com/kevinzg/facebook-scraper/assets/45081862/ace39506-082c-44e9-b541-73acb36ab0dd)

**Comment by aymen-ch** [comment]
@moda20 when I use your solution I cannot have more than 5 posts even when I indicate the number of pages at 20

**Comment by moda20** [comment]
@aymen-ch Please open a new issue on my repo with a bit more details
