### ISSUE TITLE
Extract specific post URL

### ISSUE THREAD

**Issue by andrew-trustlab** [kevinzg/facebook-scraper#109]
I'm looking to extract a specific post URL (e.g. https://www.facebook.com/APNews/posts/10157519759086623/). I'm starting with `extract_post`, but wanted to check to see if there's a better way to do so already :)

**Comment by kevinzg** [comment]
Currently there isn't a straight forward way to do that, but consider that the `extract_post` function is tailored for posts from the mobile page (`m.facebook.com`).
Hopefully in the future it will handle the `www` page as it has more accurate data.

**Comment by andrew-trustlab** [comment]
Sounds good, thank you for the reply!
