### ISSUE TITLE
[Discussion] Avoiding blacklists: rotating proxies or varying scraping params

### ISSUE THREAD

**Issue by simonsterj** [kevinzg/facebook-scraper#11]
Seeing as to how getting blacklisted is likely a concern to many using a module such as this, I'd like to start a discussion on ideas to avoid doing so.  

What are anyone's thoughts on implementing features that reduce the chance of getting blacklisted, such as rotating proxies, or allowing adjustment of scraping params such as time in between requests?  

Has anybody implemented something similar in their own usage? What's worked and what hasn't?

**Comment by kevinzg** [comment]
I don't think those features will be implemented directly on this project.

Eventually I would like to provide an Spider class interface to be used with [Scrapy](https://scrapy.org/).

Scrapy already has support for [auto throttle](https://docs.scrapy.org/en/latest/topics/autothrottle.html) and has some recommended practices on how to [distribute scrapers](https://docs.scrapy.org/en/latest/topics/practices.html#distributed-crawls) and [avoid getting banned](https://docs.scrapy.org/en/latest/topics/practices.html#avoiding-getting-banned).

If there is another scraping framework with those features we might also provide an interface for it.

**Comment by Retro64XYZ** [comment]
I can implement rotating proxies if there is an interest. I don't want to do it if you won't accept it though. If I added the ability to rotate proxies, would you accept the pull request?

https://pypi.org/project/requests/

```
r = requests.get("http://www.google.com", 
                 proxies={"http": "http://61.233.25.166:80"})
print(r.text)
```

You can easily update code yourself to include a list of proxies as an argument. But I am willing to do it.

**Comment by nubpro** [comment]
How likely is it to get banned from Facebook if I were to scrape the 3 Facebook page with a minimum of 2 pages each every 15 minute?  All through a single machine with a single IP address (without logging in to Facebook)

I should really get started looking into Scrapy and all the stuff you all have mentioned above.
