### ISSUE TITLE
Not Calculating Number of Comments Properly

### ISSUE THREAD

**Issue by tspier** [kevinzg/facebook-scraper#110]
Perhaps I missed this in the documentation, but it looks to me like the script is only calculating the total number of top-level comments and not replies. The reason I suggest this is because one of the pages I'm looking at has around five-hundred posts from the organization. When I exported the data from facebook-scraper, it insists that there are only 580 comments. Looking at only the top ten and calculating manually, however, yields a total of 610 comments. This would mean that those ten posts somehow add up to more than the sum of all posts, which simply isn't accurate. I looked through the rest of the posts, and even those have one or more comments in most instances, which means the number is probably two to three times what facebook-scraper is indicating.

**Comment by kevinzg** [comment]
The script isn't really calculating anything, it is just grabbing the number of comments that appears on the mobile version of the page, which for some reason is different than the one from the regular version.

**Comment by tspier** [comment]
Thanks for the response! I did a little more sleuth work, and it does seem that only those top-level comments are considered. This could very well be the case, given that the "show more" needs to be manually clicked (or done automatically with JS), and it would appear to me to be all the more likely on the mobile version that it would appear this way.

**Comment by neon-ninja** [comment]
Now that comments & replies extraction is possible, you can extract comments and take the `len()` if you need exact comment counts.
