### ISSUE TITLE
Does it works with new layout ? 2020

### ISSUE THREAD

**Issue by whatneuron** [kevinzg/facebook-scraper#113]
Does it work with new Facebook layout ? 2020

**Comment by kevinzg** [comment]
It's still working for me.

**Comment by webcoderz** [comment]
yea seems to work ok for me as well, reactions are returning empty dicts but everything else is ok here also

**Comment by ryudoawaru** [comment]
can not scrape at this moment 
![截圖 2020-09-19 下午4 24 19](https://user-images.githubusercontent.com/212290/93662686-97f8f300-fa94-11ea-82b9-d8f15b9a68a7.jpg)

**Comment by whatneuron** [comment]
> It's still working for me.

Are you using mbasic version of Facebook in code or new layout as it seems Facebook changed all IDs / classes in new layout, thanks

**Comment by kevinzg** [comment]
@whatneuron `m.facebook.com`, I think it is the same as `mbasic`.

@ryudoawaru That's weird, I'll try to add a way to dump the requests and responses being done for better debugging.

**Comment by neon-ninja** [comment]
Working fine for me
