### ISSUE TITLE
Feature request - provide login option in order to scrape private/age restricted pages

### ISSUE THREAD

**Issue by jwesheath** [kevinzg/facebook-scraper#12]
Thank you for this great package.  I need a way to scrape certain Facebook pages that require the user to be logged in.  I believe some of these pages (think alcohol and tobacco related products) only need the user to be logged in so they can check the user's age/DOB and restrict young users from viewing the page (though I'm not 100% certain about this).  I've forked this repo and modified the code so that I can provide my login information to log the session in before scraping so that I can scrape these restricted pages.  If I submit a pull request to add this feature, is this something people would be interested in?  I am admittedly not a professional software developer and may not implement the feature in the most optimal way, but I have it working and would be glad to try and share if folks are interested.

**Comment by kevinzg** [comment]
Thanks for adding this. I don't have a FB account so I haven't tested it.
If there is an problem with login in let's just reopen the issue.
