### ISSUE TITLE
Not all pages are scrapable

### ISSUE THREAD

**Issue by KristofferK** [kevinzg/facebook-scraper#121]
Hello,

While this works for most pages it does not seem to work for all.

An example of a page where this doesn't work is: https://m.facebook.com/KvicklyGrenaa/

When you are not logged in on Facebook the page will say "The link you followed may be broken, or the page may have been removed.". But if you login, the page does exist.

With facebook-scraper it **will return 0 results, even when the credentials parameter is being set and it does successfully login**. Maybe these pages use another HTML template?

Is there any fix for this?

**Comment by jrosen48** [comment]
I have ran into this same issue

**Comment by alejandrohdo** [comment]
Facebook since yesterday no longer allows access to posts publicly, I think it does not work for all fan pages

**Comment by bessiethacow** [comment]
Hi Alejandro, is there any way to overcome the block that Facebook has placed in this update, whether it be a way to manipulate this library to cater for the update, or otherwise?

**Comment by simeon9696** [comment]
I'm also experiencing this issue @alejandrohdo

**Comment by KristofferK** [comment]
It seems like some pages are scrapable again without logging in as Facebook has changed so that you can see posts without logging in. 

However a page such as KvicklyGrenaa is still not scrapable despite logging in.

**Comment by neon-ninja** [comment]
Hi, please pass cookies as per the readme for accounts such as these.
I tested with

```python
posts = list(get_posts("KvicklyGrenaa", page_limit=2, cookies='cookies.txt'))
print(len(posts))
```
and got 5 posts.
