### ISSUE TITLE
Post not found 

### ISSUE THREAD

**Issue by bessiethacow** [kevinzg/facebook-scraper#122]
I've been using this library for the past few months to obtain data related to my country's ministry of health, and it's been working very well, until today. 
The following code, which usually works and returns the respective data, currently produces no data for 'post' and hence, nothing for postText, postImage or postURL: 

```
for post in get_posts('MinistryofHealthTT', pages=1): 
    postText    = post['text'][:50]
    postImage   = post['image']
    postURL     = post['post_url']
```

Usually the data is produced in the form of a dictionary, however none of the data is currently being extracted. I also know for sure that the post exists. 
Hoping someone could provide me with assistance/clarification on why I am unable to receive data from this function, or if there was an update to this function that I missed

**Comment by jeffersonlo-nesso** [comment]
I am encountering the same issue as well.

**Comment by simeon9696** [comment]
I just stumbled into this issue as well

**Comment by KristofferK** [comment]
This was a change at Facebook but it seems like they have reverted it again, so you should once again be able to scrape

**Comment by bessiethacow** [comment]
While the reverted change was noted, the library currently seems to be unable to retrieve the post URL and the link for the posts being scraped (showed up as **None**), taken from a public page, below:

`{'post_id': '3725601007469680', 'text': 'MoH COVID-19 Update #471', 'post_text': 'MoH COVID-19 Update #471', 'shared_text': '', 'time': datetime.datetime(2020, 9, 20, 18, 1, 44), 'image': 'https://scontent.fpos1-1.fna.fbcdn.net/v/t1.0-9/fr/cp0/e15/q65/119713035_3725601014136346_9219913483351361425_o.jpg?_nc_cat=108&_nc_sid=da1649&_nc_ohc=tgf5XLQh_gcAX9-86_T&_nc_ht=scontent.fpos1-1.fna&tp=14&oh=3f2158bd86f10dadd8e5cf89937a8037&oe=5F8EAF61', 'video': None, 'video_thumbnail': None, 'likes': 10, 'comments': 0, 'shares': 0, 'post_url': None, 'link': None}`

Has anyone else had this problem today, and are there any suggestions on how to proceed?

**Comment by simeon9696** [comment]
Hi @bessiethacow  can you provide the link you're trying to scrape?

**Comment by bessiethacow** [comment]
The page that I am trying to scrape is [https://m.facebook.com/MinistryofHealthTT/](url) and the specific post that I was trying to get from the `post_url` is [https://m.facebook.com/story.php?story_fbid=3725601007469680&substory_index=0&id=151162024913614](url)

**Comment by asymness** [comment]
The post URL can be constructed with the following format:
`https://web.facebook.com/<page_id>/posts/<post_id>`
So, in your case you can do:
```
page_id = 'MinistryofHealthTT'
for post in get_posts('MinistryofHealthTT', pages=1): 
    postText    = post['text'][:50]
    postImage   = post['image']
    postURL     = 'https://web.facebook.com/{}/posts/{}'.format(page_id, post.get('post_id'))
```

**Comment by neon-ninja** [comment]
```python
pprint(next(get_posts(post_urls=["https://m.facebook.com/story.php?story_fbid=3725601007469680&substory_index=0&id=151162024913614"])))
```
returns
```python
{'available': True,
 'comments': 23,
 'comments_full': None,
 'factcheck': None,
 'image': 'https://scontent.fakl1-3.fna.fbcdn.net/v/t1.6435-9/fr/cp0/e15/q65/119713035_3725601014136346_9219913483351361425_n.jpg?_nc_cat=108&ccb=1-3&_nc_sid=da1649&_nc_ohc=Xjl3URBLie0AX-zsf5v&_nc_ht=scontent.fakl1-3.fna&tp=14&oh=026ee7cead34083ec262da27bdae77c0&oe=60CFA59A',
 'image_lowquality': 'https://scontent.fakl1-3.fna.fbcdn.net/v/t1.6435-9/cp0/e15/q65/s1080x2048/119713035_3725601014136346_9219913483351361425_n.jpg?_nc_cat=108&ccb=1-3&_nc_sid=da1649&_nc_ohc=Xjl3URBLie0AX-zsf5v&_nc_ht=scontent.fakl1-3.fna&tp=9&oh=683cfe969daee4560a0f64c0c06071a6&oe=60CE157C',
 'images': ['https://scontent.fakl1-3.fna.fbcdn.net/v/t1.6435-9/fr/cp0/e15/q65/119713035_3725601014136346_9219913483351361425_n.jpg?_nc_cat=108&ccb=1-3&_nc_sid=da1649&_nc_ohc=Xjl3URBLie0AX-zsf5v&_nc_ht=scontent.fakl1-3.fna&tp=14&oh=026ee7cead34083ec262da27bdae77c0&oe=60CFA59A'],
 'images_description': None,
 'images_lowquality': ['https://scontent.fakl1-3.fna.fbcdn.net/v/t1.6435-9/cp0/e15/q65/s1080x2048/119713035_3725601014136346_9219913483351361425_n.jpg?_nc_cat=108&ccb=1-3&_nc_sid=da1649&_nc_ohc=Xjl3URBLie0AX-zsf5v&_nc_ht=scontent.fakl1-3.fna&tp=9&oh=683cfe969daee4560a0f64c0c06071a6&oe=60CE157C'],
 'images_lowquality_description': ['No photo description available.'],
 'is_live': False,
 'likes': 58,
 'link': None,
 'original_request_url': 'https://m.facebook.com/story.php?story_fbid=3725601007469680&substory_index=0&id=151162024913614',
 'post_id': '3725601007469680',
 'post_text': 'Ministry of Health - Trinidad and Tobago\n'
              '\n'
              'MoH COVID-19 Update #471',
 'post_url': 'https://m.facebook.com/3725601007469680',
 'reaction_count': None,
 'reactions': None,
 'reactors': None,
 'shared_post_id': None,
 'shared_post_url': None,
 'shared_text': None,
 'shared_time': None,
 'shared_user_id': None,
 'shared_username': None,
 'shares': 214,
 'text': 'Ministry of Health - Trinidad and Tobago\n\nMoH COVID-19 Update #471',
 'time': datetime.datetime(2020, 9, 20, 0, 0),
 'user_id': None,
 'user_url': 'https://facebook.com/MinistryofHealthTT/?refid=52&__tn__=%2Cg',
 'username': 'Ministry of Health - Trinidad and Tobago',
 'video': None,
 'video_duration_seconds': None,
 'video_height': None,
 'video_id': None,
 'video_quality': None,
 'video_size_MB': None,
 'video_thumbnail': None,
 'video_watches': None,
 'video_width': None,
 'w3_fb_url': None}
```

so this seems fixed
