### ISSUE TITLE
cannot get more than one post

### ISSUE THREAD

**Issue by win20012** [kevinzg/facebook-scraper#124]
Hi, I am quite new to programming and I couldn't figure out why it only gives me one post.
`for post in get_posts('9gag', timeout=10, page_limit=10):
     post_text= post['text']`

> {'post_id': '10160983712696840', 'text': 'Caption This: Studio Ghibli Edition\n\n✍🏻 the.agent.p, fer.nando.r.m, bhargavsagiraju, lig.ht.shine, pascalashnikov, tildalidell, notnajiya, barbora.80, kt_siapno, & sebsbvb | IG', 'post_text': 'Caption This: Studio Ghibli Edition\n\n✍🏻 the.agent.p, fer.nando.r.m, bhargavsagiraju, lig.ht.shine, pascalashnikov, tildalidell, notnajiya, barbora.80, kt_siapno, & sebsbvb | IG', 'shared_text': '', 'time': datetime.datetime(2020, 9, 27, 9, 0, 1), 'image': 'https://scontent.ftpe3-1.fna.fbcdn.net/v/t1.0-9/fr/cp0/e15/q65/120033108_10160983708096840_6359985742870496403_o.jpg?_nc_cat=100&_nc_sid=8024bb&_nc_ohc=datrzsgTJpkAX9jE8wK&_nc_ht=scontent.ftpe3-1.fna&tp=14&oh=beb99b51b15ecc3bfce7af9dc9cf0c10&oe=5F973B2C', 'video': None, 'video_thumbnail': None, 'video_id': None, 'likes': 3515, 'comments': 206, 'shares': 0, 'post_url': 'https://facebook.com/story.php?story_fbid=10160983712696840&id=21785951839', 'link': None, 'user_id': '21785951839'}

**Comment by kevinzg** [comment]
On the loop you posted you are assigning and overwriting the same variable every iteration.

What's the value of `len(list(facebook_scraper.get_posts('9gag', timeout=10, page_limit=10)))`? Should be around 40.

**Comment by win20012** [comment]
thank you so much, I already solved the issue.
