### ISSUE TITLE
Sleep argument not working

### ISSUE THREAD

**Issue by rajasaad7** [kevinzg/facebook-scraper#129]
for post in get_posts(group=groupname ,sleep = 2, credentials=facebook_creds[0]  ):
    print(post)
sleep argument is not there or whats the matter?

TypeError: _generic_get_posts() got an unexpected keyword argument 'sleep'

**Comment by kevinzg** [comment]
Yes, the sleep parameter was removed, I have updated the readme, sorry for the confusion.
