### ISSUE TITLE
How to get Comments and reactions ?

### ISSUE THREAD

**Issue by nassera2014** [kevinzg/facebook-scraper#132]
Hello, 
 Thank you so much for your great work, i get posts , but i failed to get comments of posts ? and reactions ? 
can you help me pleaase !! 
i get this error when i try to get reactions : 
 _more_info_post = extractors.extract_reactions(post)
AttributeError: module 'facebook_scraper.extractors' has no attribute 'extract_reactions'_

when i execute this code : 
   _for post in get_posts('fanpage'):
            more_info_post = fetch_share_and_reactions(post)
            print(more_info_post)_

Thank you, this is my email : nassera.habbat@gmail.com.

**Comment by GintamaYu** [comment]
that function is for internal use only, the comment for usage in code is old version
you need to add a parameter in get_post, which is extra_info

**Comment by gonzalo-gongora** [comment]
> 
> 
> that function is for internal use only, the comment for usage in code is old version
> you need to add a parameter in get_post, which is extra_info

Where do I have to add the 'extra_info' line? Do I have to modify any file from the facebook-scraper folder?

**Comment by GintamaYu** [comment]
for example:
for post in get_posts('nintendo', pages=1,extra_info=True)

**Comment by nassera2014** [comment]
Thank you for your response, yes i arrived to collect reactions using 'extra_info' parameter,,but i need the comments for each post , do you have any idea how can i extract them ? thank you.

**Comment by gonzalo-gongora** [comment]
> 
> 
> for example:
> for post in get_posts('nintendo', pages=1,extra_info=True)
> but sometimes it doesn't work properly, like sometimes I can only get reactions from a post that includes video, and idk why

The extra_info starts acting up when analyzing long sets of data for me.
The CLI usage is also funky when I try to create a .csv for data sets > 5 pages

**Comment by GintamaYu** [comment]
> Thank you for your response, yes i arrived to collect reactions using 'extra_info' parameter,,but i need the comments for each post , do you have any idea how can i extract them ? thank you.

I think this is the most helpful one https://github.com/rugantio/fbcrawl
its good at crawling comments, but its crawling post functions is kinda broken

**Comment by neon-ninja** [comment]
As of https://github.com/kevinzg/facebook-scraper/pull/194 and https://github.com/kevinzg/facebook-scraper/pull/188 this is now possible
