### ISSUE TITLE
text posts with colored background not scrapped !

### ISSUE THREAD

**Issue by MoumenKhadr** [kevinzg/facebook-scraper#137]
any text post with colored background is not scrapped at all like it being ignored !
for example posts like this 
fb.com/TechLobia/posts/1558037414380000

**Comment by MoumenKhadr** [comment]
found the solution  by @TearsOfTheEarth
https://github.com/kevinzg/facebook-scraper/issues/86#issuecomment-657690560

**Comment by danijoo** [comment]
Any reason why this was closed, but @TearsOfTheEarth's fix has not been taken over?

**Comment by MoumenKhadr** [comment]
> Any reason why this was closed, but @TearsOfTheEarth's fix has not been taken over?

I have already found the solution and already mentioned the answer see my last comment

**Comment by danijoo** [comment]
yes but it would be nice to see this fix upstream :)
