### ISSUE TITLE
flag when not more posts

### ISSUE THREAD

**Issue by GivenToFlyCoder** [kevinzg/facebook-scraper#146]
Is there some message or flag that happens when no more posts founds in facebook page account?

I need it to implement some logic, when not more posts found

**Comment by kevinzg** [comment]
You can set the page limit to `None` and wait till the loop is over. Would that work?

**Comment by GivenToFlyCoder** [comment]
The loop ends, but i need to get some message or flag that indicates there is no more post.

I´m extracting data from a list of Facebook Pages, when post["time"] reach the begin date that i set, the loops breaks and  begins some code. But in some cases, the loop is break beacuse there is no more post, instead of the reach of the begin date.
