### ISSUE TITLE
Some pages don't have relative path `/posts`

### ISSUE THREAD

**Issue by balazssandor** [kevinzg/facebook-scraper#148]
Some pages don't have relative path `/posts` so fetching of posts fails with 
`HTTPError: 404 Client Error: Not Found for url: https://m.facebook.com/*/posts/`

**Comment by Ting0887** [comment]
fans_page is private ?

**Comment by rowedenny** [comment]
I guess it could be the same issue when I try to fetch posts from private pages even when I log in.
