### ISSUE TITLE
comment scraping

### ISSUE THREAD

**Issue by chowdhury-najir** [kevinzg/facebook-scraper#153]
how to scrape group comments

**Comment by lidiasm** [comment]
Any solution to scrape comments from the posts??

**Comment by maroxtn** [comment]
This library doesn't support that, maybe in future releases it will

**Comment by fashandatafields** [comment]
@maroxtn @kevinzg can you give any tips to scrape comments using this library or is it impossible to do that task?

**Comment by kevinzg** [comment]
Comments scraping is currently not implemented. I can't work on it right now, but I'm accepting pull requests.

Closing this issue, use #22 for discussion about this feature.
