### ISSUE TITLE
Page likes

### ISSUE THREAD

**Issue by rinaldipratama** [kevinzg/facebook-scraper#159]
Thank you for your great work, I'd appreciate it!

But, how can I get the page likes for fan page? is there available?

**Comment by kevinzg** [comment]
Currently not available.

**Comment by rinaldipratama** [comment]
It's okay, I got it.

**Comment by ashxbw** [comment]
Is there a way to get likes for a post on a fan page? For example, I want to scrape the posts for www.facebook.com/themonkees along with the likes for each post.
