### ISSUE TITLE
No response when retrieving posts

### ISSUE THREAD

**Issue by gomesfernanda** [kevinzg/facebook-scraper#18]
I just installed the library and I'm trying to run the example at the README, but I get an error

```
Traceback (most recent call last):
  File "/Users/fernandagomes/dev/deni_dashbot/main_executer.py", line 49, in <module>
    for p in posts:
  File "/Users/fernandagomes/dev/deni_dashbot/deni_env/lib/python3.6/site-packages/facebook_scraper.py", line 55, in get_posts
    html = response.html
AttributeError: 'Response' object has no attribute 'html'
```

Any idea on why this is happening? I tried with many different pages.

**Comment by rmassidda** [comment]
I had the same problem, the fix proposed in this other issue works for me: https://github.com/kevinzg/facebook-scraper/issues/18

**Comment by gomesfernanda** [comment]
Sorry Riccardo (@rmassidda) but you referenced to this same issue hahaha #18. Which issue you were talking about?

**Comment by rmassidda** [comment]
> Sorry Riccardo (@rmassidda) but you referenced to this same issue hahaha #18. Which issue you were talking about?

Oops! I edited the comment :+1:
