### ISSUE TITLE
Profile Scraper

### ISSUE THREAD

**Issue by tahakorkmazTGA** [kevinzg/facebook-scraper#183]
I have made a profile scraper with same tools, but it's only been for the front page posts of the profile. After implementing the scrape for other pages and media links can we add this to the project. 

Thanks

**Comment by neon-ninja** [comment]
This tool works for profiles too already

**Comment by tahakorkmazTGA** [comment]
wait really? i couldn't manage to make it work and developed it myself though mine wasn't this complex

**Comment by neon-ninja** [comment]
Yes, you just need to pass cookies generally. For example, the code:

```python
posts = list(get_posts("joe.trinder", pages=10, cookies="cookies.txt"))
print(len(posts))
```

returns
```python
100
```

**Comment by tahakorkmazTGA** [comment]
by cookies.txt do you mean the chrome's cookies after i login to the facebook?

**Comment by neon-ninja** [comment]
Yes, in Netscape format. See https://github.com/kevinzg/facebook-scraper/issues/28#issuecomment-793066983
