### ISSUE TITLE
Scraping groups ?

### ISSUE THREAD

**Issue by w0989en** [kevinzg/facebook-scraper#19]
e.g. https://www.facebook.com/groups/483818411801540/
there is nothing: 
`get_posts('groups/483818411801540', pages=1)`

**Comment by kevinzg** [comment]
I updated the master branch to support groups.

Try with `get_posts(group=483818411801540)`.

It only gets the first page though. I haven't looked at the cursor for group pages yet.

**Comment by yushaamalik** [comment]
This doesn't work. Group is an invalid arguement
