### ISSUE TITLE
Only shows first paragraph of a post

### ISSUE THREAD

**Issue by brutalsavage** [kevinzg/facebook-scraper#2]
Just need to do
paragraphs = article.find('p', first=false)
and then loop through the paragraphs to append text

**Comment by kevinzg** [comment]
Fixed, thank you.

**Comment by Fdowouo** [comment]
Hello,
I am not sure if i should open thread for this issue, 
In my use case, **for longer post, the text is being limited to around 700 characters**, usually a little more that a paragraph, I look at the code and I don't see what is causing that problem. Has anyone ran into this issue , any fix ? Thanks
