### ISSUE TITLE
Attribute error _find_and_search

### ISSUE THREAD

**Issue by Saloking** [kevinzg/facebook-scraper#20]
For some posts, in the function _find_and_search the container returned is of type None. The subsequent pattern search explicitly looks for the attribute html which then leads to an exception.

![2019-12-18-002101_655x344_scrot](https://user-images.githubusercontent.com/19406973/71042737-e0ae0500-212c-11ea-8c34-ec4360ec1184.png)

**Comment by Saloking** [comment]
@kevinzg I have a pull request ready but can't push. Can you add me as a contributor?

**Comment by kevinzg** [comment]
@Saloking can you try the current version on master and check if the error keeps happening?

I believe I already fixed the error you are reporting. I just haven't published the new version on PyPI yet.

If you still want to submit a pull request just fork the repo, push your changes there, and then create the PR, see [Creating a pull request from a fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by Saloking** [comment]
I’ll check later today. Thanks for the quick reply and letting me know how to contribute :))

**Comment by Saloking** [comment]
Hi @kevinzg you were right, with the version on master the error does not appear.
