### ISSUE TITLE
How to extract replies

### ISSUE THREAD

**Issue by fashandatafields** [kevinzg/facebook-scraper#219]
How to extract replies along with comments, please help

**Comment by fashandatafields** [comment]
> How to extract replies along with comments, please help

@kevinzg  or @neon-ninja any suggestion about this fixing

**Comment by neon-ninja** [comment]
Comment threads you mean? Does the existing comment extractor not already extract those threaded comments?

**Comment by neon-ninja** [comment]
@fashandatafields this PR should make it possible to extract replies - https://github.com/kevinzg/facebook-scraper/pull/225
