### ISSUE TITLE
Generating Json gives incorrect formatting.

### ISSUE THREAD

**Issue by fashandatafields** [kevinzg/facebook-scraper#227]
When I format the JSON, it gives an incorrect JSON format.
the error is the `date and time` 

```
datetime.datetime(2021,
   4,
   27,
   0,
   33,
   46),
```
Is it possible to convert like this?
`date.strftime('%Y:%m:%d %H:%M:%S')` with utc time `datetime.utcnow()`

please consider my suggestion @neon-ninja  or @kevinzg

**Comment by fashandatafields** [comment]
I suggested UTC time is because the current time doesn't give an accurate posted, commented and replied times which is `hours, mins and secs` ago values

**Comment by neon-ninja** [comment]
Why not do this on your end? e.g.,

```python
for post in posts:
    post["time"] = post.get("time").strftime('%Y:%m:%d %H:%M:%S')
```

The reason I think it's better on your side as opposed to within the library is that not every might agree that's the best way to format the timestamp - some people might prefer Y-m-d format or .isoformat().

**Comment by kevinzg** [comment]
@fashandatafields How are you formatting it as JSON? if you are using the standard `json` module you can pass the `default` parameter to transform the datetime as you like. See this [SO answer](https://stackoverflow.com/a/22238613).
