### ISSUE TITLE
Small Suggestion in the current json for public pages

### ISSUE THREAD

**Issue by fashandatafields** [kevinzg/facebook-scraper#228]
Current JSON is completely perfect but I have a small suggestion. We have added all data for the public post JSON but we have missed something that is the forum/page name which we have extracted from the data. 
I suggest to add the page name to the current JSON

**Comment by fashandatafields** [comment]
@kevinzg and @neon-ninja, please consider my suggestion

**Comment by neon-ninja** [comment]
@fashandatafields the username should be in present in the output dict under the key "username"

**Comment by fashandatafields** [comment]
@neon-ninja So you mean, the forum name is under the key of "username". 
Missing JSON is the person name and id who posted the post
`{ "post_author":"Ninja Neon", "post_author_id":"3123218312312"}` 
It may be a complete JSON. Its my suggestion 

@kevinzg and @neon-ninja, please consider my suggestion

**Comment by neon-ninja** [comment]
@fashandatafields in the case of a page, the user_id and username will be the same for each post. In the case of a group, it can differ. For example:

```python
posts = list(get_posts(group="lienminhnongnghieptute", page_limit=1))
for post in posts:
    print(post.get("user_id"), post.get("username"))
```

Outputs

```python
100001080786945 Hoàng Công
100004172320454 Hà Công Xã
100001572304920 Trung Nguyễn
100008623893421 Dương Đình Tường
100011490288041 Ngọc Lễ
100010998814861 Minh Pham
100033040967455 Hoài Lê
100027396282216 Tịnh Nguyên
100000360975013 Kim Anh Vu
100000368409146 Nguyễn Thị Lĩnh
100012596924056 Nguyễn Vương Lan
100002860458068 Điệp Đỏng Đảnh
100004406447214 Hoan Nguyễn
100008909839117 Loan Phi Thi
100026743291839 Lê Xuân Vịnh
100058619983331 Duy Ong Mật
100005930040386 Hungcuong Pham
100008414438582 Đào Thi Hòa
100027396282216 Tịnh Nguyên
100005975141461 Dương Ngọc Trường
100026206981980 Vu Tranthi
```
