### ISSUE TITLE
Comment URL and reply URL issue

### ISSUE THREAD

**Issue by fashandatafields** [kevinzg/facebook-scraper#229]
When I run the script, the comment and reply URL is none. Why is it? 

`{
         "comment_id":"1100458000438886",
         "commenter_url":"None",
         "commenter_name":"Sur Kelvin Lwanja",
         "commenter_meta":"None",
         "comment_text":"watching from RSA",
         "comment_time":datetime.datetime(2021,
         4,
         28,
         13,
         45,
         31,
         737858),
         "replies":[
            {
               "comment_id":"1100519170432769",
               "commenter_url":"None",
               "commenter_name":"Muhammadh Fashaan",
               "commenter_meta":"None",
               "comment_text":"blah blah",
               "comment_time":datetime.datetime(2021,
               4,
               28,
               14,
               45,
               32,
               718600)
            }
         ]
      },`

**Comment by fashandatafields** [comment]
`{
   "commenter_profile_id":"2849453428654932",
   "permalink_of_comment":"None",
   "commenter_profile_name":"None",
   "comment_text":"Chimombo Tinashe",
   "commented_at":"2021:04:28 17:44:30"
}`

permalink_of_comment & commenter_profile_name are NONE too.

**Comment by fashandatafields** [comment]
`first_link = comment.find("div:not([data-sigil])>a[href]:not([data-click]):not([data-store]):not([data-sigil])", first=True)`
gives me None

**Comment by fashandatafields** [comment]
@neon-ninja any idea on this?

**Comment by neon-ninja** [comment]
commenter_url will be None if no cookies are passed. Facebook does not provide these links to anonymous users. Not sure where you're getting permalink_of_comment and commenter_profile_name from, this must be your own code, that's not part of the library.

**Comment by fashandatafields** [comment]
Thanks for the information
