### ISSUE TITLE
Public Post JSON [replies dictionary] suggestion 

### ISSUE THREAD

**Issue by fashandatafields** [kevinzg/facebook-scraper#230]
In the this JSON 
`{
   "comments_full":[
      {
         "comment_id":"1100504423767577",
         "commenter_url":"None",
         "commenter_name":"Phil Kay",
         "commenter_meta":"None",
         "comment_text":"Inu a MBC change the Page\\'s name, mukukhala ngati anthu osaphunzira bwa? MBC Malawi ndekuti chani? Redundance!! Write \"Malawi Broadicasting Cooperation.\" Not izozo mutichisa manyazi. Usumbuleta basi",
         "comment_time":datetime.datetime(2021,
         4,
         28,
         14,
         22,
         30,
         747038),
         "replies":[
            {
               "comment_id":"1100519060432780",
               "commenter_url":"None",
               "commenter_name":"Muhammadh Fashaan",
               "commenter_meta":"None",
               "comment_text":"Wowo",
               "comment_time":datetime.datetime(2021,
               4,
               28,
               14,
               45,
               31,
               717806)
            }
         ]
      }
   ]
}`

I think we need to mention that this replier was replied to `Phil Kay`
For example `Muhammadh Fashaan replied to Phil Kay`
`{"replied_to":"Phil Kay"}`

**Comment by fashandatafields** [comment]
<img width="972" alt="Screenshot 2021-04-29 at 17 22 29" src="https://user-images.githubusercontent.com/67037844/116547081-0dbd1b00-a910-11eb-93c9-95a75fbc42da.png">
This may help

**Comment by neon-ninja** [comment]
This relationship is already implicit, as the replies field is underneath the parent comment.

```python
{'comment_id': '2849997038600571',
                     'comment_text': 'COVID 21',
                     'comment_time': datetime.datetime(2021, 4, 29, 18, 42, 16, 404718),
                     'commenter_meta': None,
                     'commenter_name': 'Muhammadh Fashaan',
                     'commenter_url': 'https://facebook.com/fashanzak?fref=nf&rc=p&refid=52&__tn__=R',
                     'replies': [{'comment_id': '2849997125267229',
                                  'comment_text': 'COVID 20',
                                  'comment_time': datetime.datetime(2021, 4, 29, 18, 42, 16, 909694),
                                  'commenter_meta': None,
                                  'commenter_name': 'Muhammadh Fashaan',
                                  'commenter_url': 'https://facebook.com/fashanzak?fref=nf&rc=p&__tn__=R'},
                                 {'comment_id': '2849997171933891',
                                  'comment_text': 'COVID 19',
                                  'comment_time': datetime.datetime(2021, 4, 29, 18, 42, 16, 911553),
                                  'commenter_meta': None,
                                  'commenter_name': 'Muhammadh Fashaan',
                                  'commenter_url': 'https://facebook.com/fashanzak?fref=nf&rc=p&__tn__=R'}]}
```

This library primarily works with the mobile version of facebook, at m.facebook.com. The HTML there differs to what is in your screenshot. Specifically, the reply comment extractor accesses the url https://m.facebook.com/comment/replies/?ctoken=2849939015273040_2849997038600571&count=2&curr&pc=1&isinline&initcomp&ft_ent_identifier=2849939015273040&eav=AfbICnmqMrAszfOcewVgAw6cMBJsaR3u0EeEPIM3Uk-xhWNR5ljMQ7oLvAp_erI0TVA&av=0&gfid=AQCHvR3DWpB0qkJOA8Q&refid=52&__tn__=R-R to extract replies. The aria-labels are not present there.

**Comment by fashandatafields** [comment]
As you said, "This relationship is already implicit, as the replies field is underneath the parent comment.". There are many instances that some replies are not replying to the commenter but it comes under reply section

**Comment by neon-ninja** [comment]
@fashandatafields in that case, they tag the person they're replying too. From the perspective of facebook structure, replies are only nested one level deep.

**Comment by fashandatafields** [comment]
`{
   "commenter_profile_id":"3256905477745221",
   "permalink_of_comment":"https://facebook.com/herbert.chazuka?fref=nf&rc=p&refid=52&__tn__=R",
   "commenter_profile_name":"Herbert Chazuka",
   "comment_text":"Jumbe Tuntufye come see this osamangolubwa lubwa.",
   "commented_at":"2021:04:28 00:00:00",
   "replies":[
      {
         "replier_profile_id":"3257281797707589",
         "permalink_of_reply":"https://facebook.com/jumbe.tuntufye?fref=nf&rc=p&__tn__=R",
         "replier_profile_name":"Jumbe Tuntufye",
         "replied_to":"Herbert Chazuka",
         "reply_text":"Herbert Chazuka dont forget kut chizuma iz on the ground remember that sam alufandika is a master mind of tpex thank you",
         "replied_at":"2021:04:28 00:00:00"
      },
      {
         "replier_profile_id":"3257411184361317",
         "permalink_of_reply":"https://facebook.com/herbert.chazuka?fref=nf&rc=p&__tn__=R",
         "replier_profile_name":"Herbert Chazuka",
         "replied_to":"Herbert Chazuka",
         "reply_text":"Jumbe Tuntufye 😂😂🤣🤣👹",
         "replied_at":"2021:04:28 00:00:00"
      }
   ]
}`

<img width="616" alt="Screenshot 2021-04-30 at 13 38 08" src="https://user-images.githubusercontent.com/67037844/116667491-e0c54280-a9b9-11eb-951b-8df2b4e20ad1.png">

This `replied_to` will give a bug, as I have followed ur above suggestion.

**Comment by neon-ninja** [comment]
The only way you can tell Herbet is replying to Jumbe here, and not their own comment, is by the tag present in reply_text

**Comment by fashandatafields** [comment]
Worked and Fine

**Comment by fashandatafields** [comment]
> The only way you can tell Herbet is replying to Jumbe here, and not their own comment, is by the tag present in reply_text

U mean how?
