### ISSUE TITLE
Scraping more than 50 / 100 Comment [Issue]

### ISSUE THREAD

**Issue by fashandatafields** [kevinzg/facebook-scraper#232]
I noticed when scraping more than 50 or 100, it returns the JSON pair `comment_full` as NONE. 
Please consider my issue @kevinzg  and @neon-ninja 

I think comment rendering issue or else timeout

**Comment by neon-ninja** [comment]
@fashandatafields which post are you having this problem with?

**Comment by fashandatafields** [comment]
@neon-ninja lets take this post
https://m.facebook.com/story.php?story_fbid=1517650235239786&id=144655535872603

**Comment by neon-ninja** [comment]
With the code:

```python
from facebook_scraper import *
import time

start = time.time()
posts = list(get_posts(
    post_urls=["https://m.facebook.com/story.php?story_fbid=1517650235239786&id=144655535872603"],
    cookies="cookies.txt",
    options={"comments":500}
))
print(f"{len(posts[0].get('comments_full'))} comments extracted in {round(time.time() - start)}s")
```

I get the output: `510 comments extracted in 86s`

**Comment by fashandatafields** [comment]
Do we need to pass comment count, inorder to get the comments?

**Comment by neon-ninja** [comment]
No, as of https://github.com/kevinzg/facebook-scraper/commit/b9abf63b37a75325769bd82ef9912365bc9575c8 if you pass `True`, it tries to retrieve up to 5000 (prior to this commit it just kept going until it got all of them). https://www.facebook.com/story.php?story_fbid=1517650235239786&id=144655535872603 has 2.5K comments. You might be waiting a while to extract all 2.5K, given 510 takes 86s.

**Comment by fashandatafields** [comment]
when we give `True` the `comment_full` will be `None`

**Comment by neon-ninja** [comment]
Perhaps we can more gracefully handle errors when paginating comments, and still return the comments that were successfully extracted

**Comment by neon-ninja** [comment]
I got `1788 comments extracted in 238s` with `comments=True`

**Comment by fashandatafields** [comment]
Is it mandatory to pass cookies.txt when scraping?

**Comment by neon-ninja** [comment]
For comments, yes. See what happens when you try view comments on https://m.facebook.com/story.php?story_fbid=1517650235239786&id=144655535872603 in an incognito window.

**Comment by fashandatafields** [comment]
DO u have any idea, why comment URL and reply URL gives `None`

**Comment by neon-ninja** [comment]
https://github.com/kevinzg/facebook-scraper/commit/1730178c960ddc018cc3bebd32a0981f7d32b1cd should make comment extraction error handling more graceful

**Comment by neon-ninja** [comment]
> DO u have any idea, why comment URL and reply URL gives `None`

I replied in https://github.com/kevinzg/facebook-scraper/issues/229
