### ISSUE TITLE
Regarding Cookies.txt

### ISSUE THREAD

**Issue by fashandatafields** [kevinzg/facebook-scraper#233]
I'm still confused about what cookies.txt consist of and how can I get the cookies to pass via the argument 
Please give some information regarding this. @kevinzg  or @neon-ninja

**Comment by VariabileAleatoria** [comment]
https://github.com/kevinzg/facebook-scraper/issues/28#issuecomment-793066983

**Comment by neon-ninja** [comment]
It's also in the README now
