### ISSUE TITLE
Comments always show 0 when cookies is set

### ISSUE THREAD

**Issue by cmhcheung** [kevinzg/facebook-scraper#234]
I find that when cookies is set, comments_full can be returned but comments always show 0.  Any solution?

**Comment by fashandatafields** [comment]
Yes, I also noted that the `comment count `is always 0 from today. When I test

**Comment by neon-ninja** [comment]
This is likely because the HTML differs if you're logged in:

Cookies:

```html
<div class="_1fnt">
  <span class="_1j-c" data-sigil="comments-token">1 comment</span>
  <span class="_1j-c">21 shares</span>
</div>
```

No cookies:

```html
<span class="_28-d" id="u_4_6_ye">
  <span class="like_def _28wy">23 Likes</span>
  <span class="cmt_def _28wy">1 comment</span>
</span>
```

**Comment by neon-ninja** [comment]
https://github.com/kevinzg/facebook-scraper/commit/c2862505b5214235bfb737b982e43c9efb5d4efc this should fix it

**Comment by fashandatafields** [comment]
Thanks

**Comment by cmhcheung** [comment]
Thanks.  It's okay now.
