### ISSUE TITLE
Do we need to rotate cookies or proxy if we always runs the script?

### ISSUE THREAD

**Issue by fashandatafields** [kevinzg/facebook-scraper#235]
Please let me know what should rotate [proxy or cookies]. If cookies please guide me on how to rotate cookies.

**Comment by fashandatafields** [comment]
@neon-ninja any idea on this

**Comment by fashandatafields** [comment]
<img width="981" alt="Screenshot 2021-04-25 at 06 24 00" src="https://user-images.githubusercontent.com/67037844/116835081-8953ec00-abde-11eb-97ba-a1d23228b53a.png">
Proxy rotation right?
Wbt any cookie rotation!

**Comment by neon-ninja** [comment]
@fashandatafields I've never needed to do this myself so can't really offer any advice, you'll need to do some testing yourself I think

**Comment by fashandatafields** [comment]
sure
