### ISSUE TITLE
extract time error - wks 

### ISSUE THREAD

**Issue by papaya-ais** [kevinzg/facebook-scraper#238]
It seems to be not able to parse date like 'n wks'
![image](https://user-images.githubusercontent.com/71307736/116837968-92a57e80-ac07-11eb-8d8a-bb043ba13f0e.png)
![image](https://user-images.githubusercontent.com/71307736/116837980-a0f39a80-ac07-11eb-812d-359eac1bb166.png)

I saw code for finding reason, then I found that utils.py doesn't support about "1 wk" "2 wks"
How can I add some regex on it?

**Comment by neon-ninja** [comment]
Hi @papaya-ais - this should do it - https://github.com/kevinzg/facebook-scraper/commit/0f3a190ac42be7037cd35ecc43c7f0c53b7b1a21

**Comment by papaya-ais** [comment]
I downloaded master branch and tested, and then it works!
Thank you @neon-ninja!
Can you publish this commit with PyPI?

**Comment by neon-ninja** [comment]
Sure, published as 0.2.33

**Comment by papaya-ais** [comment]
Checked update 0.2.33. Thank you!
