### ISSUE TITLE
Dealing with Cookies

### ISSUE THREAD

**Issue by trimbilrepo** [kevinzg/facebook-scraper#239]
is the any way how to dealing with cookies without going to copy manually the cookies from the browser?
did try to use login function in the lib. but always says unsuccessful. I think its because the form data need also include the hidden input.

**Comment by fashandatafields** [comment]
@neon-ninja

**Comment by neon-ninja** [comment]
This commit https://github.com/kevinzg/facebook-scraper/commit/e8eab1e01db999474b83f5af593a2ebeeb6c62b1 should fix credential-based login, by sending the hidden inputs as you suggested
