### ISSUE TITLE
Only a small part of longer post is getting returned

### ISSUE THREAD

**Issue by Fdowouo** [kevinzg/facebook-scraper#24]
For longer post, only a fraction of the text is being returned. this is different from the issue #2  as  more than one paragraph is being shown but not the full text. In my use cases, there seems to be a limit  of around 700 characters  after which "**... more**" is displayed at the end of the returned fraction.

Has anyone ran into this issue, any fix ?
Thank you

**Comment by kevinzg** [comment]
I never ran into a long post so I didn't notice this. Can you share a Facebook page with these long posts?

**Comment by Fdowouo** [comment]
You could try this page: _Kamerkongossa_ (@kamerkongossa)

**Comment by fgremler** [comment]
A makeshift solution is to use something like this on all the posts that have been cut off:

```
from bs4 import BeautifulSoup as soup
import requests
import time

fb_url = "yourposturl"

html = requests.get(fb_url).text

html = soup(html, 'html.parser')

text_of_post = html.find('title')
 
```

**Comment by nubpro** [comment]
I've come across this bug and have managed to trace the issue.

When skimming through pages, Facebook does not fully loads the content of every posts entirely. Instead, '... More' will show up in the post which requires a user to click on that link to load the post in full.

I'll submit a PR tomorrow.

**Comment by kevinzg** [comment]
Thank you, @nubpro

**Comment by Tommy95271** [comment]
I encountered an issue where longer text is being cut off. The temporary solution provided by @fgremler no longer works. Could you please take a look at it?
You can try this post url: https://facebook.com/592LDS/posts/718746139941286
