### ISSUE TITLE
Duration and View Count on Video Posts

### ISSUE THREAD

**Issue by grubeli** [kevinzg/facebook-scraper#246]
Gathering duration and view count on video posts would be useful as well

**Comment by neon-ninja** [comment]
This should do what you want - https://github.com/kevinzg/facebook-scraper/commit/d9ab00aa641ff861f7e5031b371677f0f1ccf503

**Comment by grubeli** [comment]
Thank you

**Comment by grubeli** [comment]
When will it be available from pip package?

**Comment by neon-ninja** [comment]
Once a few more people have tested it to make sure I haven't broken latest master with this commit ;)

**Comment by neon-ninja** [comment]
Published on pypi as 0.2.35

**Comment by grubeli** [comment]
Thanks for the quick response.
