### ISSUE TITLE
Comment & Reply Section [Enhancement]

### ISSUE THREAD

**Issue by fashandatafields** [kevinzg/facebook-scraper#249]
Hi @neon-ninja 
Is it possible to get the comment's URL? We already have the commenter's URL but we haven't had the comments URL. I think if comments URL also there means, the output is perfect in facebook-scraper

**Comment by neon-ninja** [comment]
https://github.com/kevinzg/facebook-scraper/commit/d60db61503f1c0b821f1fef35f610fead112e802 this should do it

**Comment by fashandatafields** [comment]
@neon-ninja 

Comment URL :  `https://www.facebook.com/zanupfparty/posts/2858071924459749?comment_id=2858190424447899`

Replied Comment URL: `https://www.facebook.com/zanupfparty/posts/2858071924459749?comment_id=2858190424447899&reply_comment_id=2858387894428152`
