### ISSUE TITLE
TypeError: get_posts() got an unexpected keyword argument 'group'

### ISSUE THREAD

**Issue by yushaamalik** [kevinzg/facebook-scraper#25]
This is my code.

from facebook_scraper import get_posts

for post in get_posts(group='EatsleeprepeatESR'):
    print(post['text'][:50])

Gives this error : 
TypeError: get_posts() got an unexpected keyword argument 'group'

What am I doing wrong?

**Comment by kevinzg** [comment]
I uploaded the last version to PyPI, please update the library and try again.

**Comment by yushaamalik** [comment]
Thankyou so much. It's working now.
