### ISSUE TITLE
public group get specific number of posts

### ISSUE THREAD

**Issue by mpizosdim** [kevinzg/facebook-scraper#254]
I am trying to get some posts from a public group but it always returns 21 posts no matter how many pages I define

```
count1 = 0
for post in get_posts('587430195526306', pages=1): count1 += 1
print(count1)

count10 = 0
for post in get_posts('587430195526306', pages=10): count10 += 1
print(count10)

assert count1!=count10 # should be different
```

Any idea why is this happening?

**Comment by neon-ninja** [comment]
This is a group, in order for group pagination to work, the scraper needs to know it's a group. Try use 
```python
get_posts(group=587430195526306, pages=10)
````
instead.

**Comment by mpizosdim** [comment]
@neon-ninja right. I should have checked better the docs. thanks for the help
