### ISSUE TITLE
indentify cookies/user ban

### ISSUE THREAD

**Issue by fashandatafields** [kevinzg/facebook-scraper#255]
@neon-ninja please let know how cookies/user is banned or not.
How to know it as it automated the facebook-scraper

And I wanted to know how to identify facebook forum is not working or not for example this forum `facebook.com/dasjncmckbad`

**Comment by neon-ninja** [comment]
In both cases you wouldn't get any posts

**Comment by neon-ninja** [comment]
Actually I'm wrong, you get an exception if the page doesn't exist:

```python
Traceback (most recent call last):
  File "./test.py", line 27, in <module>
    posts = list(get_posts('dasjncmckbad'))
  File "/root/git/facebook-scraper/facebook_scraper/facebook_scraper.py", line 284, in _generic_get_posts
    for i, page in zip(counter, iter_pages_fn()):
  File "/root/git/facebook-scraper/facebook_scraper/page_iterators.py", line 36, in generic_iter_pages
    response = request_fn(next_url)
  File "/root/git/facebook-scraper/facebook_scraper/facebook_scraper.py", line 227, in get
    response.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://m.facebook.com/dasjncmckbad/
```

**Comment by neon-ninja** [comment]
See https://github.com/kevinzg/facebook-scraper/issues/195#issuecomment-814591181 for my previous thoughts on how to handle alerting the user if they're temporarily blocked

**Comment by fashandatafields** [comment]
> Actually I'm wrong, you get an exception if the page doesn't exist:
> 
> ```python
> Traceback (most recent call last):
>   File "./test.py", line 27, in <module>
>     posts = list(get_posts('dasjncmckbad'))
>   File "/root/git/facebook-scraper/facebook_scraper/facebook_scraper.py", line 284, in _generic_get_posts
>     for i, page in zip(counter, iter_pages_fn()):
>   File "/root/git/facebook-scraper/facebook_scraper/page_iterators.py", line 36, in generic_iter_pages
>     response = request_fn(next_url)
>   File "/root/git/facebook-scraper/facebook_scraper/facebook_scraper.py", line 227, in get
>     response.raise_for_status()
>   File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 943, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://m.facebook.com/dasjncmckbad/
> ```

can't we make the error specifically stating the reason? with one line message instead of Traceback lines

**Comment by neon-ninja** [comment]
Sure, we could use warnings.warn, in which case it would look like:

```python
/root/git/facebook-scraper/facebook_scraper/page_iterators.py:40: UserWarning: 404 Client Error: Not Found for url: https://m.facebook.com/dasjncmckbad/
  warnings.warn(e)
```
How about that?

**Comment by fashandatafields** [comment]
nice

**Comment by fashandatafields** [comment]
is it commited

**Comment by neon-ninja** [comment]
It is now - https://github.com/kevinzg/facebook-scraper/commit/1a0229e021d81a335f70484d907d83503a95a45c

my test script:

```python
print("start")
posts = list(get_posts('dasjncmckbad'))
print(len(posts))
posts = list(get_posts('100034285300666'))
print(len(posts))
print("end")
```

output:
```python
start
/root/git/facebook-scraper/facebook_scraper/page_iterators.py:40: UserWarning: 404 Client Error: Not Found for url: https://m.facebook.com/dasjncmckbad/
  warnings.warn(e)
0
/root/git/facebook-scraper/facebook_scraper/facebook_scraper.py:218: UserWarning: Locale detected as en_GB - for best results, set to en_US
  warnings.warn(f"Locale detected as {locale} - for best results, set to en_US")
/root/git/facebook-scraper/facebook_scraper/facebook_scraper.py:231: UserWarning: Content not found
  warnings.warn(title)
0
end
```

**Comment by neon-ninja** [comment]
This actually makes for a good pattern for signaling warnings for a few different error states, see https://github.com/kevinzg/facebook-scraper/commit/9873f22b49975059e114c6087b5de10071d9b969

**Comment by fashandatafields** [comment]
@neon-ninja I think we cant capture the error `233: UserWarning: Content not found` with my script.
i  imported facebook-scraper and used post
`for post in get_posts('pokretobnovekraljevinesrbije'):`
`             print(post)`

**Comment by neon-ninja** [comment]
That's correct... Should it throw an exception in that case? But that might break existing code that relies on it returning []. Maybe an option to throw exceptions?

**Comment by fashandatafields** [comment]
yes we need to throw an exception right

**Comment by fashandatafields** [comment]
> yes we need to throw an exception right? @neon-ninja

any commit for this
@neon-ninja

**Comment by fashandatafields** [comment]
Hi @neon-ninja is it good to raise exception like this
<img width="974" alt="Screenshot 2021-05-15 at 06 36 57" src="https://user-images.githubusercontent.com/67037844/118343791-9959bd00-b548-11eb-9090-8d4d07304217.png">

**Comment by fashandatafields** [comment]
@neon-ninja 
<img width="1231" alt="Screenshot 2021-05-15 at 06 59 37" src="https://user-images.githubusercontent.com/67037844/118344462-afb54800-b54b-11eb-9fde-ed066bc9af53.png">
Currently this user is blocked, but I used this cookies to extract forum.

I have printed the response in 3lines
<img width="1048" alt="Screenshot 2021-05-15 at 07 00 22" src="https://user-images.githubusercontent.com/67037844/118344481-decbb980-b54b-11eb-97f5-ba7f14c9bb13.png">


the result was this
`None`
`None`
`<Element 'title' >` 
And returned nothing;  any thing regarding user got blocked

**Comment by neon-ninja** [comment]
I've never seen that before, so I don't know what the title would be, and I can't see it in your screenshot. It's different to a temporary block. Could you print `title.text` with that account? On line 231.

**Comment by fashandatafields** [comment]
the result of the `print(title.text)` is `Facebook`
@neon-ninja

**Comment by neon-ninja** [comment]
that's not super helpful - there must be something else in the HTML we can use - can you send me the HTML? Either `print(response.html)` or 

```python
with open("banned.html", "w") as f:
  f.write(response.html.html)
```

**Comment by fashandatafields** [comment]
[banned.html.zip](https://github.com/kevinzg/facebook-scraper/files/6481761/banned.html.zip)
Is it okay this file? @neon-ninja

**Comment by neon-ninja** [comment]
> Hi @neon-ninja is it good to raise exception like this
> <img alt="Screenshot 2021-05-15 at 06 36 57" width="974" src="https://user-images.githubusercontent.com/67037844/118343791-9959bd00-b548-11eb-9090-8d4d07304217.png">

I think it would be better if there was a specific exception for each error class: like a `NotFound` exception, and a `TemporarilyBanned` exception - then a user could catch those exception types and handle them differently

**Comment by neon-ninja** [comment]
Like so - https://github.com/kevinzg/facebook-scraper/commit/017e25720e8ce8c1db9770083dd14a85db1240ee

**Comment by fashandatafields** [comment]
wow great..

**Comment by neon-ninja** [comment]
This commit (https://github.com/kevinzg/facebook-scraper/commit/e6cfc839e20057abad5459093b9e9902d4b98b93) should throw an exception if your account is disabled, but I don't have any way of testing this

**Comment by fashandatafields** [comment]
I noticed a small issue @neon-ninja 
if the forum is not working means it should break. when the first URL visit `Content Not Found` it shouldn't navigate anymore, right?  
for me it came like this. when I ran a not working post
`Content Not Found`
`You’re Temporarily Blocked`

**Comment by neon-ninja** [comment]
What post?

**Comment by fashandatafields** [comment]
it's not the post, the page. when Facebook detects the page is not there means it solely should return `Content Not Found` and exit the program.

**Comment by neon-ninja** [comment]
What page?

**Comment by fashandatafields** [comment]
`https://www.facebook.com/pokretobnovekraljevinesrbije`

**Comment by fashandatafields** [comment]
@neon-ninja any idea?
why its happening

**Comment by fashandatafields** [comment]
@neon-ninja why i couldnt install latest updates using this code in my environment
`pip install -U git+https://github.com/kevinzg/facebook-scraper.git`

**Comment by neon-ninja** [comment]
> @neon-ninja why i couldnt install latest updates using this code in my environment
> `pip install -U git+https://github.com/kevinzg/facebook-scraper.git`

That should do it, what output do you get when you do that?

**Comment by fashandatafields** [comment]
I renamed the old facebook_scraper dir and `pip install -U git+https://github.com/kevinzg/facebook-scraper.git` but the new facebook_scraper dir didnt came

**Comment by fashandatafields** [comment]
@neon-ninja i tried in another python environment, same result

**Comment by neon-ninja** [comment]
Instead of renaming the folder, try a pip uninstall

**Comment by fashandatafields** [comment]
`pip install facebook-scraper` havent the latest update right?

**Comment by neon-ninja** [comment]
No, I haven't done a pypi release since yesterday

**Comment by fashandatafields** [comment]
> Instead of renaming the folder, try a pip uninstall facebook-scraper. Failing that, try a git clone and `pip install .` from within the checked out directory

tried, it didn't update the latest version even after this `pip uninstall facebook-scraper`  and tried within the environment 
`pip install -U git+https://github.com/kevinzg/facebook-scraper.git`

**Comment by fashandatafields** [comment]
@neon-ninja has a serious issue, i think

**Comment by fashandatafields** [comment]
@neon-ninja have u tried `pip install -U git+https://github.com/kevinzg/facebook-scraper.git`?

**Comment by fashandatafields** [comment]
I think @neon-ninja we need to add this text right?
`raise exceptions.AccountDisabled('Your Account Has Been Disabled')`

<img width="689" alt="Screenshot 2021-05-16 at 05 56 02" src="https://user-images.githubusercontent.com/67037844/118381763-fd918500-b60b-11eb-99e0-c40c841ef18a.png">

**Comment by neon-ninja** [comment]
Couldn't hurt, submit a pull request

**Comment by fashandatafields** [comment]
> Couldn't hurt, submit a pull request

https://github.com/kevinzg/facebook-scraper/pull/260
Ok

**Comment by neon-ninja** [comment]
> `https://www.facebook.com/pokretobnovekraljevinesrbije`

This is a valid page

**Comment by neon-ninja** [comment]
> @neon-ninja have u tried `pip install -U git+https://github.com/kevinzg/facebook-scraper.git`?

Works fine for me, the last line printed is `Successfully installed facebook-scraper-0.2.36`. Do you need to use sudo?

**Comment by fashandatafields** [comment]
> > @neon-ninja have u tried `pip install -U git+https://github.com/kevinzg/facebook-scraper.git`?
> 
> Works fine for me, the last line printed is `Successfully installed facebook-scraper-0.2.36`. Do you need to use sudo? Difference being installing just for your user vs system-wide - different folders

nope

**Comment by neon-ninja** [comment]
Did you solve this problem? If so, how?

**Comment by fashandatafields** [comment]
@neon-ninja i tried by creating a new environment and used the above code to clone, so it cloned the new version
