### ISSUE TITLE
Is scraping facebook legal

### ISSUE THREAD

**Issue by miketrimmel** [kevinzg/facebook-scraper#257]
I´m thinking about legal issues when scraping Facebook sites. Can somebody give me some clarification what officially is allowed or not?

**Comment by neon-ninja** [comment]
It's a violation of their terms of service, for sure. However, if you don't make an account, technically you don't ever agree to those terms.

**Comment by miketrimmel** [comment]
Seems feasible. But what if you would use this content for commercial use? I know the sue of LinkedIn against hiQ

**Comment by neon-ninja** [comment]
I don't think it's possible to operate at that sort of scale with this library
