### ISSUE TITLE
Post Scrape: keep original URL in dict.

### ISSUE THREAD

**Issue by nershman** [kevinzg/facebook-scraper#258]
I'm using the newly added function of scraping specific posts by URL ID. It could be useful to add a dict key which keeps the original URL before transformation, as it's difficult to trace back to the original URL if it was transformed into a story?=... format. In my case I want to keep the original URL so I can link back to my original dict of URLs which also has other information in it.

At the moment to get around this I'm running a new get_post for each url, passing a list containing only one entry:

```
for url in posts:
	url_dict[url] = list(facebook_scraper.get_posts(post_urls = [url], options=my_fb_options, timeout=45))[0]
````

(note thats posts is a list of URLs corresponding to FB posts, url_dict is a dictionary with keys based on those URLs among other things)

Thanks a lot to the devs, I have seen a lot of progress in the past week.

**Comment by neon-ninja** [comment]
Hi, this commit should do what you want - https://github.com/kevinzg/facebook-scraper/commit/f2f653d52c4059da525e4375e66ffaea9223af48 - it returns a new key called `original_request_url` with your original input

**Comment by nershman** [comment]
oh, awesome! thanks.
