### ISSUE TITLE
getting data from private groups

### ISSUE THREAD

**Issue by mpizosdim** [kevinzg/facebook-scraper#259]
Using: 

```
next(get_posts(group='395304918032818', pages=2, options={"allow_extra_requests": False, "comments": False, "reactors": False, "posts_per_page": 20},cookies='cookies.json'))
```

where `'395304918032818'` is a private group and `cookies.json` format:

```
[{
	"Host raw": "https://.facebook.com/",
	"Name raw": "datrasdad",
	"Path raw": "/",
	"Content raw": "fdfsfdghgjfhdf",
	"Expires": "15-05-2023 15:41:27",
	"Expires raw": "1684154487",
	"Send for": "Encrypted connections only",
	"Send for raw": "true",
	"HTTP only raw": "true",
	"SameSite raw": "no_restriction",
	"This domain only": "Valid for subdomains",
	"This domain only raw": "false",
	"Store raw": "firefox-default",
	"First Party Domain": ""
}]
```

gives: `{StopIteration}`

Also tried with credentials: 

```
next(get_posts(group='395304918032818', pages=2, options={"allow_extra_requests": False, "comments": False, "reactors": False, "posts_per_page": 20},credentials=('username@protonmail.com', 'password')))
```

with same result.

Any insights?

**Comment by neon-ninja** [comment]
Likely a cookies issue, related to https://github.com/kevinzg/facebook-scraper/issues/262

**Comment by neon-ninja** [comment]
Your cookies.json doesn't look right - there should be ~7 cookies there, not just one. When extracting the cookies from Firefox, make sure you select the whole facebook.com domain and not just the one datr cookie

**Comment by neon-ninja** [comment]
This commit (https://github.com/kevinzg/facebook-scraper/commit/f5f359ddaed473fa589b7efc595c9b490d08fd58) should make it so the scraper throws an exception if cookies are passed but some are missing
