### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='about', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000285FF521B80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

### ISSUE THREAD

**Issue by wael-sudo** [kevinzg/facebook-scraper#261]

**Comment by neon-ninja** [comment]
What code did you use to generate this bug?

**Comment by wael-sudo** [comment]
from facebook_scraper import get_profile
get_profile(user_id)

**Comment by neon-ninja** [comment]
What version do you have?

**Comment by wael-sudo** [comment]
how to check?

**Comment by neon-ninja** [comment]
`pip freeze | grep facebook`

**Comment by wael-sudo** [comment]
facebook-scraper==0.2.36  the version  and the user_id its a variable where  i  store  some the  users id's  as if  "zuck " etc ..

**Comment by wael-sudo** [comment]
hi there i am over that bug but im having another error here any idea?
 UserWarning: Locale detected as fr_FR - for best results, set to en_US  warnings.warn(f"Locale detected as {locale} - for best results, set to en_US")

**Comment by neon-ninja** [comment]
How did you fix the ConnectionErrror?

As it says, your locale is detected as French - this might cause you problems for some of the scrapers functions. If you're using an account you can set the language of your account. If not, you can use a proxy from an English speaking country.

**Comment by wael-sudo** [comment]
i dont know how i fixed the ConnectionError exactly but i tired it in another ide it worked
