### ISSUE TITLE
Why cant we scrape some url under the `get_posts` function for these URL's

### ISSUE THREAD

**Issue by fashandatafields** [kevinzg/facebook-scraper#266]
there are some URLs that are not giving the post details as JSON, it gives less information.

https://www.facebook.com/zelenskiy95
I got this result
`[{'original_request_url': 'zelenskiy95', 'post_url': 'https://m.facebook.com/zelenskiy95'}]`

https://www.facebook.com/profile.php?id=100002141889628

@neon-ninja please consider

**Comment by neon-ninja** [comment]
post_urls expects links to actual posts, not a link to a profile. Use `get_profile` for that
