### ISSUE TITLE
JSON result's  [comment not scraping] [bug]

### ISSUE THREAD

**Issue by fashandatafields** [kevinzg/facebook-scraper#267]
Hi @neon-ninja 
I was passing cookies and tried to scrape some post, but unfortunately, facebook-scraper isn't getting the comments even the posts has comments. 
Note: I  pass working cookies.

`https://www.facebook.com/gp.gov.ua/posts/1610364829101773`
`https://www.facebook.com/YuliaTymoshenko/posts/4133922966645775`

@neon-ninja early this morning commenter time didn't scrape properly now, the entire comment section arent scraping. May be facebook may have upgraded their version, i don't know actually

**Comment by fashandatafields** [comment]
@neon-ninja but i used proxies. does the proxy affect the comment not been scraped

**Comment by neon-ninja** [comment]
Both worked fine for me, the problem must be with your proxy
