### ISSUE TITLE
ImportError: cannot import name 'get_profile' from 'facebook_scraper' 

### ISSUE THREAD

**Issue by widedM** [kevinzg/facebook-scraper#269]
ImportError: cannot import name 'get_profile' from 'facebook_scraper' (C:\Users\LENOVO\Anaconda3\lib\site-packages\facebook_scraper\__init__.py)

**Comment by neon-ninja** [comment]
You need to update - `pip install -U facebook-scraper`

**Comment by widedM** [comment]
yes i did it but in vain

**Comment by neon-ninja** [comment]
What code did you use to get this error?

What is the output of `pip freeze | grep facebook`? What is the output of 

```python
import facebook_scraper
print(dir(facebook_scraper))
```

**Comment by widedM** [comment]
the output is:

['Credentials', 'DEFAULT_REQUESTS_TIMEOUT', 'FacebookScraper',
'Iterator', 'Optional', 'Post', 'Tuple', 'Union', '__builtins__',
'__cached__', '__doc__', '__file__', '__loader__', '__name__',
'__package__', '__path__', '__spec__', '_scraper', 'constants', 'csv',
'enable_logging', 'extractors', 'facebook_scraper', 'fb_types',
'get_posts', 'locale', 'logger', 'logging', 'page_iterators', 'sys',
'utils', 'write_posts_to_csv']

I used this code to get that error : from facebook_scraper import get_profile

get_profile("zuck") # Or get_profile("zuck", cookies="cookies.txt")

**Comment by neon-ninja** [comment]
That's definitely an old version of facebook-scraper - what's the output of `print(facebook_scraper.__file__)`?
