### ISSUE TITLE
Passing cookies as JSON [bug]

### ISSUE THREAD

**Issue by fashandatafields** [kevinzg/facebook-scraper#270]
I was passing cookies as JSON format, the script didn't extract the expected post. but Netscape format gave the expected JSON.

Passed as JSON cookies, below is the result
```
`{
   "original_request_url":"https://m.facebook.com/story.php?story_fbid=1781867791974810&id=284294775065460&_rdr",
   "post_url":"https://m.facebook.com/story.php?story_fbid=1781867791974810&id=284294775065460&_rdr"
}`
```
Note: passing as cookies as JSON is basically not working

**Comment by neon-ninja** [comment]
Working fine for me, what does the structure of your JSON look like?

**Comment by fashandatafields** [comment]
`[{,,,,,},{,,,,,}]`
list type

**Comment by neon-ninja** [comment]
key names?

**Comment by fashandatafields** [comment]
@neon-ninja please chk ur mail

**Comment by fashandatafields** [comment]
i ve send u a working cookies can test

**Comment by neon-ninja** [comment]
You should only feed the scraper cookies for the https://.facebook.com/ domain, and not all these other domains

**Comment by neon-ninja** [comment]
Maybe these cookies just aren't valid any more, just regenerate them?

**Comment by fashandatafields** [comment]
these are latest cookies

**Comment by fashandatafields** [comment]
@neon-ninja In JSON template it gives expiry but Netscape template haven't expiry? which template is good for long term?

**Comment by fashandatafields** [comment]
i think in read me u can add this extension too 
https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg/related?hl=en

<img width="1056" alt="Screenshot 2021-05-18 at 15 32 45" src="https://user-images.githubusercontent.com/67037844/118633241-e2cb3600-b7ee-11eb-97b8-967c16cc1b51.png">

**Comment by neon-ninja** [comment]
this should fix it https://github.com/kevinzg/facebook-scraper/commit/168a245aa94f2a01710d938be7308732862c8b55. Netscape format has expiry as a unix timestamp

**Comment by fashandatafields** [comment]
@neon-ninja what is this update

**Comment by neon-ninja** [comment]
the extension Cookie Quick Manager's JSON format passes a domain like this "https://.facebook.com/" when it should be like this ".facebook.com"
