### ISSUE TITLE
Accounts ban

### ISSUE THREAD

**Issue by straiffix** [kevinzg/facebook-scraper#275]
Hi, I would like to scrape some private groups and use account information for this, but I wonder what is a probability that accounts get banned. As I heard, facebook tries to block requests, so it's better to use selenium for user actions simulation. As I see, you are using only requests for login and open\private groups scraping, so I would like to ask you, did you get blocked account for suspicious actions in some time? And does selenium really performs better, or usual requests are okay too? I am aiming to scrape only two groups, about 400-800 posts per day with one account.

**Comment by neon-ninja** [comment]
I think at that sort of scale, you should be fine, it's more at the thousands of posts scale where you start to see temporary bans. Even then, the temporary ban only lasts about an hour.

**Comment by fashandatafields** [comment]
ic
