### ISSUE TITLE
Facebook Scraping [doubt]

### ISSUE THREAD

**Issue by fashandatafields** [kevinzg/facebook-scraper#276]
Hi @neon-ninja 
I passed Netscape cookies and ran the facebook-scraper using the console. It gave good JSON for this post
`http://facebook.com/1610364829101773.` and later I again ran after an hour back. It didn't return reactions
```
`"reactors":"None",
      "w3_fb_url":"None",
      "reactions":"None",
      "reaction_count":"None"`
```
even commenter URL is none

I feel something wrong when scraping.

**Comment by neon-ninja** [comment]
What steps did you take to cause this problem? Were you scraping heavily during that hour?

**Comment by fashandatafields** [comment]
Basically when we pass cookie
It actually logged in to FB and scrape the post
So when the proxy is slow page loads for a while to give a complete rendered page
While pages are rendering it will scrape the result before rendering and returns with a bad result
This what I think basically
@neon-ninja 
Am I correct?

Couldn't we wait until page/post loads 100% and then extract all data regarding that post?

**Comment by neon-ninja** [comment]
That's not how it works - requests.get is a blocking operation - it doesn't return until the entire request is complete. It's all or nothing. If it's slow you might hit a timeout error though - `requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='m.facebook.com', port=443): Read timed out. (read timeout=0.1)`

**Comment by fashandatafields** [comment]
If that's the case, why is not returning
`commenter URL`
`"reactors":"None",
  "w3_fb_url":"None",
  "reactions":"None",
  "reaction_count":"None"`

`http://facebook.com/1610364829101773`

Note: Btw I'm passing private proxy

**Comment by fashandatafields** [comment]
@neon-ninja if u needed a private proxy, I can share with u with the cookies

**Comment by neon-ninja** [comment]
Sure, post your proxy details

**Comment by fashandatafields** [comment]
@neon-ninja please check ur mail.

**Comment by neon-ninja** [comment]
The proxy is fine, the problem is your cookies:

```python
from facebook_scraper import _scraper
from facebook_scraper import *
set_cookies("top.txt")
print(_scraper.is_logged_in())
```
returns False

**Comment by fashandatafields** [comment]
IC, @neon-ninja But I directly exported Netscape cookies from this
https://addons.mozilla.org/en-US/firefox/addon/cookie-quick-manager/

**Comment by neon-ninja** [comment]
Did you logout of facebook in that session before or after exporting cookies?

**Comment by fashandatafields** [comment]
Is there any way to export working cookies 
What I did was. Before login Into Facebook. I cleared history and then logged In and exported the cookies

**Comment by neon-ninja** [comment]
The original cookies you sent me (with filename produc_cookies.json) are still valid, why not just use those?

**Comment by fashandatafields** [comment]
```
from facebook_scraper import _scraper
from facebook_scraper import *
for file in ["top.txt", "produc_cookies.json", "newjson.json", "cookies.txt", "cookies.json"]:
    set_cookies(file)
    print(file, _scraper.is_logged_in())
```
this code is really helpfull

**Comment by neon-ninja** [comment]
This commit (https://github.com/kevinzg/facebook-scraper/commit/9af15d86c26b76357e2f72198a955ac59631a558) will make it so that the scraper throws an exception if you pass invalid cookies

**Comment by fashandatafields** [comment]
@neon-ninja how to make cookies, not to expire quickly

**Comment by fashandatafields** [comment]
@neon-ninja can u share me the html, when logging using my cookies. is it possible to share with via email please

**Comment by neon-ninja** [comment]
They don't expire quickly, the expiry is like 2 years away. produc_cookies.json is still valid, what did you do differently with those compared to say, top.txt?

**Comment by fashandatafields** [comment]
@neon-ninja  top.txt is an account that is 2FA authenticated account.

**Comment by neon-ninja** [comment]
Maybe that's the problem?

**Comment by fashandatafields** [comment]
if we figured it out means we are good. by getting the HTML response which is preventing from logging.
is it possible to share me the file @neon-ninja

**Comment by neon-ninja** [comment]
Why do you need me to extract html for you when you can just as easily do it yourself?

**Comment by fashandatafields** [comment]
ok, can i know where is the place to put an debug print @neon-ninja

**Comment by neon-ninja** [comment]
I'm not sure I understand - what do you want the HTML for? It's just the standard facebook login page.

**Comment by neon-ninja** [comment]
What do you get when you run those cookies yourself?

**Comment by fashandatafields** [comment]
`>>> for file in ["cookies3.txt"]:
...     set_cookies(file)
...     print(file, _scraper.is_logged_in())
... 
cookies3.txt False`

@neon-ninja

**Comment by neon-ninja** [comment]
Then that doesn't seem to have helped. Maybe Facebook have somehow flagged your account, such that any time you try connect from a new IP, you're forced to log in again

**Comment by fashandatafields** [comment]
@neon-ninja Hi
Is it possible, send a username and password which consists of 2FA A/C? when logged in Facebook will ask the code of the 2FA and passing the code obtained from authentication API/App and set when it required

**Comment by neon-ninja** [comment]
Also note that you don't technically need facebook-scraper to observe this behaviour, you can just use curl like so:

```bash
curl --silent --head --cookie cookies3.txt https://facebook.com/settings|grep cookie
set-cookie: c_user=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=-1621542934; path=/; domain=.facebook.com
set-cookie: spin=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=-1621542934; path=/; domain=.facebook.com; httponly
set-cookie: xs=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=-1621542934; path=/; domain=.facebook.com; httponly
```

See how facebook says to delete those invalid cookies?

**Comment by neon-ninja** [comment]
https://github.com/kevinzg/facebook-scraper/commit/18d9d539cb8fc95ac527027f81289071a0423b31 this commit should make it possible to enter your 2FA token on the command line
