### ISSUE TITLE
Users posts

### ISSUE THREAD

**Issue by panichmaxim** [kevinzg/facebook-scraper#277]
Sorry for possibly dumb question, but I cant get a posts from a specific user. For example:

`for post in facebook_scraper.get_posts("zuck"):`
 `   print(post['text'][:50])`

    
 Shows me error: 
 

`Exception while requesting URL: https://m.facebook.com/zuck/posts/`
`Exception: HTTPError('404 Client Error: Not Found for url: https://m.facebook.com/zuck/posts/')`

Meanwhile get_profile() and get_posts() for groups works fine.
My goal is to check for new posts from different users, thx.

**Comment by neon-ninja** [comment]
You need to pass cookies to get a users posts, see the readme

**Comment by panichmaxim** [comment]
Got it, thx!  @neon-ninja
Is there some examples of how I can create such cookies? Not so obvious for me =(

`cookies: One of:`
`The path to a file containing cookies in Netscape or JSON format`
`A CookieJar`
`A dictionary that can be converted to a CookieJar with cookiejar_from_dict`

**Comment by neon-ninja** [comment]
You could either use your browsers developer tools or a browser extension. EditThisCookie or Cookie Quick Manager should work.

**Comment by neon-ninja** [comment]
I've updated the readme to make it clearer - https://github.com/kevinzg/facebook-scraper/commit/0688f898b0cb993b800164c1ebdc21be45a33f87

**Comment by panichmaxim** [comment]
Thx!
