### ISSUE TITLE
Scrapping slower than 2 months earlier

### ISSUE THREAD

**Issue by dimitriskg7** [kevinzg/facebook-scraper#278]
Hello, so I noticed that the last 3 days my scrapping has slowed down drastically. For example at 17/05/2021 I scraped 16,000 posts from a page in 2-3 hours, and now it takes much longer, about 1000 post per hour. Do you have any clue what may have happened?

**Comment by neon-ninja** [comment]
This is probably related to https://github.com/kevinzg/facebook-scraper/issues/161 - prior to v0.2.31, the scraper would only extract up to 4 image links, now it can extract all image links in a post. Extracting each link requires an additional request (equivalent to clicking on the image), which can be slow. You can use the options introduced in https://github.com/kevinzg/facebook-scraper/pull/212 if you need to optimise for speed.
