### ISSUE TITLE
About no. of comments

### ISSUE THREAD

**Issue by cmhcheung** [kevinzg/facebook-scraper#283]
May I know if the comments count and the no. of comment_text are sometimes different?  I found it happens in Facebook, for example, it shows there are 24 comments but I can only see 23 comments or so.

**Comment by neon-ninja** [comment]
Sometimes there's a difference due to counting replies or only top level comments. Also sometimes comments are suppressed for being spam or "not relevant"

**Comment by cmhcheung** [comment]
I found that I cannot distinguish reply to reply comments as they are all presented in the replies.  Is there any possible way I can maintain the layers, i.e. know that the reply is to the reply rather than to the original comment?

**Comment by neon-ninja** [comment]
Mobile facebook doesn't distinguish, the only way you can tell is by the @ name mention in the text
