### ISSUE TITLE
get_photos() fork

### ISSUE THREAD

**Issue by lennoxho** [kevinzg/facebook-scraper#288]
Hi! 

I have a fork of facebook-scraper with get_photos() support.
https://github.com/lennoxho/facebook-scraper

It's NOT just a wrapper over get_posts();
I've extended page_iterators to look at "/{account}/photos/"

Feel free to get inspiration from/merge.

**Comment by neon-ninja** [comment]
Great! Please submit a pull request

**Comment by lennoxho** [comment]
https://github.com/kevinzg/facebook-scraper/pull/289

**Comment by neon-ninja** [comment]
Merged
