### ISSUE TITLE
Use account without logging in on each subsequent request

### ISSUE THREAD

**Issue by lazanet** [kevinzg/facebook-scraper#29]
If I'm not mistaken, at the moment scraping several pages in a row would have `_login_user` triggered for each `_get_posts` call. This might be flagged by facebook as suspicious.

In my usecase I fixed it this way:
```python
def _get_posts(path, pages=10, timeout=5, sleep=0, credentials=None):
    """Gets posts for a given account."""
    global _session, _timeout

    url = f'{_base_url}/{path}'
    if _session is None:
        _session = HTMLSession()
        _session.headers.update(_headers)

        if credentials:
            _login_user(*credentials)
```
That however this isn't optimal for people who use several different accounts in their workloads, so I believe it should be discussed.

**Comment by neon-ninja** [comment]
This is now solved by passing in cookies
