### ISSUE TITLE
reaction bug?!

### ISSUE THREAD

**Issue by Eevaariste** [kevinzg/facebook-scraper#292]
hello, so i was testing and i noticed than when a reaction like "haha" is more than "likes" post.get('likes', '0') returns none.

**Comment by neon-ninja** [comment]
Do you have a sample post where this occurs?

**Comment by Eevaariste** [comment]
i have group posts but the group is private.

**Comment by neon-ninja** [comment]
Do you have a publicly available post where this occurs?

**Comment by Eevaariste** [comment]
i solved this by adding the reactions dictionary.. only in one private group that occured i dont know why
