### ISSUE TITLE
Duplicate post text

### ISSUE THREAD

**Issue by masalha-alaa** [kevinzg/facebook-scraper#293]
For some reason I'm getting the post text doubled. For example:

```
for post in get_posts('verge', pages=3, extra_info=True, timeout=60, options={'posts_per_page': 200}):
    # ...
```
**post['text']:**
The e-commerce giant’s biggest entertainment acquisition yet

The e-commerce giant’s biggest entertainment acquisition yet

THEVERGE.COM
Amazon buys MGM for $8.45 billion
The studio behind the James Bond and Rocky franchises.

THEVERGE.COM
Amazon buys MGM for $8.45 billion

**post['post_text']:**
'The e-commerce giant’s biggest entertainment acquisition yet

The e-commerce giant’s biggest entertainment acquisition yet

THEVERGE.COM
Amazon buys MGM for $8.45 billion
The studio behind the James Bond and Rocky franchises.'

**Comment by mennatallah644** [comment]
I am facing the same problem

**Comment by masalha-alaa** [comment]
I examined the raw html response, and found that there's only 1 appearance of the text:

`<div><span><p>A big change for the series</p></span></div>`

But when the parser `extract_text()` calls `element.find('p, header, span[role=presentation], .story_body_container>div')`, two appearances are found.

The line:
`[(node.tag, node.text) for node in element.find('p, header, span[role=presentation], .story_body_container>div')]`
produces:

> [('header', '\u200f\u200eThe Verge\u200e\u200f\n\u200f40\u200f דקות ·'), **('div', 'A big change for the series')**, **('p', 'A big change for the series')**, ('div', 'THEVERGE.COM\nOpen-world RPG Pokémon Legends: Arceus is launching January 28th, 2022\nOld time Pokémon.'), ('header', 'THEVERGE.COM\nOpen-world RPG Pokémon Legends: Arceus is launching January 28th, 2022')]

If we remove either `p` or `.story_body_container>div` from the search pattern, the result looks good:

Remove `.story_body_container>div`:
`[(node.tag, node.text) for node in element.find('p, header, span[role=presentation]')]`

> [('header', '\u200f\u200eThe Verge\u200e\u200f\n\u200f40\u200f דקות ·'), ('p', 'A big change for the series'), ('header', 'THEVERGE.COM\nOpen-world RPG Pokémon Legends: Arceus is launching January 28th, 2022')]

Remove `p`:
`[(node.tag, node.text) for node in element.find('header, span[role=presentation], .story_body_container>div')]`

> [('header', '\u200f\u200eThe Verge\u200e\u200f\n\u200f40\u200f דקות ·'), ('div', 'A big change for the series'), ('div', 'THEVERGE.COM\nOpen-world RPG Pokémon Legends: Arceus is launching January 28th, 2022\nOld time Pokémon.'), ('header', 'THEVERGE.COM\nOpen-world RPG Pokémon Legends: Arceus is launching January 28th, 2022')]

**Comment by neon-ninja** [comment]
Hi, this should fix the problem https://github.com/kevinzg/facebook-scraper/commit/da3efa99a0cb6e490de82b1d379dd7bb61dcdcd5

**Comment by masalha-alaa** [comment]
Looking good now, thanks.
