### ISSUE TITLE
Proxy issue

### ISSUE THREAD

**Issue by fashandatafields** [kevinzg/facebook-scraper#307]
why am i getting this error @neon-ninja 

`HTTPSConnectionPool(host='m.facebook.com', port=443): Max retries exceeded with url: /10642907715/posts/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f39d339d550>: Failed to establish a new connection: [Errno 111] Connection refused')))`

**Comment by neon-ninja** [comment]
Your proxy isn't working
