### ISSUE TITLE
Weird error statement given from the script

### ISSUE THREAD

**Issue by fashandatafields** [kevinzg/facebook-scraper#309]
`A login (cookies) is required to see this page` forumid = 160836574053016
`int() argument must be a string, a bytes-like object or a number, not 'NoneType'`      forum id = 411066625581056  post id = 4160196777334670

What is this issue, I experience some issues while scraping @neon-ninja 

But running manually is giving the result. But I'm currently running with celery

**Comment by neon-ninja** [comment]
As it says, cookies are required

**Comment by fashandatafields** [comment]
@neon-ninja 
what can be this issue
`int() argument must be a string, a bytes-like object or a number, not 'NoneType'  for this forum id = 411066625581056 post id = 4160196777334670`

**Comment by fashandatafields** [comment]
> As it says, cookies are required

But it scrapes `160836574053016`  manually but when schedule with celery it occurs this. 
`{'post_id': '2344416302361688', 'text': '4 cents of every tax rand you paid went to the Guptas. Are we on the road to recovery from corruption, or is it forever entrenched in our land? Watch Judge for Yourself on Tuesday at 8h30pm on #DStv403.', 'post_text': '4 cents of every tax rand you paid went to the Guptas. Are we on the road to recovery from corruption, or is it forever entrenched in our land? Watch Judge for Yourself on Tuesday at 8h30pm on #DStv403.', 'shared_text': '', 'time': '2021-06-02 02:30:03', 'image': None, 'image_lowquality': None, 'images': [], 'images_description': [], 'images_lowquality': [], 'images_lowquality_description': [], 'video': 'https://video.fcmb2-1.fna.fbcdn.net/v/t42.1790-2/193999019_386804035959871_1259534335010099613_n.mp4?_nc_cat=105&ccb=1-3&_nc_sid=985c63&efg=eyJ2ZW5jb2RlX3RhZyI6InN2ZV9zZCJ9&_nc_ohc=-0ZyP8yGhbIAX9Jq0qH&_nc_rml=0&_nc_ht=video.fcmb2-1.fna&oh=fc393898290296f6f89040eba6428ac8&oe=60B70706', 'video_duration_seconds': None, 'video_height': 1080, 'video_id': '630787431652839', 'video_quality': '1080p', 'video_size_MB': 99.367755, 'video_thumbnail': 'https://scontent.fcmb2-1.fna.fbcdn.net/v/t15.13418-10/cp0/e15/q65/s320x320/187790135_588828528718001_1832428523695282034_n.jpg?_nc_cat=108&ccb=1-3&_nc_sid=ccf8b3&_nc_ohc=T0r9ZH79a-wAX9jjZHt&_nc_ht=scontent.fcmb2-1.fna&tp=9&oh=6f3f6b53f666524624b4790feaee11ef&oe=60BB9195', 'video_watches': 1857, 'video_width': 1920, 'likes': 13, 'comments': 17, 'shares': 0, 'post_url': 'https://facebook.com/160836574053016/posts/2344416302361688', 'link': None, 'user_id': '160836574053016', 'username': 'eNCAnews', 'user_url': 'https://facebook.com/eNCAnews/?__tn__=C-R', 'is_live': False, 'factcheck': None, 'shared_post_id': None, 'shared_time': None, 'shared_user_id': None, 'shared_username': None, 'shared_post_url': None, 'available': True, 'comments_full': None, 'reactors': None, 'w3_fb_url': None, 'reactions': None, 'reaction_count': None}`

**Comment by neon-ninja** [comment]
> @neon-ninja
> what can be this issue
> `int() argument must be a string, a bytes-like object or a number, not 'NoneType' for this forum id = 411066625581056 post id = 4160196777334670`

Can you provide the code to reproduce this error? Are you extracting comments?

**Comment by neon-ninja** [comment]
Sometimes facebook lets you extract posts without cookies a few times from any given IP, but after a certain amount of requests, it starts insisting you login. Or, you might be able to view a post, but subsequent requests (requesting the full text, or the high resolution image, or a reply to a comment) require login

**Comment by fashandatafields** [comment]
> > @neon-ninja
> > what can be this issue
> > `int() argument must be a string, a bytes-like object or a number, not 'NoneType' for this forum id = 411066625581056 post id = 4160196777334670`
> 
> Can you provide the code to reproduce this error? Are you extracting comments?

`for post in get_posts(forum, pages=pages, timeout=70, options={'reactors': True}):`
       ` print(post)`

**Comment by neon-ninja** [comment]
I'm unable to reproduce that error with that code.

**Comment by fashandatafields** [comment]
@neon-ninja what is this 
`Object of type Element is not JSON serializable`

**Comment by neon-ninja** [comment]
As it says, you can't JSON serialise an Element

**Comment by fashandatafields** [comment]
@neon-ninja there is an issue with the latest commit I think related to comment
```
>>> from facebook_scraper import _scraper
>>> from facebook_scraper import *
>>> set_cookies("1.txt")
>>> _scraper.is_logged_in()
True
>>> posts = list(get_posts(post_urls=["https://www.facebook.com/ArmataRo/posts/4027833410643061"], timeout=90, cookies="1.txt", options={'comments': True, 'reactors': True, 'progress': True}))

[{'original_request_url': 'https://www.facebook.com/ArmataRo/posts/4027833410643061', 'post_url': 'https://facebook.com/story.php?story_fbid=4027833410643061&id=879862792106821', 'post_id': '152841466750551', 'text': 'Pregătiți pentru "ARGEDAVA 21"\n\nÎn dimineața zilei de 23 mai, forțele principale ale Batalionului 2 Infanterie "Călugăreni" s-au deplasat în poligoanele de instrucție în vederea participării la exercițiul multinațional "ARGEDAVA 21".\n\nAcesta este un exercițiu în teren/real (LIVEX), planificat de către Divizia 2 Infanterie "Getica" și condus de către Brigada 1 Mecanizată "Argedava", care urmărește instruirea întrunită a Batalionului 2 Infanterie "Călugăreni", Batalionului 114 Tancuri "Petru Cercel" , Batalionului 113 Artilerie "Bărăganul" , Batalionului 55 Apărare Antiaeriană "Someș" și a Batalionului 117 Sprijin Logistic "Colonel Alexandru Polyzu".\n\nExercițiul face parte din seria de exerciții GETICA 21/DACIA 21 LIVEX, unul dintre cele mai complexe evenimente de instruire ale Armatei României din ultimii ani care integrează secvențe de pregătire a unor forțe românești, aliate și partenere, în context NATO și al parteneriatului româno-american, deopotrivă.\n\n#ArmataRomaniei #B2I #Bg1Mc #MApN\n\nText și imagini: Locotenent Sergiu Iosub', 'post_text': 'Pregătiți pentru "ARGEDAVA 21"\n\nÎn dimineața zilei de 23 mai, forțele principale ale Batalionului 2 Infanterie "Călugăreni" s-au deplasat în poligoanele de instrucție în vederea participării la exercițiul multinațional "ARGEDAVA 21".\n\nAcesta este un exercițiu în teren/real (LIVEX), planificat de către Divizia 2 Infanterie "Getica" și condus de către Brigada 1 Mecanizată "Argedava", care urmărește instruirea întrunită a Batalionului 2 Infanterie "Călugăreni", Batalionului 114 Tancuri "Petru Cercel" , Batalionului 113 Artilerie "Bărăganul" , Batalionului 55 Apărare Antiaeriană "Someș" și a Batalionului 117 Sprijin Logistic "Colonel Alexandru Polyzu".\n\nExercițiul face parte din seria de exerciții GETICA 21/DACIA 21 LIVEX, unul dintre cele mai complexe evenimente de instruire ale Armatei României din ultimii ani care integrează secvențe de pregătire a unor forțe românești, aliate și partenere, în context NATO și al parteneriatului româno-american, deopotrivă.\n\n#ArmataRomaniei #B2I #Bg1Mc #MApN\n\nText și imagini: Locotenent Sergiu Iosub', 'shared_text': '', 'time': '2021-05-23 18:46:00', 'image': None, 'image_lowquality': None, 'images': [], 'images_description': [], 'images_lowquality': [], 'images_lowquality_description': [], 'video': None, 'video_duration_seconds': None, 'video_height': None, 'video_id': '152841466750551', 'video_quality': None, 'video_size_MB': None, 'video_thumbnail': 'https://scontent-lga3-1.xx.fbcdn.net/v/t15.5256-10/fr/cp0/e15/q65/183445983_152841863417178_6411428426778658943_n.jpg?_nc_cat=107&ccb=1-3&_nc_sid=ccf8b3&efg=eyJpIjoidCJ9&_nc_ohc=eNWEyRSUXe4AX__osnO&_nc_ht=scontent-lga3-1.xx&tp=14&oh=2bd0d75e60844b2354eed8c91c05dee1&oe=60BC6F1B', 'video_watches': None, 'video_width': None, 'likes': 476, 'comments': 11, 'shares': 38, 'link': None, 'user_id': '879862792106821', 'username': 'Armata României', 'user_url': 'https://facebook.com/ArmataRo/?_ft_=qid.6969022047092496502%3Amf_story_key.5480520070342404845%3Atop_level_post_id.152841466750551%3Acontent_owner_id_new.879862792106821%3Apage_id.879862792106821%3Atracking_source.video_home%3Astory_location.31%3Astory_attachment_style.video_autoplay%3Atds_flgs.3%3Aott.AX9beEQ9bdGI6xik&__tn__=C', 'is_live': False, 'factcheck': None, 'shared_post_id': None, 'shared_time': None, 'shared_user_id': None, 'shared_username': None, 'shared_post_url': None, 'available': True, 'comments_full': None, 'reactors': [], 'w3_fb_url': 'https://www.facebook.com/story.php?story_fbid=4027833410643061&id=879862792106821', 'reactions': {'like': 476, 'love': 12, 'haha': 2, 'care': 1, 'angry': 1}, 'reaction_count': 492, 'image_id': None, 'image_ids': [], 'fetched_time': '2021-06-02 03:44:49'}]

```

**Comment by neon-ninja** [comment]
Videos have 2 ways of accessing them:
https://m.facebook.com/4027833410643061 -> redirects to https://m.facebook.com/story.php?story_fbid=4027833410643061&id=879862792106821, extraction works
https://m.facebook.com/ArmataRo/posts/4027833410643061 -> redirects to https://m.facebook.com/watch/?v=152841466750551&_rdr, extraction doesn't work - how could it? There are no comments on this page

**Comment by fashandatafields** [comment]
@neon-ninja
`int() argument must be a string, a bytes-like object or a number, not 'NoneType'`
This error pops out from the script while scrolling and getting post

**Comment by neon-ninja** [comment]
I'd need to know what line of code that's referring to

**Comment by fashandatafields** [comment]
@neon-ninja 
 
```
`>>> from facebook_scraper import get_posts`
`>>> for post in get_posts("182243201819458", pages=30, timeout=100, options={"reactors": True, "posts_per_page": 75}):`
`...     print(post)`
```
At this point, it occurs in get_posts

**Comment by neon-ninja** [comment]
Try turn on debug logging

**Comment by fashandatafields** [comment]
@neon-ninja 
may I know what is this 
```
: UserWarning: Facebook served mbasic/noscript content unexpectedly on http://ipinfo.io/
  warnings.warn(f"Facebook served mbasic/noscript content unexpectedly on {response.url}")
```

**Comment by neon-ninja** [comment]
It's a warning to try detect mbasic / noscript content. Safe to ignore here.

**Comment by neon-ninja** [comment]
If you're catching this exception can you also print the full stacktrace?

**Comment by fashandatafields** [comment]
sure i'll print the stacktrace

@neon-ninja its TypeError
<img width="850" alt="Screenshot 2021-06-04 at 19 26 09" src="https://user-images.githubusercontent.com/67037844/120812691-d96df780-c56a-11eb-8b77-c9440e98b26b.png">
