### ISSUE TITLE
Unable to collect posts beyond a certain number due to Temporary Block

### ISSUE THREAD

**Issue by dimitriskg7** [kevinzg/facebook-scraper#310]
Hi,

First of all, this is a really great tool, so thank you very much for your work!
I want to scrape some private groups. However, every time I'm trying, I get the message ```You are Temporarily Blocked``` after scraping from 100 posts up to 9000 posts, even thought the group I'm trying to scrape has way more posts. I have tested alt accounts too. Is there any possible solution to my problem so that Facebook don't block me every time so quick? Or if there is a way I can continue from where I left off because I was blocked?
Furthermore, I'm using ```"allow_extra_requests":  True``` since I want to download all photos to max quality. Could you add ```get_photos``` for groups to speed up scraping or is there any other way I could get the link of the first photo (at max quality) of every post faster without using allow_extra_requests which is slow?

**Comment by neon-ninja** [comment]
Increasing posts_per_page might help, as then you'd make fewer requests. Adding some `time.sleep` lines might help reduce the rate at which you're making requests. Yes, you can continue from a pagination url, by passing the url as the `start_url` argument to `get_posts`. These pagination URLs can be seen in the logs if you have debug logging enabled, or you can pass a callback function as `request_url_callback` to `get_posts` to handle extracting these pagination urls. Here's some sample code:

```python
import time
from facebook_scraper import *

results = []
start_url = None
def handle_pagination_url(url):
    start_url = url
set_cookies("cookies.txt")
while True:
    try:
        if start_url:
            posts = get_posts("Nintendo", page_limit=None, start_url=start_url, request_url_callback=handle_pagination_url)
        else:
            posts = get_posts("Nintendo", page_limit=None, request_url_callback=handle_pagination_url)
        for post in posts:
            print(len(results))
            results.append(post)
        print("All done")
        break
    except exceptions.TemporarilyBanned:
        print("Temporarily banned, sleeping for 10m")
        time.sleep(600)
```

AFAIK, facebook only provides the high resolution image URL if you click on the photo

**Comment by cmhcheung** [comment]
Sorry I'm a newbie in python and I'm not sure how to eliminate the following error.  Do we need to define the exception somewhere?

    except exceptions.TemporarilyBanned:
NameError: name 'exceptions' is not defined

**Comment by neon-ninja** [comment]
The line `from facebook_scraper import *` should import exceptions

**Comment by dimitriskg7** [comment]
Thanks for all your help! with the code above I can finally scrape some data! Only one problem. I get this weird Warning every few posts, If you know what it means ```UserWarning: Facebook served mbasic/noscript content unexpectedly on https://m.facebook.com/photo/view_full_size/?fbid=288277231647594&ref_component=mbasic_photo_permalink&ref_page=%2Fwap%2Fphoto.php&refid=13&_ft_=qid.6969143656967528552%3Amf_story_key.1312900498823511%3Atop_level_post_id.1312900498823511%3Atl_objid.1312900498823511%3Acontent_owner_id_new.100013959583061%3Apage_id.1213736755406553%3Asrc.22%3Astory_location.6%3Astory_attachment_style.photo%3Afilter.GroupStoriesByActivityEntQuery%3Atds_flgs.3%3Aott.AX9i6gf_fleGNzvu&__tn__=%2Cg
  warnings.warn(f"Facebook served mbasic/noscript content unexpectedly on {response.url}")```

**Comment by neon-ninja** [comment]
Probably nothing to worry about, so long as that image URL extraction worked

**Comment by roma-glushko** [comment]
@neon-ninja thank you for the replay!

Can't actually get it working. I pass `start_url` and `request_url_callback ` params to the `get_posts()` function:

```python
            for post_idx, post in enumerate(get_posts(
                    group=group_id,
                    cookies=cookie_path,
                    page_limit=None,  # try to get all pages and then decide where to stop
                    start_url=search_page_url, request_url_callback=save_search_page,
                    options={
                        'reactors': True,
                        'posts_per_page': 10,
                    }
            )):
                # ... lots of stuff
```

 However, the arguments don't seem to pass further to the place where they are actually used (facebook_scraper/page_iterators.py:48):

<img width="978" alt="Screenshot 2021-06-02 at 17 33 07" src="https://user-images.githubusercontent.com/9402690/120499724-f36fd480-c3c8-11eb-8f02-7f4e48ebd859.png">
<img width="1283" alt="Screenshot 2021-06-02 at 17 39 40" src="https://user-images.githubusercontent.com/9402690/120500491-8dd01800-c3c9-11eb-82ba-19361fe1a123.png">

So my `request_url_callback` is never called and I cannot save the next search page URL.

Has anyone experienced the same?

**Comment by roma-glushko** [comment]
Created a PR with a possible fix for the issue: https://github.com/kevinzg/facebook-scraper/pull/318

**Comment by Eevaariste** [comment]
is there a way to rotate accounts?

**Comment by neon-ninja** [comment]
Sure, just change your cookies file

**Comment by Eevaariste** [comment]
i mean is it effective has anyone tried it ? or the block is universal for the pc?

**Comment by neon-ninja** [comment]
Changing your cookies if you're IP banned probably won't help, but if your account is disabled or locked, it would. Those are raised as different exceptions, see https://github.com/kevinzg/facebook-scraper/blob/master/facebook_scraper/facebook_scraper.py#L280

**Comment by Eevaariste** [comment]
Thank you! i ll try combing proxy with user rotation and maybe some sleep time and i ll see how it goes.. but with the same start url when exception occurs will cookie rotation work ? or will it scrap from the start?

**Comment by neon-ninja** [comment]
It seems pagination URLs can be accessed with different cookies, or without cookies even

**Comment by dimitriskg7** [comment]
Could you please update the version, so I can get the fix for the request_url_callback?

**Comment by dimitriskourg** [comment]
@roma-glushko What do you think about #336 ?

**Comment by u3533791** [comment]
> 

Thank you for the snippet. But I got stuck with only the first post retrieved.
No error code, it just loads forever after the console prints the pagination url for the first post... 
Something wrong with my settings?

```
from facebook_scraper import *
import time

locale.setlocale(locale.LC_CTYPE,'chinese')
results = []
start_url = None
targetpage = '387603714763860'

def handle_pagination_url(url):
    global start_url
    start_url = url
    if results:
        print(f"{len(results)}: {results[-1]['time']}: {start_url}")

while True:
    try:
        for post in get_posts(targetpage, pages=None, start_url=start_url, options={'allow_extra_requests': False, 'posts_per_page': 200}, request_url_callback=handle_pagination_url):
            print(post["time"])
            results.append(post)
        print("All done")
        break
    except exceptions.TemporarilyBanned:
        print("Temporarily banned, sleeping for 10m")
        time.sleep(600)
```

Console:
```
2022-04-06 23:10:02
1: 2022-04-06 23:10:02: https://m.facebook.com/page_content_list_view/more/?page_id=387603714763860&start_cursor={"timeline_cursor":"AQHRgmXT4l8sYYNmhgNAQz5ZVlvflKdm9firaq923upFZRSaK3bgkiZjcsZXGZwMZsuHOuSwUT1xVm7D0g-NExjSaD3bgVe7nVyE64fR9YFB5Nul0ZRANVHVm4CS5FsSZ48t","timeline_section_cursor":null,"has_next_page":true}&num_to_fetch=200&surface_type=posts_tab
```
(stuck loading forever)

**Comment by neon-ninja** [comment]
Try pass cookies as per the readme
