### ISSUE TITLE
Scrapper won't working on production server? 

### ISSUE THREAD

**Issue by maorkavod** [kevinzg/facebook-scraper#322]
The scrapper working fine on my local machine. but on production server the scrapper return **zero** posts (I pass my cookies file).
On my localhost facebook-scrapper is workign great. On server dose not.

@neon-ninja 

i used the debug mode. I see a lot of erros like this for every post : 

DEBUG:facebook_scraper.extractors:Fetching https://m.facebook.com/groups/369537586455596/permalink/4001152336627418/
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /groups/369537586455596/permalink/4001152336627418/ HTTP/1.1" 200 None
WARNING:facebook_scraper.extractors:[None] Extract method extract_link didn't return anything
WARNING:facebook_scraper.extractors:[None] Exception while running extract_user_id: KeyError('content_owner_id_new')
WARNING:facebook_scraper.extractors:[None] Extract method extract_video didn't return anything
WARNING:facebook_scraper.extractors:[None] Extract method extract_video_thumbnail didn't return anything
WARNING:facebook_scraper.extractors:[None] Extract method extract_video_id didn't return anything
WARNING:facebook_scraper.extractors:[None] Extract method extract_video_meta didn't return anything
WARNING:facebook_scraper.extractors:[None] Extract method extract_factcheck didn't return anything
WARNING:facebook_scraper.extractors:[None] Extract method extract_share_information didn't return anything
ERROR:facebook_scraper.extractors:Error parsing data-ft JSON: JSONDecodeError("Expecting ',' delimiter: line 1 column 192 (char 191)")
DEBUG:facebook_scraper.extractors:9 total photos in gallery
DEBUG:facebook_scraper.extractors:Fetching 1054762397/posts/pcb.4000550376687614
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /1054762397/posts/pcb.4000550376687614 HTTP/1.1" 200 None
DEBUG:facebook_scraper.extractors:Fetching https://m.facebook.com/groups/369537586455596/permalink/4000550376687614/
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /groups/369537586455596/permalink/4000550376687614/ HTTP/1.1" 200 None
WARNING:facebook_scraper.extractors:[None] Exception while running extract_user_id: KeyError('content_owner_id_new')
WARNING:facebook_scraper.extractors:[None] Extract method extract_video didn't return anything
WARNING:facebook_scraper.extractors:[None] Extract method extract_video_thumbnail didn't return anything
WARNING:facebook_scraper.extractors:[None] Extract method extract_video_id didn't return anything
WARNING:facebook_scraper.extractors:[None] Extract method extract_video_meta didn't return anything
WARNING:facebook_scraper.extractors:[None] Extract method extract_factcheck didn't return anything
WARNING:facebook_scraper.extractors:[None] Extract method extract_share_information didn't return anything
ERROR:facebook_scraper.extractors:Error parsing data-ft JSON: JSONDecodeError("Expecting ',' delimiter: line 1 column 191 (char 190)")
DEBUG:facebook_scraper.extractors:6 total photos in gallery
DEBUG:facebook_scraper.extractors:Fetching 1054762397/posts/pcb.4000963129979672
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /1054762397/posts/pcb.4000963129979672 HTTP/1.1" 200 None
DEBUG:facebook_scraper.extractors:Fetching https://m.facebook.com/groups/369537586455596/permalink/4000963129979672/
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /groups/369537586455596/permalink/4000963129979672/ HTTP/1.1" 200 None
WARNING:facebook_scraper.extractors:[None] Extract method extract_link didn't return anything
WARNING:facebook_scraper.extractors:[None] Exception while running extract_user_id: KeyError('content_owner_id_new')
WARNING:facebook_scraper.extractors:[None] Extract method extract_video didn't return anything
WARNING:facebook_scraper.extractors:[None] Extract method extract_video_thumbnail didn't return anything
WARNING:facebook_scraper.extractors:[None] Extract method extract_video_id didn't return anything
WARNING:facebook_scraper.extractors:[None] Extract method extract_video_meta didn't return anything
WARNING:facebook_scraper.extractors:[None] Extract method extract_factcheck didn't return anything
WARNING:facebook_scraper.extractors:[None] Extract method extract_share_information didn't return anything
ERROR:facebook_scraper.extractors:Error parsing data-ft JSON: JSONDecodeError("Expecting ',' delimiter: line 1 column 199 (char 198)")
DEBUG:facebook_scraper.extractors:Fetching 1054762397/posts/pcb.4006985896044062

**Comment by neon-ninja** [comment]
Why not just do all your scraping on your local machine then?

**Comment by fashandatafields** [comment]
may be try proxies and try

**Comment by maorkavod** [comment]
@fashandatafields

Thank you,
Is there a sample with Facebook scraper & set proxy?
It hasn't worked for me so far..

**Comment by neon-ninja** [comment]
Sure, here's an example:
```python
set_proxy("http://146.196.99.122:63123")
```
