### ISSUE TITLE
About setting locale

### ISSUE THREAD

**Issue by cmhcheung** [kevinzg/facebook-scraper#327]
I got a warning as below
UserWarning: Locale detected as en_GB - for best results, set to en_US
  warnings.warn(f"Locale detected as {locale} - for best results, set to en_US")

I already added the following in my python code
locale.setlocale(locale.LC_ALL, 'en_US')

How to eliminate the above warning?

**Comment by neon-ninja** [comment]
This is related to cookies. You'd set the language on your account

**Comment by cmhcheung** [comment]
Thanks.  It is eliminated after setting the locale in Facebook.

**Comment by alvaroserrrano** [comment]
Hi, I am getting the results in the language of the country where I am making the request even after changing the language on the Facebook account. It says my locale is es_ES instead of en_US even after setting the English language in Facebook. What would be a workaround for this? Thanks

**Comment by neon-ninja** [comment]
Re-export your cookies after changing language
