### ISSUE TITLE
Error parsing data-ft JSON: JSONDecodeError

### ISSUE THREAD

**Issue by maorkavod** [kevinzg/facebook-scraper#329]
There is a problem with the scrapper. A specific error prevents me from scraping 90% of the posts from all groups.

`ERROR:facebook_scraper.extractors:Error parsing data-ft JSON: JSONDecodeError("Expecting ',' delimiter: line 1 column 192 (char 191)") `

**Comment by neon-ninja** [comment]
What group are you having this problem with?

**Comment by neon-ninja** [comment]
https://github.com/kevinzg/facebook-scraper/commit/caf89d711d187a6c33330efb6ef695dd45271cb4 should fix this specific problem around parsing video URLs btw
