### ISSUE TITLE
Capture posts from old pages

### ISSUE THREAD

**Issue by reichaves** [kevinzg/facebook-scraper#33]
Please, I did:

```
from facebook_scraper import get_posts

for post in get_posts('cezinhademadureira', pages=1):
    print(post['text'])
```

And for this page the return is empty. I noticed that it's an old page and hasn't been updated in a while. Is there a solution in these cases?

**Comment by kevinzg** [comment]
Going to https://facebook.com/cezinhademadureira asks me to log in. Try providing login credentials to the scraper.

**Comment by reichaves** [comment]
Thank you very much Kevin
I did not know that. So some FB pages can choose to only allow viewing if the user is logged in?
Can I resolve this if I am logged into the same section of the scraping?
