### ISSUE TITLE
Its not returning any post in public page?

### ISSUE THREAD

**Issue by fashandatafields** [kevinzg/facebook-scraper#330]
I have passed cookies and tried to get post from this page but not returned any post. I have enabled the log also. please check the log too
`https://m.facebook.com/112649746799207`
[issue.txt.zip](https://github.com/kevinzg/facebook-scraper/files/6616159/issue.txt.zip)

@neon-ninja please check

**Comment by neon-ninja** [comment]
Take a look at https://m.facebook.com/fdaemasr... this is a bug on Facebook's end

**Comment by fashandatafields** [comment]
@neon-ninja wat can we do for this

**Comment by neon-ninja** [comment]
Submit a bug report to Facebook?

**Comment by fashandatafields** [comment]
do we have a checker in the facebook-scraper just to assume when we set proxy does facebook can view the public forum or to get catch this exception` A login (cookies) is required to see this page`
Is it possible to achieve this

**Comment by neon-ninja** [comment]
set_proxy only checks that the proxy is working by making a request to ipinfo.io, and displaying the result in the debug log. When any request is made to Facebook, a few different conditions that can indicate a login is required are checked, and an exception is raised (see https://github.com/kevinzg/facebook-scraper/blob/master/facebook_scraper/facebook_scraper.py#L327). Depending on the context of how that request is made, that exception may stop execution (ie, when trying to iterate through pages), or it may be caught and logged (if it's a non-critical request, like a request to get full text or HQ images).

**Comment by neon-ninja** [comment]
This bug appears to have been fixed on the Facebook end
