### ISSUE TITLE
Set locale without cookies

### ISSUE THREAD

**Issue by dimitriskourg** [kevinzg/facebook-scraper#331]
Hi! I get the warning  ```UserWarning: Locale detected as el_GR - for best results, set to en_US
  warnings.warn(f"Locale detected as {locale} - for best results, set to en_US") ```

How could I set the locale to en_US without add cookies, since I want to scrape public pages without logging in?

**Comment by neon-ninja** [comment]
I don't think Facebook has any way of setting language without an account. Is this causing a problem for you? I think the scraper _should_ still mostly work with Greek Facebook. Alternatively you could use a VPN or proxy in an English speaking country.

**Comment by dimitriskourg** [comment]
Thanks for all your help! Most parts of the scraper still work with Greek Facebook, however it returns always likes = 0. Is there a possible way I could get the number of likes in every post without VPN or proxy?

**Comment by neon-ninja** [comment]
Sure, try this - https://github.com/kevinzg/facebook-scraper/commit/336621df75e86f682af353167c39b72a55fd2b34

**Comment by dimitriskourg** [comment]
Thanks for all! Everything works fine now
