### ISSUE TITLE
Wrong datetime format for last day with dot.number after seconds LIKE: 2021-06-14 14:22:19.455552

### ISSUE THREAD

**Issue by vitovt** [kevinzg/facebook-scraper#341]
When I parse using cookies I get post creation **time** in strange format 2021-06-14 14:22:19.455552
There is additional number after seconds per dot.

I is actual only for last 24h. After that - all is OK.

**Comment by neon-ninja** [comment]
That's milliseconds. It's because Facebook provides post timestamps in relative time - like "5 hours ago".

**Comment by neon-ninja** [comment]
This commit should make the scraper drop milliseconds - https://github.com/kevinzg/facebook-scraper/commit/ff687fbd1446338331efb06a763a3a372af62e2e

**Comment by vitovt** [comment]
Yes it works. Thankyou
