### ISSUE TITLE
FB inconsistent with more pages on groups?

### ISSUE THREAD

**Issue by TimNZ** [kevinzg/facebook-scraper#343]
I was only getting one page from a group and confirmed in the browser that FB doesn't return any more pages for it.
This is the POST request triggered from scroll to the bottom of the first page.

Any known hacks?

![image](https://user-images.githubusercontent.com/1051701/122113340-13e26900-ce76-11eb-988f-14718b174330.png)

**Comment by neon-ninja** [comment]
What group are you having this problem with?

**Comment by TimNZ** [comment]
Didn't specify it as it's private.
https://m.facebook.com/groups/494029924138675
Just looks like FB decides to return no more pages.

![image](https://user-images.githubusercontent.com/1051701/122115197-4ab97e80-ce78-11eb-821e-3fa8b8acef18.png)

**Comment by neon-ninja** [comment]
This looks like a bug in Facebook itself. I note https://www.facebook.com/groups/494029924138675 works fine, perhaps a selenium-based scraper, or something that uses the graphql endpoint would work better

**Comment by TimNZ** [comment]
FB bug is what I thought.  Hoping someone knew of a query string hack that magically fixes this scenario.
The issue is it's broken in a regular browser so another scraper won't help.

**Comment by neon-ninja** [comment]
It's only broken on the m.facebook.com domain, it's fine on www.facebook.com. So a scraper that relied on the latter would work fine.
