### ISSUE TITLE
Proxy checker

### ISSUE THREAD

**Issue by fashandatafields** [kevinzg/facebook-scraper#345]
`ip = self.get("http://ipinfo.io", headers={"Accept": "application/json"}).json()`

I recommend using this URL [proxy checker](http://lumtest.com/myip.json) than above one, coz it has a limitation but recommended one haven't a limitation 

`ip = self.get(“http://lumtest.com/myip.json”, headers={“Accept”: “application/json”}).json()` 
https://github.com/kevinzg/facebook-scraper/blob/master/facebook_scraper/facebook_scraper.py#L57

**Comment by neon-ninja** [comment]
Sounds good, please submit a pull request
