### ISSUE TITLE
Can we integrate these kind of proxies to the facebook_scraper

### ISSUE THREAD

**Issue by fashandatafields** [kevinzg/facebook-scraper#349]
https://brightdata.com/pricing/proxy-network

@neon-ninja  can u look this. It seems we cannot implement this to kevingz

**Comment by neon-ninja** [comment]
https://github.com/kevinzg/facebook-scraper/issues/337#issuecomment-860608259 worked fine, remember?

**Comment by vitovt** [comment]
If you run from CLI you can use:
HTTPS_PROXY="super-proxy.com:3388" bash -c "/usr/local/bin/facebook-scraper --filename filename.csv --pages 10 pagename"
