### ISSUE TITLE
Continue Reading not working

### ISSUE THREAD

**Issue by tomscag** [kevinzg/facebook-scraper#35]
When "Continue Reading" is displayed in a post, only a fraction of the text is returned (when "see more" is displayed it  works well).

**Comment by qwertygc** [comment]
Hello,
i have the same error.

**Comment by nubpro** [comment]
You could perhaps provide the link to the post?

**Comment by tomscag** [comment]
Hello,
I've just checked the problem has been solved! Thank you for your work

**Comment by Cubic-K** [comment]
Same problem

**Comment by Cubic-K** [comment]
How to solve that problem, I can’t read anymore on Facebook now

**Comment by aerial23** [comment]
I have same problem. How can i solve this?
