### ISSUE TITLE
All content from groups/private groups

### ISSUE THREAD

**Issue by Cheltone** [kevinzg/facebook-scraper#350]
Hello, excellent work! Do you know if it is possible to scrape content from a private group if you are a member? Also, are there thorough directions for the "cookies" issue anywhere on your github? Thanks!

**Comment by neon-ninja** [comment]
Yes. Yes, see the readme.

**Comment by Cheltone** [comment]
OK thanks! Can I access these groups through the CLI commands too? Also, is there a way to get the comment texts through the CLI command?

**Comment by neon-ninja** [comment]
You can access the groups through CLI, by passing the cookies argument. The CLI currently doesn't have an argument for comments but it would be very easy to add that in.

**Comment by neon-ninja** [comment]
This should do it - https://github.com/kevinzg/facebook-scraper/commit/9ce70d084ba3bc49238cb7d905bcb6f387f17ec0

**Comment by Cheltone** [comment]
I just tried it out and the argument was unrecognized. I apologize if these are simple mistakes. Learning... 

facebook-scraper --filename nintendo_page_posts.csv --pages 10 1708856692733861 --encoding utf-8 --9ce70d0

**Comment by neon-ninja** [comment]
That's a commit hash referring to a change made to this repository. You would need to pull the latest master branch, then use the --comments argument

**Comment by Cheltone** [comment]
OK I pulled the latest but it doesn't seem to be working still. I should be able to pip install --upgrade right? Thanks!

**Comment by neon-ninja** [comment]
`​pip install git+https://github.com/kevinzg/facebook-scraper.git` should do it

**Comment by Cheltone** [comment]
Alright! We are in business! Thanks for your time and expertise :)
