### ISSUE TITLE
connection to m.facebook.com timed out

### ISSUE THREAD

**Issue by Nevebe** [kevinzg/facebook-scraper#355]
use the case but failed,  @neon-ninja please check.

> from facebook_scraper import *
> 
> set_noscript(True)
> for post in get_posts("Nintendo", pages=3):
>     print(post["post_id"], post["time"])

requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='m.facebook.com', port=443): Max retries exceeded with url: /Nintendo/posts/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001DA98F0C280>, 'Connection to m.facebook.com timed out. (connect timeout=5)'))

**Comment by neon-ninja** [comment]
Increase the timeout with the timeout argument

**Comment by Nevebe** [comment]
> Increase the timeout with the timeout argument

ty, could it be caused by the proxy issues?

**Comment by neon-ninja** [comment]
Yes, proxies tend to add a bit of overhead. Might delay each request by a few seconds

**Comment by Nevebe** [comment]
it works, ty!
