### ISSUE TITLE
Generate cookies.txt

### ISSUE THREAD

**Issue by cmhc2021** [kevinzg/facebook-scraper#363]
Hi buddies, I used to generate cookies.txt in python before scraping as below:

s = requests.Session()
s.cookies = MozillaCookieJar("c:\\cookies.txt")
response = s.get('https://m.facebook.com')
response = s.post('https://m.facebook.com/login.php', data={
                            'email': email,
                            'pass': password
                        }, allow_redirects=False)
 if 'c_user' in response.cookies:
                    s.cookies.save()

But today this method does not work as Facebook seems to impose additional security as below:
Login Approval Needed
We noticed a login from a browser, device or location you don't usually use. We need to confirm it was you before you can get back on Facebook. 

Is there any way I can programmatically generate a valid cookies.txt?

**Comment by neon-ninja** [comment]
Have you tried the credentials/login method built into this library?

**Comment by cmhcheung** [comment]
I am able to login by passing the following parameters
credentials = [email, password]
I would like to clarify that if I pass the credentials, does it mean that there is no need for cookies.txt anymore? Do they serve the same purpose?

**Comment by neon-ninja** [comment]
effectively, yes. The act of logging in requires a minimum of two extra requests, but that likely won't add much delay.
