### ISSUE TITLE
Problems within the comment_time

### ISSUE THREAD

**Issue by Nevebe** [kevinzg/facebook-scraper#365]
Hi, 
when I print the comment_time, the month/day/hh/ss is based on the present time, but the year is right.  @neon-ninja please check.
code shows below:

>         if post.get("time") and post.get("post_id"):
>             if post["comments"] > 0 and post.get("comments_full"):
>                 p_id = post["post_id"]
>                 for comment in post["comments_full"]:
>                     if comment.get("comment_time"):
>                         print(comment['comment_url'], comment["comment_text"], comment["comment_time"])

result shows below:

> https://facebook.com/2071868283040513 j'ai adoré ta vidéo comme toute tes vidéo 2017-06-22 17:14:51.600965
> https://facebook.com/2068816940012314 Ça tourne mal ? 2017-06-22 17:14:51.604954
> https://facebook.com/2068879003339441 je t'adore! t'es trop marrant surtout sur cette vidéo :) 2017-06-22 17:14:52.881871

**Comment by neon-ninja** [comment]
Facebook doesn't show detailed timestamps for comments on m.facebook.com. See https://m.facebook.com/1602276179999728/photos/a.1670180436542635/2068815840012424/?comment_id=2071868283040513. Strings like "3 yrs", "4 yrs" is all we have to work with to determine the time.

**Comment by Nevebe** [comment]
Oh I see, ty!
