### ISSUE TITLE
Load cookie from variable instead of file

### ISSUE THREAD

**Issue by Prabesh01** [kevinzg/facebook-scraper#367]
How do I load cookie from variable instead of file?

Thing is I host my script on replit.com where I can't create any private repl/files unless I buy a plan. 
I can't just expose my cookie file to whoever views my repl.

So, I have to keep the cookie value in environment variable which are private by default in replit and load the cookie from the variable.

Thanks

**Comment by maorkavod** [comment]
Why won't you check for the env variable,  than If not exist read the cookie file and save the value as env variable for next iterations? 
I think this is the most simplest way..

**Comment by neon-ninja** [comment]
One way of doing this would to encode your cookies as a JSON string in this environment variable. For example, running this script:
```python
from facebook_scraper import *
import os
import json
cookies = json.loads(os.environ["COOKIES"])
set_cookies(cookies)
```

like so:
COOKIES='{"c_user": "REDACTED", "xs": "REDACTED"}' ./test.py

Seems to work fine

**Comment by Prabesh01** [comment]
Thanks you :)
