### ISSUE TITLE
How to check if a page is available?

### ISSUE THREAD

**Issue by reichaves** [kevinzg/facebook-scraper#37]
Please, I have a group of pages that I want to capture posts. However, I discovered on the way that some of them are already disabled or no longer available. Example: https://www.facebook.com/DanielFreitasDeputadoFederal

In such a situation is there a way to automatically check beforehand if the page is available? And return some warning message

Or is it better to do it manually first?

**Comment by neon-ninja** [comment]
I think just check if `get_posts` is empty and that should suffice
