### ISSUE TITLE
Can't get comments from some posts?

### ISSUE THREAD

**Issue by PeterStavrou** [kevinzg/facebook-scraper#375]
It seems that I cannot get comments from some posts even though they are identical to the ones I can get comments from.
There is no JSON data when this happens but there are comments on the post.
Example: https://bit.ly/2V45z6Z

```
'comments_full': [
    {
      'comment_id': None,
      'comment_url': 'https://facebook.com/',
      'commenter_id': None,
      'commenter_url': None,
      'commenter_name': '',
      'commenter_meta': None,
      'comment_text': '',
      'comment_time': None,
      'comment_image': None
    }
```

**Comment by neon-ninja** [comment]
Try use the latest master branch?

**Comment by PeterStavrou** [comment]
ah that did the trick...
Thank you!
