### ISSUE TITLE
comments_full is None or Empty

### ISSUE THREAD

**Issue by cocxtrash** [kevinzg/facebook-scraper#379]
### Input:
```python
import json
import logging

from facebook_scraper import get_posts, enable_logging

enable_logging(logging.DEBUG)
logging.basicConfig(filename="logs.txt", filemode='w', level=logging.DEBUG)

posts: list = []

for post in get_posts(group='1653646018033823', pages=1, cookies="cookies.json", timeout=30,
                      extra_info=True,
                      options={"comments": True,
                               "reactors": True, }):
    posts.append(post)
    json.dump(posts, open('posts.txt', 'w', encoding='utf-8'),
              indent=4, ensure_ascii=False, default=str, sort_keys=True)

    if len(posts) == 3:
        break

```
### Output Files:
[logs.txt](https://github.com/kevinzg/facebook-scraper/files/6758556/logs.txt)
[posts.txt](https://github.com/kevinzg/facebook-scraper/files/6758557/posts.txt)

---
_facebook-scraper-0.2.43_

**Comment by neon-ninja** [comment]
Try latest master

**Comment by cocxtrash** [comment]
> 
> 
> Try latest master

Thanks it Worked :)

**Comment by januarioccp** [comment]
I'm also having the same issue while scraping comments on public posts. I tried cookies, credentials, run in on macOS and Ubuntu, and I'm also using the latest master.

```python
import json
import logging

from facebook_scraper import get_posts, enable_logging

enable_logging(logging.DEBUG)
logging.basicConfig(filename="logs.txt", filemode='w', level=logging.DEBUG)

posts: list = []

for post in get_posts(post_urls=['https://www.facebook.com/ExpressNewspapers/posts/10157986087965814'], 
                      cookies="cookies.json", 
                      extra_info=True,
                      options={"comments": True, 
                               "progress": True }):
    posts.append(post)
    json.dump(posts, open('posts.txt', 'w', encoding='utf-8'),
              indent=4, ensure_ascii=False, default=str, sort_keys=True)

    if len(posts) == 3:
        break
```

[posts.txt](https://github.com/kevinzg/facebook-scraper/files/6772509/posts.txt)
[logs.txt](https://github.com/kevinzg/facebook-scraper/files/6772510/logs.txt)

**Comment by neon-ninja** [comment]
You're actually having a different issue that only occurs with video posts. It's caused by the /watch/ URL. See https://github.com/kevinzg/facebook-scraper/issues/309#issuecomment-852677793

**Comment by januarioccp** [comment]
Brilliant! It worked like a charm! Thanks!

**Comment by neon-ninja** [comment]
https://github.com/kevinzg/facebook-scraper/commit/a6af0366ba8b5430efa9be3275791ebea2df19e2 should fix this problem
