### ISSUE TITLE
Only limited number of posts could be scraped when scraping groups

### ISSUE THREAD

**Issue by kcshum** [kevinzg/facebook-scraper#38]
```
from facebook_scraper import get_posts

for post in get_posts(group='234176430922917', credentials=('xxxx', 'xxxx')):
    print(post)
```
When executing the above code, only about 20 posts are collected while the group has hundreds of new posts a day.
Moreover, the time of all posts is **none**. Is it normal?

Thank you very much.

**Comment by kevinzg** [comment]
No, there is still work to do on the scraping for groups.

**Comment by BNkosi** [comment]
Very eager for a fix for this. My group has nearly hundreds of new posts per day. working around it by executing my script every 15 minutes to add new tweets to my database. I'f i could run it once per day that would be great

**Comment by ebtrader** [comment]
great script - works awesome on pages!!!

i had the same problem on groups and would love to move past the limit of about 22 posts.  

looking forward to the fix on this.

**Comment by salamtamp** [comment]
I had the same problem and I fixed it on #53 . Waiting for the review :)

**Comment by kevinzg** [comment]
Thanks @salamtamp!

I have merged your code and released the new version.

**Comment by kanishkaRandunu** [comment]
Is this resolved. I still can only scrape around 20 post from a group. any support on this would be much appreciated.
