### ISSUE TITLE
Author Responses?

### ISSUE THREAD

**Issue by PeterStavrou** [kevinzg/facebook-scraper#381]
I am using the latest master branch and was wondering if it's possible to also get Author responses in comments?
At the moment I see that they are not included so if there are multiple comments on a reply, the Author's are missing from the JSON.

Also, where is the time scraped from?
The time scraped cannot be found within the page source code.

**Comment by neon-ninja** [comment]
Do you have a sample post where this occurs?

The post time is calculated based on the available information - so if fb says "2 hours ago", the minutes and seconds may be inaccurate

**Comment by PeterStavrou** [comment]
Sample Post: [(https://bit.ly/3dLvDKn)]

In terms of time, so it's calculated based on TimeNow - 3Weeks for example rather than using the time which is shown when the mouse hovers over 3w?

**Comment by neon-ninja** [comment]
Yes. The mouse hover feature only exists on desktop. This scraper uses the mobile version of Facebook (https://m.facebook.com/story.php?story_fbid=4776018582413826&id=165961726752891)

**Comment by neon-ninja** [comment]
https://github.com/kevinzg/facebook-scraper/commit/850ce7aad7932ac9121901af61b1b0b20a17f3ad should make it possible to extract inline replies

**Comment by PeterStavrou** [comment]
Perfect! This has been solved :)
Thank you!
