### ISSUE TITLE
Anyway to scrape the reactions instead of the total like counts?

### ISSUE THREAD

**Issue by cyriltw** [kevinzg/facebook-scraper#39]
I noticed it pulls the total likes, is there a way to get the reactions specifically.

**Comment by kevinzg** [comment]
The scraper uses the mobile page of Facebook and it doesn't have reactions as far as I know.
To extract the reactions we would have to look where they come from on the regular Facebook site.

**Comment by neon-ninja** [comment]
Should be solved as of https://github.com/kevinzg/facebook-scraper/pull/194
