### ISSUE TITLE
Does it work with another languages? 

### ISSUE THREAD

**Issue by etomoscow** [kevinzg/facebook-scraper#399]
Trying to parse posts and comments for the Russian segment of Facebook. When I try to run the code below, I get `HTTPError: 404 Client Error: Not Found for url: https://m.facebook.com/%D0%B6%D0%B0%D1%80%D0%B0/`

```python
for post in get_posts('жара', pages=1, options={'comments' : True, 'progress' : True, 'allow_extra_requests' : True}):
    print(post['text'][:50])
```

**Comment by neon-ninja** [comment]
That URL doesn't work for me either. Is this a page or a group? There's several pages and groups on Facebook called жара - which one did you mean? You need to pass the unique fragment from the URL

**Comment by etomoscow** [comment]
> That URL doesn't work for me either. Is this a page or a group? There's several pages and groups on Facebook called жара - which one did you mean? You need to pass the unique fragment from the URL

That is an URL generated by my query in Russian.

**Comment by neon-ninja** [comment]
What query?

**Comment by etomoscow** [comment]
> What query? Do you mean https://www.facebook.com/heat.public? In that case, pass "heat.public"

No, I mean I want to search for posts with my query. For example, I chose my search query as "жара" which is "heat" in Russian. I expected to get posts and comments as a result of search via this query.

**Comment by neon-ninja** [comment]
get_posts is intended for collecting posts from a given page or group. It is not a search function. The scraper does not currently support search
