### ISSUE TITLE
Scraper only retrieving 2 posts

### ISSUE THREAD

**Issue by kevinzg** [kevinzg/facebook-scraper#4]
It seems Facebook changed its code and the scraper is only getting 2 posts now.

I'll try to fix this over the weekend but if anyone has looked into it please share your findings here. PRs with a fix are also welcomed.

**Comment by simonsterj** [comment]
Hey @kevinzg thanks for the work. Question: expecting facebook UI changes to be a regular thing, what are your plans for future maintenance?

**Comment by kevinzg** [comment]
Hi @simonsterj, thanks for your interest.

Ideally we would have unit tests and something running them every once in a while, notifying me and the users when the scraper is failing.

I didn't expect much change from the Facebook side, especially since we are using their m.facebook interface, but as this has shown it can happen.

Personally, I will maintain this project while it is useful to me, can't promise more than that.
