### ISSUE TITLE
Login only once

### ISSUE THREAD

**Issue by grubeli** [kevinzg/facebook-scraper#400]
I'm using `get_posts(page_name, page_limit=3, credentials=(...)` every time I'm accessing to a page, my code is running a long time, is it possible to provide credentials only once, login only once and not every time I'm parsing a page, I guess it takes a time to login before every get_posts call

**Comment by grubeli** [comment]
I guess something like `set_credentials`  would work

**Comment by neon-ninja** [comment]
You could use:

```python
from facebook_scraper import _scraper
_scraper.login((username, password))
```
