### ISSUE TITLE
About temporarily block

### ISSUE THREAD

**Issue by cmhc2021** [kevinzg/facebook-scraper#409]
I don't know why recently I encountered a lot of temporary ban even with cookies.txt, and not sure if security has been heighted.  I would like to ask, sometimes, when I'm scraping, say, AndyMurray, I can see temporarily blocked in the log but I'm still able to fetch the comments.  Is it usual?  Why is it in the log? I will catch exceptions.TemporarilyBanned in my program but in such case, it seems my program will not run into the exception statement.

2021-07-27 11:34:21,113
Fetching https://m.facebook.com/comment/replies/?ctoken=10157115967571324_10157118433851324&count=1&curr&pc=1&isinline&initcomp&ft_ent_identifier=10157115967571324&eav=AfZ-Bkw7aFm3LhuKR5WEE-Zzf-uMqanA3GO5BYH3XUu4ItOx9WtNo4htTWNmUmVVcv8&av=100070379280090&gfid=AQC-\-\EPBMTYVrx5qz1c&refid=52&__tn__=R
2021-07-27 11:34:21,363
Content not found
2021-07-27 11:34:21,379
Fetching https://m.facebook.com/comment/replies/?ctoken=10157115967571324_10157119529536324&count=4&curr&pc=1&isinline&initcomp&ft_ent_identifier=10157115967571324&eav=AfaQOmbiQgTar3Ebgu3MojjgzoNw8eEL9KqTIY6rLzpQ2PAfQRfohx4C_ixoPXrNvA8&av=100070379280090&gfid=AQDHfGk86CfbHpgjGvA&refid=52&__tn__=R
2021-07-27 11:34:21,628
You¡¦re Temporarily Blocked
Scraped post: 10157115967571324
2021-07-27 11:34:21,628
Found new comment 10157116011651324
2021-07-27 11:34:21,644
...

**Comment by neon-ninja** [comment]
It's still possible to get temp banned when logged in. In some cases, the scraper makes a request, which is rejected due to temp ban (for example, getting replies to a comment). But the rest of the data can still be returned despite this, so the exception is caught and handled within the extract function.

**Comment by cmhc2021** [comment]
I can see in the log file that when the program fetches replies to comments, it will log "You're temporarily blocked".  However, even when using the latest code with except exceptions.TemporarilyBanned raised in extract_posts, the exception seems not propagated to my main program so my program continues to scrape and not pause.  Can "except exceptions.TemporarilyBanned as ex" in the main program catches such exception?

**Comment by cmhc2021** [comment]
I also wonder if we are making an independent request for each reply to comment? Should we introduce some time delay between the requests to reduce the chance of blocking?

**Comment by neon-ninja** [comment]
Sure, https://github.com/kevinzg/facebook-scraper/commit/17e8332a08cf544b64fc15effccf1ab19a011abd should make the scraper raise TemporarilyBanned if it occurs while collecting replies, or reactions to comments. Yes, each set of replies or reactions to a comment involves another request. Could do - perhaps this function could be converted into a generator that yields comments, similar to how get_posts is a generator that yields posts. What do you think?

**Comment by cmhc2021** [comment]
I only feel strange that when I am temporarily blocked, I cannot request replies and I can request story.php, so what make the difference? What I observed is that I can see that too many requests to replies to comments can get temporarily blocked easily, and it is nearly a precursor to the whole program blocked.  I'm not an expert in Python and I still don't know much about generator, but if that may improve the situation, I think it is worth a try and we can test it.

**Comment by neon-ninja** [comment]
I think it's possible that Facebook have different quotas for different request types, and some requests are "more suspicious" than others. So it seems plausible that you might be banned from getting more replies but still able to get posts.

**Comment by neon-ninja** [comment]
https://github.com/kevinzg/facebook-scraper/commit/3026d39a5f916cdaf7c3a102460cb170fdccd9f5 should make it possible to get the scraper to give you a generator of comments, if you set the comments option to "generator". This should give you more control of the rate of comment extraction. Sample usage:

```python
set_cookies("cookies.txt")

post = next(
    get_posts(
        post_urls=[2257188721032235],
        options={"comments": "generator"},
    )
)
comments = post["comments_full"]
for comment in comments:
    print(comment)
    time.sleep(5)
```

**Comment by cmhc2021** [comment]
Thanks for your great work.  Preliminary testing: when inserting a 5s break between each comment, the program takes a very long time so I quit the program after around 4 hours.  When inserting 1-2s break between each comment and I additionally insert 4-6s break if the last comment has replies, the program is still blocked by Facebook when scraping around 10 posts (around 1 hour).  
I would like to try one thing: I would like to decouple the scraping of comments and replies.  In the first stage, I scraped the comments and only URL of the replies.  This can be completed within several minutes with no block.  In the second stage, I would like to loop through the results which have reply URLs and insert, say, 20s break between each request.  However, I do not know how to revise the program because the functions are so intertwined.   Can you help write a function so that I can scrape the replies only by passing the URL? Do you think it is a feasible approach?

**Comment by neon-ninja** [comment]
Sure, https://github.com/kevinzg/facebook-scraper/commit/5143311f1e00b15cc96495649e7bac470095621f should make the replies into a generator too, if `options={"comments": "generator"}` is set. This should allow you to consume replies when ready, at the rate you prefer.

**Comment by exnerfelix** [comment]
I just started playing around with this module today and have already received the "TemporaryBanned" exception. I was wondering if there is a best practice to avoid this exception? For example, is it more likely to get banned with credentials or cookies? Or what would be a recommended number of requests per hour? Thanks in advance!

**Comment by neon-ninja** [comment]
Best practice is to reduce your requests per second ;). Credentials vs cookies should be functionally the same. Try to stay under one request per second. What were you doing? Some requests (getting friend lists for example) are more sensitive to temp bans than others.

**Comment by cmhc2021** [comment]
From my experience, use cookies instead of credentials.  Starting from July, I experienced account lock (not just temporary ban) if login to test the programs too many times.

**Comment by exnerfelix** [comment]
Yes, I figured the requests per second should be low, but in my run I only ran it once every 5 minutes, which is why I'm surprised I was already temporarily blocked. I did use credentials for it though.

This is what I'm doing:
```python
for post in get_posts(page_name, pages=5, options={"comments": True, "posts_per_page": 25}, credentials=("username", "password")):
     # save each post in a dict

     for comment in post["comments_full"]:
          # save each comment in a dict with post as parent

# ...
# analyse data in DataFrame
```

Basically, I only need one request using `get_posts()` per minute for analysing public pages.

**Comment by neon-ninja** [comment]
How many comments and replies does this page usually attract?

**Comment by exnerfelix** [comment]
I was testing on [Clash of Clans](https://www.facebook.com/ClashofClans), so quite a bit of comments.

**Comment by cmhc2021** [comment]
I get temporarily blocked even though sleeping for 20-30s after each reply, after running for around 30 minutes.  It seems it is very difficult to scrape the replies.  Some questions: 
1. Can the scraped comments include a field which is a URL to the replies.  Even though I get blocked, I can still write the URL to an Excel for future reference.
2. In the extract_comments_full function, I often get the exception local variable 'more_url' referenced before assignment, is it required to add more_url = None?
3. I'm still using "for post in get_posts(...)".  How to loop to the next post if I use the following? I find I'm always scraping the same post using the following.  

while True:
  post = next(
      get_posts(
          federer,
          options={"comments": "generator"},
      )
  )

**Comment by cmhc2021** [comment]
Some more testing indicated that it is necessary to introduce 3-5s delay after each comment and reply, and program can continue to run for around 2 hours.  Even though blocking is caused by scraping replies, it is not enough only adding delay after each reply.  It is necessary to add delay after each comment as well, and 1-2s delay from my experience is insufficient.  I will see if blocking occurs tomorrow using the current setting.

**Comment by neon-ninja** [comment]
@exnerfelix so, with ClashOfClans, 5 pages, 25 posts per page, you're looking at 101 posts and ~69,494 comments. Comments only come in pages of 30, so that's ~2316 requests to get all the comments. Some comments have replies - let's assume roughly 10% have replies. So another 231 requests to get all the replies.

Requests:
5 requests to get the pages
101 requests to click each post in turn
2316 requests to get all comments
231 requests to get all replies
Total: 5+101+2316+231 = 2653. By default, all of these requests are made as fast as possible. At this scale you should probably use the recently added generator functionality and add some `time.sleep` code.

**Comment by cmhc2021** [comment]
Using 3-5s delay after each comment and reply, I can scrape 37 posts and 4442 comments in around 6 hours without blocking.  If without replies, I do not need to introduce the delay and the scraping takes less than 5 minutes.  So, it seems a compromise here - whether the replies are worth the extra scraping hours.

**Comment by neon-ninja** [comment]
@cmhc2021 

1. Unfortunately, it seems reply URLs are account specific in some way. So reply URLs scraped probably wouldn't be viewable or usable.
2. https://github.com/kevinzg/facebook-scraper/commit/35912dace1385b65008aeea6006686074a2b51db should fix this
3. Try store the result of `get_posts` in a variable, then iterate through it using `next`. Or just iterate through `get_posts` directly.

**Comment by vitovt** [comment]
@neon-ninja , how to apply additional delay between requests, when I parse page from cli ?

I use command like that:
` facebook-scraper --filename nintendo_page_posts.csv --pages 5000 --cookies my_cookies.json nintendo
`
is there any new time.sleep CLI option ?

**Comment by neon-ninja** [comment]
No. You would need to write a Python script for that level of customisation

**Comment by neon-ninja** [comment]
https://github.com/kevinzg/facebook-scraper/commit/c61f3487612de418bf81b69e8b5cc981eecb4e0f adds a new parameter called "sleep". Sample usage: `facebook_scraper Nintendo -p 1 -s 1`

**Comment by chwba** [comment]
Im experiencing heavy ratelimits here as well while the account still seems to be perfectly fine if being used in the browser - Using cookies to login and am already getting locked out at only doing get_group_info()

**Comment by vitovt** [comment]
> [c61f348](https://github.com/kevinzg/facebook-scraper/commit/c61f3487612de418bf81b69e8b5cc981eecb4e0f) adds a new parameter called "sleep". Sample usage: `facebook_scraper Nintendo -p 1 -s 1`

There is an error when I try to use "sleep" option.

```
/usr/local/lib/python3.8/dist-packages/facebook_scraper/__init__.py:285: UserWarning: The sleep parameter has been removed, it won't have any effect.
  get_posts(account=account, group=group, remove_source=not bool(dump_location), **kwargs), kwargs.get("sleep", 0)

```

I think it conflicts with this commit ?
https://github.com/kevinzg/facebook-scraper/commit/a806a9741f28740fff102dcdae7564820137997a#diff-5293390647bfe90c64c2c6ddec0256adf4cff3b68824a5007b55cbb5671cef65

**Comment by neon-ninja** [comment]
Disregard that warning, the sleep is handled outside of get_posts

**Comment by milesgratz** [comment]
@chwba  - you're impersonating a legitimate Facebook human user on a cell phone with this Python module. The more irregular your behavior, the easier it is to determine you're a bot. "Viewing" all comments of 100 posts in ~10 minutes isn't realistic/normal as a human. In my testing, I've been temp banned for 24-48+ hours before with repeated bot-like behavior, and that will increase your chance of being temp-banned again from the same source IP or authenticated profile. Worse case scenario - your account will be temporarily locked or permanently closed. 

Few things you can try:
- Rotate cookies of different accounts
- Use IP addresses that have extremely high FB traffic (_e.g., Starbucks/University WiFi, etc._)
- Use clean IP addresses that you haven't scraped with before (_e.g., build a proxy server or OpenVPN server in Azure/AWS/GCP/etc._) 
- Generate your cookies from a clean IP using a browser that **matches** the User Agent in the fb-scraper tool ``` "User-Agent": "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Mobile Safari/537.36"```

Similar to washing your hands - it's important not to cross-contaminate. If ```ProfileA``` logged in from home IP address 1.1.1.1 and was account locked / temp banned for bot-like behavior, then logging in with ```ProfileB``` from home IP address 1.1.1.1 will increase your chances of a ban. The more FB traffic from that source IP (_e.g., public WiFis_), the more likely that you can use ```ProfileA``` and ```ProfileB``` from the same source IP without that being obviously correlated. It's worth mentioning that you are trying to trick some of the most sophisticated bot moderation engineering in the world. 

My $0.02.

**Comment by chwba** [comment]
@milesgratz thank you for the thorough writeup. Of course I understand how difficult it is to create a request-base app, that spoofs all this and gets the desired information - I just wanted to make sure I am not doing anything wrong regarding lib usage. - For my usecase I am scraping a lot of invite only private groups, so I will be forced to create a scraper that uses a browser automation.
