### ISSUE TITLE
Changed algorithm?

### ISSUE THREAD

**Issue by manfye** [kevinzg/facebook-scraper#41]
It happened since yesterday, I can't extract text from facebook page anymore

**Comment by PragmaticCoder** [comment]
same here, what's going on?

**Comment by manfye** [comment]
> same here, what's going on?

over scrap until facebook changed algorithm? the script itself doesn't return any text at all except link now

**Comment by PragmaticCoder** [comment]
Seems it's automatically fixed now...weird! lol, I guess we can close this issue now?

**Comment by manfye** [comment]
yeah, seem like auto fix on the server side, topic will be close, thank everyone
