### ISSUE TITLE
change post date-time timezone

### ISSUE THREAD

**Issue by Prabesh01** [kevinzg/facebook-scraper#416]
Lame question but how do I change the timezone used to give post's timestamp by post["time"]?

If I used as it is, the post time shows tomorrow's date lol

**Comment by kevinzg** [comment]
You can do
```python
import pytz
post['time'] = post['time'].replace(tzinfo=pytz.utc).astimezone(pytz.timezone('America/Lima'))
```
for example.

But I'm not completely sure if all the dates the scraper extract are in UTC, so you might want to double check that.

**Comment by neon-ninja** [comment]
The timestamp is local time, based on the timezone of your system. So, check the timezone set on your system.

**Comment by Prabesh01** [comment]
Thank you :)

**Comment by TowardMyth** [comment]
@neon-ninja Sorry to reopen a closed issue. When pulling posts, is there any way for Facebook Scraper to get the post timestamp's timezone when scraping FB's site?

Issue: I'm assuming that the facebook scraper's timestamps are pulled directly from the FB post, and the timestamps on the FB post are based on the user's IP address. If this is true, then using proxies would mean that the timestamps may not match your system's timezone.

**Comment by neon-ninja** [comment]
@TowardMyth depending on how you're scraping, you might get the post time in a slightly different way. Unauthenticated requests can actually receive a UNIX timestamp. In that case, a debug log message "Got exact timestamp from publish_time" would be printed. See https://github.com/kevinzg/facebook-scraper/issues/273 for example. The UNIX timestamp is defined as the number of seconds since 00:00:00 UTC on 1 January 1970. So it is the same regardless of timezone. The timestamp served by https://m.facebook.com/story.php?story_fbid=306426417518211&id=100044525645708&_rdr is 1619377200, which equates to Sun Apr 25 2021 19:00:00 GMT+0000.

**Comment by TowardMyth** [comment]
@neon-ninja Do authenticated requests also receive a unix timestamp? If not, does it at least receive a timezone-aware datetime from FB (or just a naive non-timezone aware one)?

**Comment by neon-ninja** [comment]
Sometimes. I tested by adding a field to indicate whether a timestamp was exact or not, and the following code:

```python
for post in get_posts("Nintendo", cookies="cookies.txt", options={"allow_extra_requests": False}):
    print(post["post_id"], post["time"], post.get("time_exact"))
```
And these were the results (GMT+12):
```python
4377850938965992 2021-08-07 10:09:16 True
4377380082346411 2021-08-07 06:12:37 True
4377121662372253 2021-08-07 04:23:11 True
4371727619578324 2021-08-05 09:33:45 True
4365624383521981 2021-08-03 08:09:04 True
4365050470246039 2021-08-03 04:00:19 True
4329977513753335 2021-07-21 15:51:00 None
4314796888604731 2021-07-16 10:00:00 None
4314503055300781 2021-07-16 07:54:00 None
4311927432225010 2021-07-15 11:00:00 None
4306850432732710 2021-07-15 05:00:05 True
4294380853979668 2021-07-10 04:37:24 True
4291314330952987 2021-07-09 04:27:44 True
4290937374324016 2021-07-09 02:02:31 True
4288189624598791 2021-07-08 03:30:03 True
4284852408265846 2021-07-07 01:09:41 True
4279695485448205 2021-07-05 05:00:01 True
4274331009317986 2021-07-03 10:00:03 True
4273772932707127 2021-07-02 08:34:00 None
4270449279706159 2021-07-01 06:08:00 None
4268327196585034 2021-06-30 11:30:00 None
4268132489937838 2021-06-30 10:03:00 None
4253713764713044 2021-06-25 09:11:00 None
4244168652334222 2021-06-22 04:01:00 None
4239326416151779 2021-06-20 09:00:00 None
4230186287065792 2021-06-17 01:20:00 None
4226613690756385 2021-06-15 18:00:00 None
4226242920793462 2021-06-15 14:25:00 None
4225498680867886 2021-06-15 08:30:00 None
4222851827799238 2021-06-14 09:09:00 None
4217919734959114 2021-06-13 09:37:33 True
4217774244973663 2021-06-13 08:17:58 True
4214518608632560 2021-06-12 05:11:49 True
4214033132014441 2021-06-12 02:00:01 True
4194934713924283 2021-06-04 17:33:00 None
4193752747375813 2021-06-04 08:11:00 None
4191173794300375 2021-06-03 11:00:00 None
4188174317933656 2021-06-02 12:01:00 None
```

In the absence of a UNIX timestamp, the scraper tries to make a guess by parsing text similar to the examples given in https://github.com/kevinzg/facebook-scraper/blob/master/tests/test_parse_date.py. Note the lack of seconds in that case.

**Comment by TowardMyth** [comment]
@neon-ninja thanks for helping to debug. I've spent the past few hours playing around with this too, and like you, I found that sometimes, FB will return a unix timestamp whereas other times, it won't. 

1. Is there any way to force the scraper to: for every post, it must get a unix timestamp, otherwise, retry pulling this post, until it gets a unix timestamp.

2. Do you have any further insight around when unix timestamps will be returned by the scraper, and when they won't? From my experimentation, it seems like this is random.

**Comment by neon-ninja** [comment]
In my test above, increasing the posts_per_page improved the chance of getting unix timestamps. Do you not get the same? Which page/profile/group doesn't serve unix timestamps for you?

**Comment by neon-ninja** [comment]
time_exact isn't part of the library, it was a one-off modification I did locally to test with. If you're getting seconds, you're getting UNIX timestamps.

**Comment by TowardMyth** [comment]
Edit to my above comment: I am getting an error running the code I pasted above. Not sure if related?

```
sys:1: UserWarning: A low page limit (<=2) might return no results, try increasing the limit
4388957874521965 2021-08-10 09:00:01 None
4377850938965992 2021-08-06 18:09:16 None
/home/sack/.local/lib/python3.8/site-packages/facebook_scraper/facebook_scraper.py:440: UserWarning: Facebook served mbasic/noscript content unexpectedly on https://m.facebook.com/page_content_list_view/more/?page_id=119240841493711&start_cursor=%7B%22timeline_cursor%22:%22AQHRnfQjPoQy0di1sKI1zb49Fl2ip0D6sejyMvw4tMHgKUbDTIojIHkctHtInzTppBj46e3Sf0miBLIpc0p3oS368acKad9gdeTyj8r8jYioN0czrqwnrJ7zQXKR8T8LfMrW%22,%22timeline_section_cursor%22:null,%22has_next_page%22:true%7D&num_to_fetch=10&surface_type=posts_tab
  warnings.warn(
4377380082346411 2021-08-06 14:12:37 None
4377121662372253 2021-08-06 12:23:11 None
4371727619578324 2021-08-04 17:33:45 None
4365624383521981 2021-08-02 16:09:04 None
4365050470246039 2021-08-02 12:00:19 None
4329977513753335 2021-07-21 18:51:17 None
4314796888604731 2021-07-16 13:00:02 None
4314503055300781 2021-07-16 10:54:30 None
4311927432225010 2021-07-15 14:00:03 None
4306850432732710 2021-07-14 13:00:05 None
```

**Comment by neon-ninja** [comment]
That's just a warning, not an error. Probably safe to ignore.

**Comment by TowardMyth** [comment]
Thanks. 

```post["time"]``` returns a human-readable timestamp. Is there a way to get the actual unix timestamp (i.e. ```1628651893```) so I can manipulate it easier?

**Comment by neon-ninja** [comment]
Sure, https://github.com/kevinzg/facebook-scraper/commit/d4be42923cc6b51474caee55eae7cb3433add36c should do it

**Comment by TowardMyth** [comment]
Many many many thanks! One last question if you don't mind (I'm still a beginner): is this change automatically merged into pip library (i.e. I can just do ```pip install facebook-scraper --upgrade``` to get it)?

**Comment by neon-ninja** [comment]
No. You'd need to install it from github. Like so: `pip install git+https://github.com/kevinzg/facebook-scraper.git`

**Comment by TowardMyth** [comment]
Got it to work with your ```pip install git``` command. Thank you!

**Comment by TowardMyth** [comment]
Will ```post["timestamp"]``` return anything if the scraper could not find a unix timestamp? As well, is there some way to easily check whether a unix timestamp was returned for a post?

**Comment by neon-ninja** [comment]
No, it would be `None` in that case. You can check if it is `None`.

**Comment by TowardMyth** [comment]
One more q: is there any difference in what is returned if you are authenticated vs non-authenticated? I know that if you are non-authenticated, you get the unix timestamps, but if authenticated, then less likely to get unix timestamps. If I only scrape without authentication going forward, is there any content/values/etc I would miss?

**Comment by neon-ninja** [comment]
You're more likely to run into a LoginRequired exception if you scrape unauthenticated

**Comment by TowardMyth** [comment]
If I use authenticated: is there any chance that any personal data related to the authenticated cookie/FB user will be printed onto some output (ex: maybe the userid of that FB user will be in the ```posts``` array somewhere?)

**Comment by neon-ninja** [comment]
Probably not
