### ISSUE TITLE
Scrape all images per post

### ISSUE THREAD

**Issue by smazeri** [kevinzg/facebook-scraper#42]
When using get_posts only the first image url gets scraped. Is there a way to get all of them? 
Thank you

**Comment by jermp** [comment]
I would like the same.
Can you provide an update on this, please?

**Comment by neon-ninja** [comment]
Should be fixed as of https://github.com/kevinzg/facebook-scraper/commit/7f2305efe67c43b62accd4dfe177e64abd92051e
