### ISSUE TITLE
Some exceptions received from the script

### ISSUE THREAD

**Issue by fashandatafields** [kevinzg/facebook-scraper#427]
@neon-ninja i received some exception from the scraper script please check

when scraping this forum `478579972679012`
`('Connection broken: IncompleteRead(1494 bytes read, 8746 more expected)', IncompleteRead(1494 bytes read, 8746 more expected))`

when scraping this forum `153682461447815`
`HTTPSConnectionPool(host='m.facebook.com', port=443): Read timed out.`

when scraping this forum `154687731307896`
`Document is empty`

when scraping this forum `166424440075412`
`'[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2607)'`

when scraping this forum `109505710466109`
`("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))`

**Comment by neon-ninja** [comment]
These are likely caused by your proxy, and not the fault of the library

**Comment by fashandatafields** [comment]
Ah i C, got it
