### ISSUE TITLE
Get all users tagged in target post

### ISSUE THREAD

**Issue by potterthecop** [kevinzg/facebook-scraper#431]
Hello!
Is it possible to get all the profile ID's for all users that are tagged in target post?
If so, how can i modify the code?
Thanks! :)

**Comment by potterthecop** [comment]
Up :)

**Comment by neon-ninja** [comment]
Hi, https://github.com/kevinzg/facebook-scraper/commit/d2a8d6ec6271386d5c8af8bdd64656f493051023 should do it

**Comment by potterthecop** [comment]
Thanks for the effort, @neon-ninja 
But still it's not getting tagged users.

For example, i want to get all the users tagged in this public post:
https://www.facebook.com/permalink.php?story_fbid=1515967415419085&id=100010175238222


My code is:

import datetime
import pandas as pd
from facebook_scraper import get_posts

lista_profil = []
for post in get_posts(post_urls=["100010175238222"], cookies=r'C:\Users\.....\cookies_IM.txt', options={'comments':True, 'reactors':True}):
    lista_profil.append(post)
pd.DataFrame(lista_profil).to_csv(r"C:\Users\.....\teste.csv", index=False)


I've updated your code but i don't know why i'm not getting all the users.

Thanks in advance!

**Comment by neon-ninja** [comment]
I see - try https://github.com/kevinzg/facebook-scraper/commit/d77824db2e2e26ea0042da28178cee8c8ec57734

**Comment by potterthecop** [comment]
Works biutiful, thaks!!! :)
