### ISSUE TITLE
Undefine variable in extractor

### ISSUE THREAD

**Issue by fashandatafields** [kevinzg/facebook-scraper#434]
@neon-ninja, there is an undefined variable in extractor.py

https://github.com/kevinzg/facebook-scraper/blob/master/facebook_scraper/extractors.py#L926

**Comment by neon-ninja** [comment]
Easily fixed - https://github.com/kevinzg/facebook-scraper/commit/043d40c759d68accc4aa5bc07f91013db3de3df7
