### ISSUE TITLE
facebook_scraper.exceptions.InvalidCookies: Cookies are not valid

### ISSUE THREAD

**Issue by ehdgurdkf** [kevinzg/facebook-scraper#435]
hello, i use this project with my cookie by editthiscookie tool.

I wonder how to avoid temporary ban and InvalidCookies Error.

In my case, i want to use cookie pool to rotating. But it raised Cookies are not valid Error.

I think, several cookies are used by session, so if i closed browser, cookie is not valid value.

Is it right? or another error?

If my think is right, how to use cookie_pool? 

If you can answer those questions, it would be vary helpful to make my decision.

Thank you.

**Comment by neon-ninja** [comment]
At a minimum, you need to include the xs cookie and the c_user cookie. Check your cookies file includes these cookies

**Comment by ehdgurdkf** [comment]
@neon-ninja yes, it include the xs cookie and c_user cookie. And it is extracted in few hours ago.

cookie is that, 

[
{
    "domain": ".facebook.com",
    "expirationDate": 1636345715,
    "hostOnly": false,
    "httpOnly": false,
    "name": "_fbp",
    "path": "/",
    "sameSite": "lax",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "fb.1.1624233644009.1288403213",
    "id": 1
},
{
    "domain": ".facebook.com",
    "expirationDate": 1660291712.985808,
    "hostOnly": false,
    "httpOnly": false,
    "name": "c_user",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "100065710608270",
    "id": 2
},
{
    "domain": ".facebook.com",
    "expirationDate": 1689135894,
    "hostOnly": false,
    "httpOnly": true,
    "name": "datr",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "oQbDYCDikwHegXboOrA463G2",
    "id": 3
},
{
    "domain": ".facebook.com",
    "expirationDate": 1629176988,
    "hostOnly": false,
    "httpOnly": false,
    "name": "dpr",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "1",
    "id": 4
},
{
    "domain": ".facebook.com",
    "expirationDate": 1636531710.985867,
    "hostOnly": false,
    "httpOnly": true,
    "name": "fr",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "1Ak2TLFzNcfAkYuyE.AWVug97QANWcmH4E5nsZDXNBax8.BhFKNK.he.AAA.0.0.BhFNcB.AWVVsqfZpFU",
    "id": 5
},
{
    "domain": ".facebook.com",
    "expirationDate": 1629357244,
    "hostOnly": false,
    "httpOnly": false,
    "name": "locale",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "ko_KR",
    "id": 6
},
{
    "domain": ".facebook.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "m_pixel_ratio",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "1",
    "id": 7
},
{
    "domain": ".facebook.com",
    "expirationDate": 1691827714.98567,
    "hostOnly": false,
    "httpOnly": true,
    "name": "sb",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "oQbDYC-YLmKGBKMYzo8RiS8r",
    "id": 8
},
{
    "domain": ".facebook.com",
    "expirationDate": 1628845716.265384,
    "hostOnly": false,
    "httpOnly": true,
    "name": "spin",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "r.1004242720_b.trunk_t.1628755716_s.1_v.2_",
    "id": 9
},
{
    "domain": ".facebook.com",
    "expirationDate": 1629360508,
    "hostOnly": false,
    "httpOnly": false,
    "name": "wd",
    "path": "/",
    "sameSite": "lax",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "1920x978",
    "id": 10
},
{
    "domain": ".facebook.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "x-referer",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "eyJyIjoiL3NlYXJjaC90b3AvP3E9JUVCJThEJTk0JUVDJUExJUI0JUVCJUI5JTg0JUVDJUE2JTg4JUVDJTk4JUE4JnJlZj1jb250ZW50X2ZpbHRlciZ0c2lkPTAuODAxMjAyNzc1NjE2MDExNiZzb3VyY2U9dHlwZWFoZWFkIiwiaCI6Ii9zZWFyY2gvdG9wLz9xPSVFQiU4RCU5NCVFQyVBMSVCNCVFQiVCOSU4NCVFQyVBNiU4OCVFQyU5OCVBOCZyZWY9Y29udGVudF9maWx0ZXImdHNpZD0wLjgwMTIwMjc3NTYxNjAxMTYmc291cmNlPXR5cGVhaGVhZCIsInMiOiJtIn0%3D",
    "id": 11
},
{
    "domain": ".facebook.com",
    "expirationDate": 1660291712.985841,
    "hostOnly": false,
    "httpOnly": true,
    "name": "xs",
    "path": "/",
    "sameSite": "no_restriction",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "16%3AlhUM6haQHUmD-g%3A2%3A1628755714%3A-1%3A-1",
    "id": 12
}
]

**Comment by neon-ninja** [comment]
Can confirm those cookies aren't valid anymore, despite being structurally correct. I think you must have clicked the "Log out" button on Facebook after capturing those cookies, thereby invalidating them. Log back into Facebook, re-capture your cookies, but don't click Log out.

**Comment by ehdgurdkf** [comment]
I got it. Thanks! @neon-ninja
