### ISSUE TITLE
How to save particular result in csv when parsing from CLI ?

### ISSUE THREAD

**Issue by vitovt** [kevinzg/facebook-scraper#436]
I'm parsing fb pate from CLI like that:

` facebook-scraper --filename nintendo_page_posts.csv --pages 5000 --cookies my_cookies.json nintendo`

I parse many-many pages (try to parse all page posts once) and often get different errors (block, timeout, network error, etc). After that all hours of my work are lost.
It there any option to save .csv file (maybe with different extension f.e. .csv.partial), even if error ocured ?

**Comment by neon-ninja** [comment]
No. You would need to write a Python script for that level of customisation

**Comment by vitovt** [comment]
Ok. Thanks.
I'm not so familiar with python to do that (

**Comment by neon-ninja** [comment]
https://github.com/kevinzg/facebook-scraper/commit/c61f3487612de418bf81b69e8b5cc981eecb4e0f should harden CLI post extraction a bit, catching exceptions and then writing out the CSV anyway. I would also recommend increasing the timeout with the timeout parameter if you're running into timeout issues.

**Comment by vitovt** [comment]
Thankyou!

**Comment by vitovt** [comment]
Sorry for reopening issue.
c61f348 really helps. But now if I'm temporary blocked, I see uninfomative message:
`Couldn't get any posts.`
instead of explanation
`You are temporary blocked`

**Comment by neon-ninja** [comment]
That would be because the TemporarilyBanned exception is caught. It would still be logged.
