### ISSUE TITLE
Including cookies adds risk ? 

### ISSUE THREAD

**Issue by emiliojab** [kevinzg/facebook-scraper#437]
The only way i change the locale from to en_US is by including my cookies after logging in.

Doesn't that add the risk of banning my fb account if FB knew about the scraping ? since I am adding my use id with the cookies.

**Comment by neon-ninja** [comment]
In theory, but in practise, you typically only see temporary bans for excessive scraping. If you're concerned about it, just make a new facebook account for scraping

**Comment by emiliojab** [comment]
Alright!
Thank you for the prompt reply.

Is that why i am getting a very large and messy result from get_profile() ?

The result is not well (json) structured. I am getting the expected result ...i guess ... since i can't read them all because the result includes lots of data from the request/response headers.

**Comment by neon-ninja** [comment]
Huh? What code are you using? What's the output?

**Comment by emiliojab** [comment]
>>>get_profile("facebookID")

I pasted the result of my own account's scraping in a text document.

[scraping-test.txt](https://github.com/kevinzg/facebook-scraper/files/6978477/scraping-test.txt)
document

**Comment by neon-ninja** [comment]
Strange, the code:

```python
pprint(get_profile("100001170528457", cookies="cookies.txt"))
```
outputs:
```python
{'Basic Info': 'Male\nGender\nWomen\nInterested In',
 'Contact Info': {'Facebook': '/el.jabbour', 'Instagram': 'emiliojab'},
 'Education': 'AUST - Achrafieh ( American University of Science and '
              'Technology)\n'
              'Computer science\n'
              '2020 - Present\n'
              'AUL University\n'
              'BS in Computer and Communication Engineering',
 'Family Members': 'Gabriel Jabbour\nCousin',
 'Life Events': '',
 'Name': 'Emilio Jabbour',
 'cover_photo': 'https://scontent.fhlz2-1.fna.fbcdn.net/v/t1.6435-9/fr/cp0/e15/q65/128298875_3439917982723852_8323324331711751703_n.jpg?_nc_cat=107&ccb=1-4&_nc_sid=dd9801&efg=eyJpIjoidCJ9&_nc_ohc=nY1_JK5awXQAX95oDiQ&tn=M_pw8qegwC4qCLuh&_nc_ht=scontent.fhlz2-1.fna&oh=d7fc25e0845bf8b6bb489235af588642&oe=613C63E9&manual_redirect=1',
 'cover_photo_text': "Cover Photo: Emilio Jabbour's photo.",
 'id': '100001170528457',
 'profile_picture': 'https://scontent.fhlz2-1.fna.fbcdn.net/v/t1.6435-9/fr/cp0/e15/q65/176589226_3825641970818116_1994488441831863125_n.jpg?_nc_cat=107&ccb=1-4&_nc_sid=85a577&efg=eyJpIjoidCJ9&_nc_ohc=iG2BGzOsYjAAX9V8L_5&_nc_ht=scontent.fhlz2-1.fna&oh=7f34f6f6d00e28e5f3efec42ffb6d58c&oe=6139BAFA&manual_redirect=1'}
```
For me. I note you have right to left characters (https://www.fileformat.info/info/unicode/char/200f/index.htm) embedded in your txt file - perhaps this is the reason. Do you get any locale warnings?

**Comment by emiliojab** [comment]
It worked on my windows when i enabled "allow UTF-8 for worldwide language support".
But not on my ubuntu, even when i changed my locale variables to c.utf-8 (while it was en-US.UTF-8).

**Comment by emiliojab** [comment]
and yes i get locale warnings when i don't use any cookies in the scraping process. even when the scraping worked fine on my windows. 
Just like your result.

**Comment by neon-ninja** [comment]
Why not just use windows then?

**Comment by emiliojab** [comment]
That's what i'm doing now.
Thank you for helping out.
