### ISSUE TITLE
I can't get response from this page

### ISSUE THREAD

**Issue by Renish94** [kevinzg/facebook-scraper#44]
I want to get post text from https://www.facebook.com/doubledowncasino/ this fb page

I also tried with login credentials but not working help me please

`get_posts('doubledowncasino', pages=2, credentials=('***@gmail.com','******'))`

**Comment by demangejeremy** [comment]
Same for me on a similar page. Help!
I'm trying to see if I find the problem.

**Comment by neon-ninja** [comment]
Try pass cookies as per the readme, this page requires you to be logged in to view.
