### ISSUE TITLE
`Reactors` option does not work

### ISSUE THREAD

**Issue by belalhamdy** [kevinzg/facebook-scraper#441]
When I enable `Reactors` option it gets an internal server error because of the URL
Here is my code snippet
```python
from facebook_scraper import *

import json

page_name = 'Nintendo'
x = next(get_posts(account=page_name, page_limit=3,options={"reactors":True, "progress": True},cookies='cookies.txt'))
print(json.dumps(x, indent=4, default=str, ensure_ascii=False))
```
It fails in line 623 in `extractors.py` which is:
 ```python
response = self.request(url)
```
Because it returns this [URL](https://m.facebook.com/ufi/reaction/profile/browser/fetch/?limit=2950&shown_ids=100071677902144%2C100071484819885%2C100071281436080%2C100071079737010%2C100071070376680%2C100070927483318%2C100070488647455%2C100070426699957%2C100070267713830%2C100070106408279%2C100070087223792%2C100069875335458%2C100069614109522%2C100069454819545%2C100069098820892%2C100068967822785%2C100068556466223%2C100068385862928%2C100068017874484%2C100067678508324%2C100067643284192%2C100067571773160%2C100067465548742%2C100067223115192%2C100067222969175%2C100066957545312%2C100066464374777%2C100066432018117%2C100065972073211%2C100065061615160%2C100064602737515%2C100064580739585%2C100064491993214%2C100064403744619%2C100064346435472%2C100063710947910%2C100063604325177%2C100063573287965%2C100061794233158%2C100060637927813%2C100060576716303%2C100059406723088%2C100059273891246%2C100058780418872%2C100058692947631%2C100058373417510%2C100057886082834%2C100057637474719%2C100057474617015%2C100057377593955&total_count=925&ft_ent_identifier=4408734065877679)

**Comment by neon-ninja** [comment]
https://github.com/kevinzg/facebook-scraper/commit/fd77a64afad216ae56afc5bcbb2084391cd949e1 should fix this

**Comment by nvmnghia** [comment]
It returns `null` now for `reactors`, `reactions`, `reaction_count`.

**Comment by neon-ninja** [comment]
Try https://github.com/kevinzg/facebook-scraper/commit/98315da50804926a589b556f48f6928550a0e75d

**Comment by TathagataRoy1278** [comment]
@neon-ninja  I tried that and added some debug statements, turns out in the scope of `extractors.py` line 618, the value of `more` is `None` and length of `elems` is `0` even though the post has reactions.
[Post URL](https://facebook.com/doiniknewsassam/posts/412010190542156)

**Comment by neon-ninja** [comment]
@TathagataRoy1278  try https://github.com/kevinzg/facebook-scraper/commit/3f0b7260c22ac7dbec5f858c90af242d34d2d095

**Comment by TathagataRoy1278** [comment]
Still returns `None`.
Also as a side note why does getting reactors need access to cookies?

**Comment by neon-ninja** [comment]
How did you update? Try browse m.facebook.com in an incognito window and see how far you can get before facebook insist you login

**Comment by TathagataRoy1278** [comment]
The very first page demands a login in incognito.

**Comment by neon-ninja** [comment]
So how could the scraper access Facebook without login if your browser can't?
