### ISSUE TITLE
Time format strange addon: -07:00 -08:00

### ISSUE THREAD

**Issue by vitovt** [kevinzg/facebook-scraper#447]
Today I've found that latest GIT version of parser often (but not allways) returns time in strange format:
```
      'time' => '2021-08-17 07:32:56-07:00',
      'time' => '2021-08-18 03:48:37-07:00',
      'time' => '2021-08-16 11:24:09-07:00',
      'time' => '2021-03-11 17:05:36-08:00',
```
Maybe facebook changed something ? Cookies lang environment is set to En_US

p.s. Not sure, maybe it is timezone ?

**Comment by neon-ninja** [comment]
This is related to https://github.com/kevinzg/facebook-scraper/issues/439 / https://github.com/kevinzg/facebook-scraper/commit/00440f7a590e2d071cd1dea9f72775c4ec9cbcb6, these ads return a datetime with a timezone. https://github.com/kevinzg/facebook-scraper/commit/4a7eeae2f8a9a5b545375c223429f8b7c7be6a55 should convert it to local time to make it more consistent with other posts.

**Comment by vitovt** [comment]
Fixed
