### ISSUE TITLE
Requesting Tips and Tricks to reduce temporary ban

### ISSUE THREAD

**Issue by belalhamdy** [kevinzg/facebook-scraper#459]
I want to scrape a lot of posts with their comments. can you give me some tips and tricks to reduce the chance of getting banned?
Also I want to know the optimal sleeping time if I should use the comments generator.

Thanks

**Comment by neon-ninja** [comment]
See https://github.com/kevinzg/facebook-scraper/issues/409. If you just want comments and not replies, you can do that and that'll result in fewer requests, reducing the likelihood of a temp ban. Apart from that, depending on the scale of the scraping you want to do, you might just need to be very patient

**Comment by belalhamdy** [comment]
@neon-ninja  thanks for your reply I have seen it but I still have a question.. What is the average number of requests per minute that should keep me in the safe zone?

**Comment by neon-ninja** [comment]
It depends on the total number of requests you're making

**Comment by belalhamdy** [comment]
@neon-ninja  assume I want to request a very huge number of posts

**Comment by neon-ninja** [comment]
What's huge? 1K? 10K? 100K?

**Comment by belalhamdy** [comment]
like 100K or more

**Comment by neon-ninja** [comment]
At that sort of scale, you might have better luck with CrowdTangle (https://help.crowdtangle.com/en/articles/4302208-crowdtangle-for-academics-and-researchers)

**Comment by belalhamdy** [comment]
okay thanks
