### ISSUE TITLE
Will accesses to video or image URLs affect the risk of being banned?

### ISSUE THREAD

**Issue by jha46** [kevinzg/facebook-scraper#465]
Hello, I am working on downloading  image and video from URLs from 'image' and 'video' field. 
It seems that these are not directed from FB website.
Do you guys have any ideas about whether requesting many accesses to these websites is also risky?

Thank you!

(e.g.)
https://scontent-bos3-1.xx.fbcdn.net/v/t1.6435-9/fr/cp0/e15/q65/37863145_2123770104540096_6583112411434188800_n.jpg?_nc_cat=1&ccb=1-5&_nc_sid=85a577&efg=eyJpIjoidCJ9&_nc_ohc=E1kiHGD1-HUAX_Khxzv&tn=oFnvAoh8xGnoEu_F&_nc_ht=scontent-bos3-1.xx&oh=b62bf9e76a9f5e8245f5f7d9916d80d5&oe=615DFE6A

(e.g.) https://video-bos3-1.xx.fbcdn.net/v/t42.1790-2/19889794_323835044720688_5659246404690771968_n.mp4?_nc_cat=104&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjUyMCwicmxhIjo1MTIsInZlbmNvZGVfdGFnIjoic3ZlX3NkIn0%3D&_nc_ohc=aIF7h__NmCIAX-gTN_9&_nc_rml=0&_nc_ht=video-bos3-1.xx&oh=1f3dc03e33d7fef298200007463cabe8&oe=61370849

**Comment by neon-ninja** [comment]
I don't think so, as you can access these CDN links without authentication even

**Comment by TowardMyth** [comment]
Video URLs time out after ~24-48 hours. As an example, if you click on the above video link provided by OP, you will get "URL signature expired" message. 

Is there a way to get a new version of the Video URL, without having to refetch all posts?

**Comment by neon-ninja** [comment]
Why not just download it within that 24-48 hour period then? If you have the post IDs, you can fetch just those post IDs directly with the `post_ids` argument to `get_posts`
