### ISSUE TITLE
No posts detected from certain groups

### ISSUE THREAD

**Issue by michelemostarda** [kevinzg/facebook-scraper#472]
In the last 48h the latest version of the scraper stopped woking on some Italian public groups, after having worked successfully dozen times in the past month.

The group produces new posts every 2/3 h, I checked at time of this test and there are lot of fresh posts.

Verified versions

`facebook-scraper==0.2.46`
`facebook-scraper==0.2.45`

Locale is correctly configured, also I don't see any warning about it.

```
from facebook_scraper import get_posts

facebook_scraper._scraper.session.cookies.update({'locale': 'en_US'})
for raw_post in get_posts(account=None, group='bitcoinitalia3', page_limit=50, credentials=None):
     print(raw_post)
```

I get the following warnings:

```
WARNING 2021-09-12_12:43:27 page_iterators.py th=MainThread _get_page:180 No raw posts (<article> elements) were found in this page.

INFO 2021-09-12_12:43:27 page_iterators.py th=MainThread generic_iter_pages:95 Page parser did not find next page URL
```

**Comment by neon-ninja** [comment]
Looks related to the change of user agent introduced in https://github.com/kevinzg/facebook-scraper/issues/300 - try https://github.com/kevinzg/facebook-scraper/commit/e99a759944224a58b9cd572578e3923f9c9672c9

**Comment by michelemostarda** [comment]
Ok just tested, this works fine now.

I don't understand yet why for some groups like 'nintendo' was working fine even without the user agent fix.

```
        facebook_scraper._scraper.session.cookies.update({'locale': 'en_US'})
        facebook_scraper._scraper.set_user_agent(
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8"
        )
        for raw_post in get_posts(account=None, group='bitcoinitalia3', page_limit=50,
                                  credentials=None):
           print(raw_post)
```

**Comment by neon-ninja** [comment]
Nintendo is a page, not a group
