### ISSUE TITLE
Scraping post with no comment

### ISSUE THREAD

**Issue by cmhc2021** [kevinzg/facebook-scraper#475]
When scraping a post with no comment, e.g. 1919102561606491, it returns "NoneType object has no attribute found" in line 974 of extractors.py.  Think might need to change to

if (elem is None):
    comments = None
else:
    comments = list(elem.find(comments_selector))

**Comment by neon-ninja** [comment]
Actually, this post has 2 comments, the scraper just wasn't correctly extracting them. Try https://github.com/kevinzg/facebook-scraper/commit/d95de50318d86b4375701edbfc36a003b9a712a3

**Comment by cmhc2021** [comment]
I experienced 'NoneType' object has no attribute 'find' again when scraping commonfarms even with the revised code.
I found that if I add the following in line 972, the error disappears but then it cannot scrape any comments.
    elem = self.full_post_html.find(comments_area_selector, first=True)
        ##########
        if not elem:
            logger.warning("No comments found on page")
            return
        ##########
        comments_selector = 'div[data-sigil="comment"]'
It seems elem unexpectedly return None...

**Comment by cmhc2021** [comment]
@neon-ninja, I experienced 'NoneType' object has no attribute 'find' again when scraping commonfarms even with the revised code.  This time, it seems the error is throwing in extractors.py line 975 which is an earlier place.  Any idea?

**Comment by neon-ninja** [comment]
Try https://github.com/kevinzg/facebook-scraper/commit/9674f13da3e3a05e63fefda4a465cee7b05022e0
