### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by mjuanes** [kevinzg/facebook-scraper#48]
First, I would like to say thank for your work, this script is very useful.

I ran get_post with a absurdly big number just to get all the post of the post.
After downloading 144 post I got this

`  File ".../facebook_post_downloader/venv/lib/python3.6/site-packages/facebook_scraper.py", line 75, in _get_posts
    yield _extract_post(article)
  File ".../facebook_post_downloader/venv/lib/python3.6/site-packages/facebook_scraper.py", line 102, in _extract_post
    text, post_text, shared_text = _extract_text(article)
  File ".../facebook_post_downloader/venv/lib/python3.6/site-packages/facebook_scraper.py", line 137, in _extract_text
    nodes = article.find('p, header')
AttributeError: 'NoneType' object has no attribute 'find'

Process finished with exit code 1
`

I was expecting a graceful exit from the generator.

**Comment by Fubuchi** [comment]
From line 139 to 143 of the file facebook_scraper.py (v0.1.10) :

```
if match:
    url = f'{_base_url}{match.groups()[0].replace("&amp;", "&")}'
    response = _session.get(url, timeout=_timeout)
    article = response.html.find('.story_body_container', first=True)
nodes = article.find('p, header')
```

Try to edit the code and log the url then open it in the browser and use inspect tool find if there is any class "story_body_container".
It seem like facebook change the page structure, after change '`.story_body_container'` to `'#m_story_permalink_view'`, everything work fine for me.

**Comment by TheMulti0** [comment]
I also experience this error

**Comment by neon-ninja** [comment]
Working fine for me
