### ISSUE TITLE
How to specify limit if scraping group pages

### ISSUE THREAD

**Issue by cmhc2021** [kevinzg/facebook-scraper#480]
If I scrape group pages, say, InstantPotCommunity by passing get_posts('groups/InstantPotCommunity', pages=2...), it seems it cannot limit the no. of page of results.  How can we specify the limit?

**Comment by neon-ninja** [comment]
Try `get_posts(group="InstantPotCommunity"...` instead

**Comment by cmhc2021** [comment]
I tried get_posts(group="InstantPotCommunity"... ) but the result is the same.  If I set pages = 2, it will scrape 42 posts with 2415 comments.  Normally when scraping with pages = 2, it will only return 5 posts.  Is the pages parameter still valid when scraping group?

**Comment by cmhc2021** [comment]
I found the scraping results very strange, not the same posts as I see on Facebook, the order is not right and sometimes there are duplicated posts...

**Comment by neon-ninja** [comment]
Groups work differently to pages, pages give 2 posts on the first page, then 4 posts per page by default. Groups give ~20 posts per page.

**Comment by cmhc2021** [comment]
Thanks. I'm fined with the posts per page.  But can you help to look into some strange results, say

When I scraped groups/hongkongbabies, it returns duplicated post_id
1769534173253543
1769534173253543 (duplicated)
1773910816149212
1773870152819945
1773775526162741

**Comment by cmhc2021** [comment]
And when I scraped groups/instantpotcommunity, it returns
4747912258636058  Celebrate the Fall Equinox with quintessential Fall vibes!...
4747016245392326  It's soup season ! What is the best soup you cook in the instant pot ???
4748674258559858  So, this happened today...times 2...
4748818258545458  Does anyone have some recipes for using wild game...
4748875578539726  Used my instant pot to make perfect sushi rice and used my instant air...

but what I saw on web was 
Our Instant Pot® Yogurt setting isn’t just for making yogurt!...
Used my instant pot to make perfect sushi rice and used my instant air... (the 5th result)
It's soup season ! What is the best soup you cook in the instant pot ??? (the 2nd result)
I’m pretty sure a lot of you are my type of people...
Can anyone who has this product give me a quick review...

It seems I'm not scraping what I saw on web.

**Comment by neon-ninja** [comment]
Maybe Facebook are adjusting the order of posts based on account or device
