### ISSUE TITLE
I can't get the full commnets, only 30~

### ISSUE THREAD

**Issue by blutics** [kevinzg/facebook-scraper#490]
`posts = facebook_scraper.get_posts(
    post_urls=[url],
    options={
        "comments": True,
        "progress": True,
    },
    cookies = cookies,
    extra_info=True
)

post = next(posts)
print(post)
for n, cmt in enumerate(post['comments_full']):
    print(n, cmt)
print(len(post['comments_full']))`

with this code, I'm only available to see 30 of comments.

and I got an warning message about locale, which is about en_US is best but I'm in ko_KR
Am I missing something??

**Comment by neon-ninja** [comment]
Set your Facebook language to English, then re-export your cookies. Also, what post id are you having this problem with? Is it a video post?

**Comment by blutics** [comment]
the id is 4392606570798592 and it is not a video : )

**Comment by blutics** [comment]
setting the facebook language to english worked for me!!
Thank you for your answer!!

**Comment by HakzA** [comment]
Hello,

I'm experiencing the exact same problem. I can only extract 30 comments from the post 10157405244133520 with my code:
```
post = next(get_posts(post_urls = [url],  # or  post_urls = [url], same results
                          options =    {'locale': 'en_US',
                                        "comments": True,
                                        "allow_extra_requests": True,
                                        "reactors": True,
                                        "progress": True,
                                        "extra_info": True
                                         }))
```
I have tried changing the language by adding the following:

`facebook_scraper._scraper.session.cookies.update({'locale': 'en_US'})`

but I'm still only getting 30 comments. Any help would be much appreciated, and thank you for this repo.

**Comment by neon-ninja** [comment]
Setting that cookie does nothing, you need to set your language on the Facebook end

**Comment by HakzA** [comment]
@neon-ninja I changed my facebook language and extracted the cookie.json using EditThisCookie, but I'm still only getting 30 comments, while the post has 400+ comments (not just replies). The 'locale' is set to 'en_US', any suggestions?

**Comment by HakzA** [comment]
If I run your above code, I get the error:

`File "/opt/project/test.py", line 46, in test
     print(post["comments"], len(post["comments_full"]), sum(len(c["replies"]) for c in post["comments_full"]))
File "/opt/project/test.py", line 46, in <genexpr>
     print(post["comments"], len(post["comments_full"]), sum(len(c["replies"]) for c in post["comments_full"]))
KeyError: 'replies'`

**Comment by HakzA** [comment]
I'm running a Docker container. I'm able to install the package with:

`pip install facebook-scraper`

But not with:

`pip install git+https://github.com/kevinzg/facebook-scraper.git`

Seems like the problem is with my end, I'll have to do some more debugging.

**Comment by neon-ninja** [comment]
Thanks for the link. This commit (https://github.com/kevinzg/facebook-scraper/commit/509a7baf0c1cf0535e6c2a38cce86212f14bec3f) upgrades from demjson to demjson3

**Comment by natanlaurett** [comment]
I'm getting this same problem for comments in a video post. My Facebook's language is english and I am with the latest version of master branch. The get_posts call is:

`get_posts(post_urls=post_ids, cookies="cookies.json", options={"comments":True, "progress": True, "allow_extra_requests": True})`

and `post_ids=["211857482296579_1798983683583943","211857482296579_1798816063600705"]`

Any ideas on what am I doing wrong here, or there is a problem up with comments in video posts?

**Comment by neon-ninja** [comment]
Try https://github.com/kevinzg/facebook-scraper/commit/1d8711658a1baf04cd389c2d44d74ebdf247046b

**Comment by natanlaurett** [comment]
It works! Amazing, thanks!

**Comment by sinanajluan** [comment]
Traceback (most recent call last):
  File "C:\Users\Lenovo T440p\PycharmProjects\facebook-scraper\ProveLuani.py", line 19, in <module>
    post = next(get_posts(post_urls=[10157405244133520], cookies="cookies.json", options={"comments":True, "progress": True}))
  File "C:\Users\Lenovo T440p\PycharmProjects\facebook-scraper\facebook_scraper\__init__.py", line 196, in get_posts
    set_cookies(cookies)
  File "C:\Users\Lenovo T440p\PycharmProjects\facebook-scraper\facebook_scraper\__init__.py", line 40, in set_cookies
    cookies = parse_cookie_file(cookies)
  File "C:\Users\Lenovo T440p\PycharmProjects\facebook-scraper\facebook_scraper\utils.py", line 221, in parse_cookie_file
    with open(filename, mode='rt') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'cookies.json'

Process finished with exit code 1

**Comment by neon-ninja** [comment]
Make sure you have a cookies.json file in your working directory
