### ISSUE TITLE
[Suggestion] CLI JSON output

### ISSUE THREAD

**Issue by CrysoK** [kevinzg/facebook-scraper#491]
A parameter should be added to choose the type of output (?). It would be basically like the [README example](https://github.com/kevinzg/facebook-scraper#post-example). I found it kind of weird that CSV is used instead. Is it for some reason that I do not know?
This along with #489 would be perfect to use the program from other languages.

**Comment by neon-ninja** [comment]
Sure - try https://github.com/kevinzg/facebook-scraper/commit/84bdbd014c32ad33cdbefd53b6515a4ef90d885c. This commit adds a new parameter, `-fmt` or `--format`.  Sample usage: `facebook_scraper Nintendo -p 1 -fmt JSON -f -`

**Comment by CrysoK** [comment]
It seems to work perfect. Thanks.
