### ISSUE TITLE
High quality images

### ISSUE THREAD

**Issue by hungphamvn** [kevinzg/facebook-scraper#492]
Hi, when I get group post's images with get_posts() function, it returned 720x720 images, are there any solution for getting the full size image?
Thanks!

**Comment by neon-ninja** [comment]
Try https://github.com/kevinzg/facebook-scraper/commit/3d388b8d3e492b1929f807b562d97d8b0e4164d7

**Comment by hungphamvn** [comment]
Wow. Super fast and accurate.. Thank you so much @neon-ninja !!
