### ISSUE TITLE
Cannot install due to demjson use_2to3

### ISSUE THREAD

**Issue by Ierezell** [kevinzg/facebook-scraper#495]
The same kind of issue was also raised for other packages: https://github.com/tikitu/jsmin/issues/33

As setuptools dropped support for use_2to3 installation of demjson fails and thus facebook-scrapper. 

Demjson already have the problem: https://github.com/dmeranda/demjson/issues/40 

EDIT : 

Just saw the new pyproject.toml which depends on demjson3
I will wait for it to be published on pyPi 

Thanks a lot for the quick fix ! 
Have a great day

**Comment by neon-ninja** [comment]
New PyPI release published as v0.2.47
