### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by null15** [kevinzg/facebook-scraper#500]
```
from facebook_scraper import get_posts

for post in get_posts('CounterSideSEA', locale='en_US', encoding='utf-8', pages=5, cookies='cookies.json'):
    print(post['text'][:50])
```

Error: 

Traceback (most recent call last):
  File "c:\Users\Raiko\Desktop\Python Project\main.py", line 4, in <module>
    print("\U0001f929")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f929' in position 0: character maps to undefined

Is this not the proper way to set the encoding?

**Comment by neon-ninja** [comment]
This is the unicode code point for the 🤩 emoji. This works fine for me, your code outputs:

```
[🤩Let's get to work! Yoo Mina ♪~]

- So, I'll be c
```

Does your terminal not support emojis? What happens if you do:
```python
print("🤩")
```

**Comment by null15** [comment]
> ```python
> print("🤩")
> ```

That did seem not to work, my terminal doesn't seem to support it? same error

**Comment by neon-ninja** [comment]
According to https://stackoverflow.com/a/64940213, the only windows terminals that support emoji is Windows Terminal

**Comment by null15** [comment]
> According to https://stackoverflow.com/a/64940213, the only windows terminals that support emoji is Windows Terminal (https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab)

Thanks! I changed to powershell and it works now
