### ISSUE TITLE
Image URL

### ISSUE THREAD

**Issue by null15** [kevinzg/facebook-scraper#502]
Assume post has an image URL, can it fetch the url too? Like my post is:

[🤩Let's get to work! Yoo Mina ♪~]

- So, I'll be cruising on a super-luxurious ship?🤔
- That's right, Mina. On a special vacation awarded to you by the Boss for solving the Replacer case.😎

- Hey, rookie! Stop dilly-dallying and clean each and every nook and cranny!
- A vacation, my butt. I knew this was too good to be true.🤦‍♀️

#COUNTERSIDE #Manhwa
[image here]

I have a python script, writing the content to a text file, but wondering if the scrapper can somehow include the image url link below the post too, if there is one? Or does it not support this yet

**Comment by neon-ninja** [comment]
Yes, check `post["image"]` or `post["images"]`

**Comment by null15** [comment]
> Yes, check `post["image"]` or `post["images"]`

Thank you 💖

**Comment by TowardMyth** [comment]
@neon-ninja Would this image also have a `image_id` or no, since the image is externally hosted?

**Comment by neon-ninja** [comment]
Which image?
