### ISSUE TITLE
How can I download the facebook scraped data in an excel file

### ISSUE THREAD

**Issue by Reena-Behl** [kevinzg/facebook-scraper#52]
This is the code
for post in get_posts('iamforloveofwater', pages=50, extra_info=True):
     #print (post)
    print (post['text'][:100])
    temp=pd.DataFrame(data=post)
    dj=dj.append(temp,verify_integrity=False)

Error: ValueError: If using all scalar values, you must pass an index

**Comment by kevinzg** [comment]
I merged #36 that allows to save the posts as a CSV file, you should be able to open that in excel.

I also added an entry point so you can run it directly from the command line:

```bash
$ facebook-scraper <account> -f file.csv
# or
$ python -m facebook-scraper <account> -f file.csv
```
