### ISSUE TITLE
`"comment_reactors": True` still results in `"comment_reactors": "<generator object PostExtractor.extract_reactors at 0x7f1fca7f4a40>",` 

### ISSUE THREAD

**Issue by fraba** [kevinzg/facebook-scraper#529]
Hello,

I am trying to write to json a post's comments and all reactions - including comments' reactors. I have set `"comment_reactors": True`. Still in the post dump I get a few fields such as `"comment_reactors": "<generator object PostExtractor.extract_reactors at 0x7f1fca7f4a40>",` although for others I actually get as expected:

```
            "comment_reactors": [
                {
                    "name": "Sara James",
...
```

Did I hit a limit in the number of nested levels the scrapers is able to get?

**Comment by neon-ninja** [comment]
Either way, try my latest commit and see if that fixes your issue
