### ISSUE TITLE
can't get sharers from post

### ISSUE THREAD

**Issue by l0rtk** [kevinzg/facebook-scraper#539]
with get_posts(page_link,pages = pages,options={"comments": True,"reactors": True, "sharers" : True}) can't get sharers correctly,
in the returned dictionary there is "shares" more than 0 but "sharers" is [] empty list

**Comment by neon-ninja** [comment]
What page are you having this problem with?

**Comment by neon-ninja** [comment]
You need to login. Try pass cookies as per the readme

**Comment by l0rtk** [comment]
still can't get, tries twice before script set_cookies and then get_posts(cookies="cookies.txt") but neither one has worked

**Comment by neon-ninja** [comment]
Also try update to the latest version

**Comment by l0rtk** [comment]
Updated and it works :) thanks!
