### ISSUE TITLE
Issue #544 was closed accidently. 

### ISSUE THREAD

**Issue by usman87626** [kevinzg/facebook-scraper#545]
[hashdevelop2k20.zip](https://github.com/kevinzg/facebook-scraper/files/7486751/hashdevelop2k20.zip)
Here is my HTML FILE

**Comment by usman87626** [comment]
@neon-ninja Can you please have a look at html file? Old issue was closed accidently while closing the comment tab

**Comment by neon-ninja** [comment]
You can reopen an issue. I'll take a look on Monday

**Comment by usman87626** [comment]
Sure

**Comment by neon-ninja** [comment]
Duplicate of https://github.com/kevinzg/facebook-scraper/issues/544
