### ISSUE TITLE
CLI → no post_per_page option

### ISSUE THREAD

**Issue by Rafurus** [kevinzg/facebook-scraper#552]
I don't see post_per_page option in CLI mode nor in help. 
I tried -o, --option, --options but none of them work. 
Could you add this to CLI?

**Comment by neon-ninja** [comment]
Sure, here you go: https://github.com/kevinzg/facebook-scraper/commit/cf6a2d22a54de7eef016fd8e219f196999d587bc

**Comment by Rafurus** [comment]
@neon-ninja Thanks, works brilliant.
