### ISSUE TITLE
issue with cookies/ facebook language

### ISSUE THREAD

**Issue by dr-nathan** [kevinzg/facebook-scraper#563]
hello!

I had quite a weird issue: your script would scrape any group, however it would be very slow:
in every retrieved post field, a lot of unnecessary text would get sucked in for some reason. For example, in the field post_text, you would get the post text first, but then also the text of the next post and of the next 30 posts, the group name, and pretty much all the text that figures on the webpage (+ a lot of human-unreadable text). 

I actually resolved it by going to Facebook and setting the language to english (US) and re-exporting the cookies. I have absolutely no idea why, but it worked! 

Thought I'd share! In case anyone runs into the issue. 

EDIT:

actually, it did not fix the issue.. Still getting a lot of extra text. 

As an example: when scraping group 712266335452208, this is the text_post output of the first post:

```
Please report all non-room related posts

We can keep it clean togetherPlease report all non-room related posts

We can keep it clean together 
Like 
13
2 Comments
Like
Show more reactions
Comment
Share
Top posts
View TimelineAdd to GroupInvite to Event
Cancel
Where are you?
Cancel
Detecting location...
There was an error detecting your current location.

Please make sure Location Services is enabled in your browser, and that facebook.com has permission to use them. You can still search for a place, but the search will not be as accurate.
Add a Place
Required
Category
I am currently at this location
Places are public and can be seen by anyone. If you add a place with someone's personal information, ask them first.
Add
Cancel
Who are you with?
Done
Cancel
What are you doing?
Cancel
Done
Tag Photo
Done
Cancel
Zoekt kamer in Amsterdam Community
Post
Please add content to your status before posting
Write Something
Please include a written review with your ratingYou’re doing great!
Loading preview...
×
With
At
×
Photo
Zoekt kamer in Amsterdam Community
Posting something for sale?
Make this a sale post to highlight important info, such as price and photos.
Post item for sale
Post
(function(){var n=now_inl();requireLazy(["__bigPipe"],function(bigPipe){bigPipe.beforePageletArrive("MRoot",n);})})(); requireLazy(["__bigPipe"],(function(bigPipe){bigPipe.onPageletArrive({displayResources:["c4ExI9N","1eyqQBr",
...
```

**Comment by neon-ninja** [comment]
what version of facebook-scraper are you using?

**Comment by dr-nathan** [comment]
The most recent one! pulled it from github the same day

**Comment by neon-ninja** [comment]
Can you post the exact code you're using? Then I can try run the same code, and see if I get the same problem

**Comment by neon-ninja** [comment]
Few things to try:
Can you try add this code:
```python
from facebook_scraper import enable_logging
enable_logging(logging.DEBUG)
```
before your code and post the logs you get when you run it. Also try set `options={"allow_extra_requests": False}` and see if that makes a difference. Also try run this code:
```python
from facebook_scraper import _scraper
with open("712266335452208.html", "w") as f:
    f.write(_scraper.get("712266335452208").text)
```
and upload the resulting html file

**Comment by dr-nathan** [comment]
here are the logs:

```
exec(compiled, ns_globals, ns_locals)
Starting to iterate pages
Requesting page from: https://m.facebook.com/groups/712266335452208/
Parsing page response
Got 21 raw posts from page
Extracting posts from page 0
[4940771999268266] Exception while running extract_time: RecursionError('maximum recursion depth exceeded in comparison')
Fetching 100000612815784/posts/pcb.4939604039385062
Fetching https://m.facebook.com/photo.php?fbid=4961912737209219&id=100001716261902&set=gm.4939604039385062
Fetching https://m.facebook.com/photo/view_full_size/?fbid=4961912737209219&ref_component=mbasic_photo_permalink&ref_page=%2Fwap%2Fphoto.php&refid=13&__tn__=%2Cg
Fetching https://m.facebook.com/photo.php?fbid=4961912807209212&id=100001716261902&set=gm.4939604039385062
Fetching https://m.facebook.com/photo/view_full_size/?fbid=4961912807209212&ref_component=mbasic_photo_permalink&ref_page=%2Fwap%2Fphoto.php&refid=13&__tn__=%2Cg
[4940771999268266] Extract method extract_video didn't return anything
[4940771999268266] Extract method extract_video_thumbnail didn't return anything
[4940771999268266] Extract method extract_video_id didn't return anything
Fetching 4940771999268266
[4940771999268266] Exception while running extract_video_meta: AttributeError("'int' object has no attribute 'startswith'")
[4940771999268266] Extract method extract_factcheck didn't return anything
[4940771999268266] Extract method extract_share_information didn't return anything
[4940771999268266] Exception while running extract_time: RecursionError('maximum recursion depth exceeded in comparison')
```

`options={"allow_extra_requests": False}` didnt help unfortunately!

The HTML file is interesting: it starts off by saying my browser is unsupported. And lots of encoding issues. 

[712266335452208.html.zip](https://github.com/kevinzg/facebook-scraper/files/7553636/712266335452208.html.zip)

Thanks for helping out in any case!!

**Comment by neon-ninja** [comment]
I think the browser unsupported error is your issue. Try
```python
from facebook_scraper import *
set_user_agent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36")
```

**Comment by dr-nathan** [comment]
Weirdly, that did not solve the issue! I have the feeling it has something to do with my cookies. The way i extract those, is that it gets copied to my clipboard via the EditThisCookie plugin in Chrome. I paste that in a txt file and rename the extension to .json. Is that correct?

**Comment by neon-ninja** [comment]
If your cookies aren't valid, the scraper is supposed to throw an InvalidCookies exception (see https://github.com/kevinzg/facebook-scraper/blob/f29fe9e5af5d66066695c3bf2e642065dd36c852/facebook_scraper/__init__.py#L44). Likewise for a failed login, the scraper should throw a LoginError exception (see https://github.com/kevinzg/facebook-scraper/blob/f29fe9e5af5d66066695c3bf2e642065dd36c852/facebook_scraper/facebook_scraper.py#L716

**Comment by dr-nathan** [comment]
Yes that is true! But any further htmls i produce, by setting the user agent as above for example, show a version in which i am not logged in.
But in any case, the issue persists! Even if I don't specify any cookies, the parsing issue still shows up. Does your code interact with my browser at all? I did notice that setting my Facebook to english-US changed things a bit.

**Comment by neon-ninja** [comment]
Only if you set the recently added option, `cookies="from_browser"` does the scraper interact with your browser. Your Facebook language is tied to your account, and therefore to your cookies.

**Comment by dr-nathan** [comment]
Okay! Good to know, thanks. But then, the original error remains a mystery. Anything i could do to gain more insight into what exactly goes wrong?

**Comment by neon-ninja** [comment]
Can you send another HTML example?

**Comment by neon-ninja** [comment]
What OS are you using?

**Comment by dr-nathan** [comment]
There you go!

I am using macOS 10.14.
[712266335452208.html 2.zip](https://github.com/kevinzg/facebook-scraper/files/7624418/712266335452208.html.2.zip)
6

**Comment by dr-nathan** [comment]
on my browser, 2 facebook account are remembered. Maybe that causes interference? I will try to remove the cookies, log in and try again. Ill let you know what happens

**Comment by dr-nathan** [comment]
OK, i resolved the issue! It was painfully simple..
I reinstalled the requirements.txt and now all runs fine. 
I was under the impression that cloning from github ran the requirements.txt file automatically?
I have issues all the time with using both conda and pip, i guess that didn't help here.

Regardless, thank you so much for your help!
