### ISSUE TITLE
Feature - Scraping Facebook posts from time X to time Y

### ISSUE THREAD

**Issue by mohamedamara1** [kevinzg/facebook-scraper#570]
Can we add the functionality of scraping posts starting from a given date and to stop scraping at another given date.

For example I want to scrape the posts of a Facebook page from 7th November 2021 until 10th November 2021.

**Comment by neon-ninja** [comment]
This isn't possible unfortunately. What is possible, is to store pagination URLs, so that you can resume from a place where you left off. It's also possible to filter out posts based on timestamp as you go.
