### ISSUE TITLE
Locale detected other than en_US → could't get any posts

### ISSUE THREAD

**Issue by Rafurus** [kevinzg/facebook-scraper#572]
When i try to get some posts specific from this page: https://www.facebook.com/MRPORTERLIVE/ 
i got this message:
```
UserWarning: Locale detected as pl_PL - for best results, set to en_US
  warnings.warn(f"Locale detected as {locale} - for best results, set to en_US")
Couldn't get any posts.
```
What's interesting that first chunk was working.
But from second, this warning appears. 

I work in WSL so i try this: https://newbedev.com/how-do-i-change-the-language-of-the-linux-subsystem-in-windows-10-wsl
and even change locale on my Windows. 
Neither it works.

**Comment by Rafurus** [comment]
Okey, i found a problem.
Account was flagged for picture verification. 
Maybe you could add some other info message when it happen than locale info?

**Comment by neon-ninja** [comment]
Try set your Facebook language to English, and re-export cookies

**Comment by neon-ninja** [comment]
https://github.com/kevinzg/facebook-scraper/commit/9a30f1210b30a4ee392265ba08380caf46c57160 This should make the error clearer
