### ISSUE TITLE
Resume scraping option

### ISSUE THREAD

**Issue by PinchOfData** [kevinzg/facebook-scraper#584]
Hi, 
Is there an option to resume the scraping on a Facebook page ? (i.e., pick up where you left off) 
[Twint](https://github.com/twintproject/twint) provides this option for Twitter, and it's a treat. 
Best,

**Comment by neon-ninja** [comment]
yes, see https://github.com/kevinzg/facebook-scraper/issues/310#issuecomment-852652846
