### ISSUE TITLE
Can't log in with credentials or cookies

### ISSUE THREAD

**Issue by Ianneee** [kevinzg/facebook-scraper#599]
Hi, i'm trying using cookies and credentials to scrape pages but every time i get the following issues:

using credentials:
```python
def scrape_nintendo_page():
    for post in get_posts('nintendo', pages=10, credentials=("email", "password")):
        print(post['text'][:50])
```

Error message: raise exceptions.LoginError("Login unsuccessful")

I've found this login_error.html in my main directory: [https://ibb.co/XSFwGHr](url)

using cookies file:

```python
def scrape_page():  
    for post in get_posts(
        group=PAGE,
        pages=pages,
        extra_info=extra_info,
        timeout=timeout,
        cookies="cookies.txt",
        options=options
    ):
        print(post)
```

Error message: facebook_scraper.exceptions.NotFound: Content Not Found
I've generated my cookies.txt file from chrome using EditThisCookies extension as suggested.

I'm in Italy and not using any proxy or vpn, i can login through incognito on m.facebook.com and i've selected english(US) as main language.

**Comment by Metgraph** [comment]
Your issue is related yo your region, while in America facebook automatically sets the cookies, in EU you need to accept them.
Facebook requires the cookie named `datr` and it can be find the value in the html code after the word `_js_datr` (you can get it doing substring ).

**Comment by neon-ninja** [comment]
What group are you having this problem with?

**Comment by Ianneee** [comment]
> What group are you having this problem with?

I've solved the problems with my cookies file, i was using a cookies disabler without remembering it.
For the login as @Metgraph said is a problem with accepting cookies page if you are from EU, i think we are now both in a pull request for fix this issue.
