### ISSUE TITLE
Timestamp option

### ISSUE THREAD

**Issue by dragonxtek** [kevinzg/facebook-scraper#60]
I get the following info from nintendo, with extra_info=True:

> 
![image](https://user-images.githubusercontent.com/10552658/81721825-789aeb00-944e-11ea-8d85-5c94d0a33288.png)

But, I can see the timestamp from when the text was posted.
How I can see the timestamp?

**Comment by kevinzg** [comment]
Try printing `post['time']`.

**Comment by dragonxtek** [comment]
In fact, with post['time'] it works.
Do you know how I can read posts until a date? I use pages=(great number) to reach every posts, but I considered that is not an optimal command. Anyway, here's an implementation to add in the repo about how to search posts up to a specific date:

```
from facebook_scraper import get_posts
import datetime
start_date=datetime.datetime(2020,5,1)
for post in get_posts('NintendoLatAm', pages=99999999):
    if (start_date>post['time']):
       break
    print(post['time'],post['text'])
```
