### ISSUE TITLE
Can get only comments numbers but comments_full is empty

### ISSUE THREAD

**Issue by Ianneee** [kevinzg/facebook-scraper#609]
I'm having problems with comments extraction during the scraping: i have the correct number of comments in 'comments' but i've the full comments list only for few post, the most are empty.

```python
PAGES = 3
TIMEOUT = 90
EXTRA_INFO = True
OPTIONS = {"comments": True, "posts_per_page": 100, "reactors": True, "allow_extra_requests": True}
PAGE = "380062975349225"


def scrape_page():
    results = list()
    for post in get_posts(
            account=PAGE,
            pages=PAGES,
            extra_info=EXTRA_INFO,
            timeout=TIMEOUT,
            credentials=(user, pw),
            options=OPTIONS
    ):
        results.append(post)

    return results
```
This is an example of post from the scraping

`{'post_id': '4711949398827206', 'text': 'Coordinamento [...], 
'comments': 37, 
[...]
 'comments_full': [], '}`

This link is a file with the result i've obtained from the previous code: [https://seupload.com/5Ca/scrape_results.txt](url)
I've the same problem also using cookies instead of credentials.

**Comment by neon-ninja** [comment]
Did you get any warnings or errors while scraping? Try:

```python
from facebook_scraper import enable_logging
enable_logging()
```
before running your code and check the debug logs.

Comment extraction for this post works fine for me, the code:

```python
post = next(get_posts(post_urls=[4711949398827206], cookies="cookies.json", options={"comments": True}))
print(post["comments"], len(post["comments_full"]), sum(len(c["replies"]) for c in post["comments_full"]))
```
outputs
```python
37 32 5
```

**Comment by Ianneee** [comment]
Hello, i'm trying with enable_logging(), and now seems the problems are when scraping a page if the post is a video and the url change in m.facebook.com/watch, the log return this: "No comments area found".
But if i scrape the post with "post_urls" i can extract the comments without any problem.

I'm stills scraping this page: 380062975349225

```
Got exact timestamp from publish_time: 2021-12-20 19:01:06
Fetching 4806235806065231
[4806235806065231] Extract method extract_video_meta didn't return anything
[4806235806065231] Extract method extract_factcheck didn't return anything
[4806235806065231] Extract method extract_share_information didn't return anything
[4806235806065231] Extract method extract_listing didn't return anything
[4806235806065231] Extract method extract_with didn't return anything
No comments area found
```

```
Got exact timestamp from publish_time: 2021-12-19 20:27:22
Fetching 4801935603161918



[4801935603161918] Extract method extract_video_meta didn't return anything
[4801935603161918] Extract method extract_factcheck didn't return anything
[4801935603161918] Extract method extract_share_information didn't return anything
[4801935603161918] Extract method extract_listing didn't return anything
[4801935603161918] Extract method extract_with didn't return anything
No comments area found
```

But with this one worked (but the url is m.facebook.com/story.php?s [...]):
```
Got exact timestamp from publish_time: 2021-12-19 15:37:14
Fetching 4800847826604029
[4800847826604029] Extract method extract_video_meta didn't return anything
[4800847826604029] Extract method extract_factcheck didn't return anything
4800847826604029 is a share of 1799097546940093
data-ft attribute not found
[4800847826604029] Extract method extract_listing didn't return anything
Fetching up to 5000 comments
```

**Comment by jx3331xx** [comment]
Can u extract the profile id100002233045625 an send it to my email as shown here plz

**Comment by Ianneee** [comment]
> Can u extract the profile id100002233045625 an send it to my email as shown here plz

I think you can do it by yourself downloading this repository on your computer.

**Comment by neon-ninja** [comment]
> Can u extract the profile id100002233045625 an send it to my email as shown here plz

What are you trying to extract? All of his public posts?

**Comment by neon-ninja** [comment]
@Ianneee I think https://github.com/kevinzg/facebook-scraper/commit/db3c117508cbee27b48190947bedf855b2b16166 should fix the issue with video posts redirecting to /watch/. Please give it a try when convenient and let me know if it works for you

**Comment by Ianneee** [comment]
> @Ianneee I think [db3c117](https://github.com/kevinzg/facebook-scraper/commit/db3c117508cbee27b48190947bedf855b2b16166) should fix the issue with video posts redirecting to /watch/. 
>...
> Please give it a try when convenient and let me know if it works for you.

The logger says "No comments area found" but the comments are correctly extracted, so it works! Thanks!
