### ISSUE TITLE
Some of the ‘time’ crawled by get_post is not displayed

### ISSUE THREAD

**Issue by JJery-web** [kevinzg/facebook-scraper#613]
Hi. I use the get_posts function but I just get some of the results of '**time**'. And some results are " "(Null). How can I deal with it.
Thanks!

**Comment by JJery-web** [comment]
Like this:

Number Time  Post
1  2019/3/2    "XXXXXXX"
2  2019/2/28    "XXXXXXX"
**3                     "XXXXXXX"**
4  2019/2/1    "XXXXXXX"

I find the third one 'time' result is nothing.

**Comment by neon-ninja** [comment]
Try set your Facebook language to English and re-export your cookies

**Comment by JJery-web** [comment]
> Try set your Facebook language to English and re-export your cookies

I see. Thanks!
