### ISSUE TITLE
facebook_scraper.exceptions.TemporarilyBanned: You’re Temporarily Blocked

### ISSUE THREAD

**Issue by JJery-web** [kevinzg/facebook-scraper#614]
Sorry. I use the facebook-scraper, but maybe the requests are a lot. And now it is showing that **'facebook_scraper.exceptions.TemporarilyBanned: You’re Temporarily Blocked'**

How can I deal with it please. Use proxy? Or use different cookies?

（I use the function of 'get_posts'）

**Comment by neon-ninja** [comment]
You're making too many requests - try add in some `time.sleep(60)`

**Comment by JJery-web** [comment]
> You're making too many requests - try add in some `time.sleep(60)`

Thanks!
