### ISSUE TITLE
get_page_info returning.... something weird

### ISSUE THREAD

**Issue by brandon-scott-pritchard** [kevinzg/facebook-scraper#618]
Hi! Happy New Year!

I've been running this program on an Anaconda-based 3.8.3 interpreter, and it works perfect. I set up a new environment on a new computer (Anaconda-based 3.9.7 interpreter) (only thing I can figure it can be), and running get_page_info ends up breaking the "about:" return so much that it doesn't even register as JSON. The terminal also logs "No ld+json element", and then it fails.

Any ideas?

Thank you for this great program!

**Comment by neon-ninja** [comment]
Try pass cookies

**Comment by brandon-scott-pritchard** [comment]
I do. I've also installed the latest master.

**Comment by neon-ninja** [comment]
Try update lxml `pip install -U lxml`

**Comment by brandon-scott-pritchard** [comment]
That did the trick. Thank you!
