### ISSUE TITLE
Loop over user id's

### ISSUE THREAD

**Issue by potterthecop** [kevinzg/facebook-scraper#631]
Hello!

Kevin, i'm using your code right here, which works brilliant:

set_cookies("cookies.json")

#Using m.facebook.com style
posts = list(get_posts("user ID", options={"allow_extra_requests": False}))
print(f"Got {len(posts)} posts, with {sum(p['comments'] for p in posts)} total comments")
#Using mbasic.facebook.com style
set_noscript(True)
posts = get_posts(post_urls=[p["post_id"] for p in posts], options={"comments": True})
for post in posts:
    print(post["post_id"])
    for comment in post["comments_full"]:
        print(comment["comment_time"])
    break

# But i have a question. How can I manage to loop over user id's?
I have tried this:

lista_postari=[]
lista_id_postari=[]
lista_comm=[]

usrid = ["user1", "user2", "user3"]
for usr in usrid:

    time.sleep(20)
    posts = list(get_posts(usr, pages=200, options={"allow_extra_requests": False, "reactors": True, 'posts_per_page': 200}))
    for p in posts:
        lista_postari.append(p)
    pd.DataFrame(lista_postari).to_csv(r"C:\Users\path_Posts" + usr + ".csv", index=False)

    # Using mbasic.facebook.com style
    set_noscript(True)

    posts = get_posts(post_urls=[p["post_id"] for p in posts], options={"comments": True})

    for post in posts:
        lista_id_postari.append(post["post_id"])
        lista_comm.append(post["comments_full"])

    df_lista_id_postari = pd.DataFrame(lista_id_postari)
    df_lista_comm = pd.DataFrame(lista_comm)
    df_lista_comm_T = df_lista_comm.T

    df_lista_id_postari.reset_index(drop=True, inplace=True)
    df_lista_comm_T.reset_index(drop=True, inplace=True)

    pd.concat( [df_lista_id_postari, df_lista_comm_T], axis=1).to_csv(r"C:\Users\path_Comm_" + usr + ".csv", index=False)

    
    print(f"Done with {usr}")

But i keep getting the data from my first user.

A little help here?

Thanks!

**Comment by neon-ninja** [comment]
Call `set_noscript(False)` after the comment extraction is complete.
