### ISSUE TITLE
comments are not downloaded

### ISSUE THREAD

**Issue by msaljoug** [kevinzg/facebook-scraper#632]
The posts'  comments (```comments_full``` which I assume is the actual comments rather than their count) are not pulled. below is my code:

```
from facebook_scraper import get_posts
options={"comments": True}
options={"reactors": True}
options={"allow_extra_requests": True}
options={"posts_per_page": 200}
posts = []
for post in get_posts('TwiddyOuterBanks', pages=1, cookies="cookies.json",extra_info = True):
    posts.append(post)
    print(post['comments_full'])
```

**Comment by neon-ninja** [comment]
You need to pass options in `get_posts`. Like so: `get_posts('TwiddyOuterBanks', pages=1, cookies="cookies.json",extra_info = True, options = {"comments" :True}) `
