### ISSUE TITLE
No comments found on page

### ISSUE THREAD

**Issue by Avibek** [kevinzg/facebook-scraper#634]
Hi guys,
I'm not sure it's an issue, so I'll let you decide.
Trying to get all comment from a post with 30K of them..I'm successfully faching ~9k comments and then getting "No comments found on page" warning.
I have tried  to continue from the last URL with "comment_start_url" option but getting the same warning.

`for post in get_posts('Carnivorans', pages=1, options={"comments": True,"allow_extra_requests": True, "progress": True, 'comment_start_url': 'https://m.facebook.com/story.php?story_fbid=1608121936208713&id=189917291362525&p=9900'}, credentials=('***', '***')):
    print(post)`
    

Thanks!

**Comment by neon-ninja** [comment]
Look at https://m.facebook.com/story.php?story_fbid=1608121936208713&id=189917291362525&p=9900 in your browser, there's no comments there. You've got all of the comments. Note that the comment count includes replies, whereas `len(post["comments_full"])` only gives you the count of top level replies

**Comment by Avibek** [comment]
There are 3.5m comments including replies,
top level comments count is 35k:

Fetching up to 35000 comments
  1%|          | 360/35000
  
I think that facebook blocking requests for old comments.

**Comment by neon-ninja** [comment]
A lot of those comments are spam, so would be suppressed for being spam.

![image](https://user-images.githubusercontent.com/3378822/149831544-051075be-df06-499f-84c5-e3ea204d3cf2.png)
