### ISSUE TITLE
Missing post time in group post

### ISSUE THREAD

**Issue by salamtamp** [kevinzg/facebook-scraper#64]
The group data don't have a "post_time" field (return None). I fixed and pull request to your repo on #63

**Comment by kevinzg** [comment]
Thanks. I added it to the prerelease version 0.2.2a0.

**Comment by salamtamp** [comment]
> Thanks. I added it to the prerelease version 0.2.2a0.

Thank you, I cannot format the post time to datetime object, because the response data that return string format (eg. Yesterday, 1 days ago) 😭😥.
