### ISSUE TITLE
Proxies support

### ISSUE THREAD

**Issue by vlzinch** [kevinzg/facebook-scraper#65]
Hi!
Cannot find proxy support in the library, am I wrong?

Regards,
Vlad

**Comment by kevinzg** [comment]
The library uses [requests](https://requests.readthedocs.io/en/master/) under the hood which supports [proxies](https://requests.readthedocs.io/en/master/user/advanced/#proxies).

In version `0.1.*` you can create the `facebook_scraper._session` object before calling `get_posts` and then set the `proxies` member of the session as the requests documentation shows.

In version `0.2.*` you can either pass the session object to the `FacebookScraper` or pass the proxies on the `request_kwargs` argument.

https://github.com/kevinzg/facebook-scraper/blob/5a2d61fda5228ea429a82b4ae4d5330021088334/facebook_scraper/facebook_scraper.py#L34-L43
