### ISSUE TITLE
Members of a Public Group

### ISSUE THREAD

**Issue by RobertAlan** [kevinzg/facebook-scraper#653]
Is there a CLI solution to quickly grab members info from a public group?

I imagine this as something similar to the --friends argument for profiles.

Something like:
facebook-scraper --filename test.json --format json  --group group-name --members 1000

Thank you!

**Comment by RobertAlan** [comment]
Please disregard. I found my answer here https://github.com/kevinzg/facebook-scraper/issues/305#issuecomment-851778770

**Comment by RobertAlan** [comment]
Maybe not. Is there a CLI argument for get_group_info?

**Comment by neon-ninja** [comment]
Like I mentioned in https://github.com/kevinzg/facebook-scraper/issues/305, m.facebook.com only lets you see up to 116 public group members. So it wouldn't be possible to extract 1000 members.

**Comment by RobertAlan** [comment]
Thank you.
