### ISSUE TITLE
Couldn't get any posts

### ISSUE THREAD

**Issue by TheGennesis** [kevinzg/facebook-scraper#654]
Hi, I started using this repo a few days ago. That's very useful, so first of all, thank you!

But, I noticed that for certain public pages, I got the same output for different commands.
Command: 
`facebook-scraper -f coldplay.json -fmt json --encoding utf-8 coldplay`
Output:
`"Couldn't get any posts."`
wheter I'm logged in or not to Facebook from my browser (Chrome).

I tried to switch browser too (Opera, Firefox), but nothing happens.  
Do I have to pass either cookies or credentials? Is there no alternative way to do this?

**Comment by neon-ninja** [comment]
The scraper won't try use your browser cookies unless you tell it to. Try `-c "from_browser"`

**Comment by TheGennesis** [comment]
Oh ok, I thought there was a relationship between script and browser used, I was wrong.

And about the option 
`-c "from_browser"` 
I notice that it uses the "browser_cookie3" library that, for some reasons, fails to load cookies if you not pass a cookies file. 

Moreover, using the command above, both in command line:
`facebook-scraper -f coldplay.json -fmt json --encoding utf-8 -c "from_browser" coldplay`

and in a py script: 
```
page = "coldplay"
with open ("{:s}.json".format(page), "w") as f:
    for post in get_posts(page, cookies="from_browser"):
        json.dump(post)
```

I got the same output:
 `facebook_scraper.exceptions.InvalidCookies: Cookies are not valid`.
I'm actually logged in.

**Comment by neon-ninja** [comment]
Try extract your cookies to a file, as per the README then. Perhaps browser_cookie3 is getting your various browsers (Chrome, Opera, Firefox) mixed up

**Comment by TheGennesis** [comment]
I forgot to answer.
So, this repo works great for my tasks. I found another way to solve my problem, that was not so related to your repo, but kind of.

Thank you for answering, You can close the issue!
