### ISSUE TITLE
Can't install Wheel for lz4 console error

### ISSUE THREAD

**Issue by HammerCod** [kevinzg/facebook-scraper#668]
hi, thanks you for this great tool for facebook scraping.

i've a issue while i tried to install facebook-scraper in console, i got this.

Building wheels for collected packages: lz4
  Building wheel for lz4 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Bryan Silva\anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Bryan Silva\\AppData\\Local\\Temp\\pip-install-ynt3z5l2\\lz4_ac39af79c580460197b7ad5ca6ff1af8\\setup.py'"'"'; __file__='"'"'C:\\Users\\Bryan Silva\\AppData\\Local\\Temp\\pip-install-ynt3z5l2\\lz4_ac39af79c580460197b7ad5ca6ff1af8\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Bryan Silva\AppData\Local\Temp\pip-wheel-0i5ed3_m'
       cwd: C:\Users\Bryan Silva\AppData\Local\Temp\pip-install-ynt3z5l2\lz4_ac39af79c580460197b7ad5ca6ff1af8\
  Complete output (17 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\lz4
  copying lz4\version.py -> build\lib.win-amd64-3.9\lz4
  copying lz4\__init__.py -> build\lib.win-amd64-3.9\lz4
  creating build\lib.win-amd64-3.9\lz4\block
  copying lz4\block\__init__.py -> build\lib.win-amd64-3.9\lz4\block
  creating build\lib.win-amd64-3.9\lz4\frame
  copying lz4\frame\__init__.py -> build\lib.win-amd64-3.9\lz4\frame
  creating build\lib.win-amd64-3.9\lz4\stream
  copying lz4\stream\__init__.py -> build\lib.win-amd64-3.9\lz4\stream
  running build_ext
  building 'lz4._version' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for lz4
  Running setup.py clean for lz4
Failed to build lz4

**Comment by neon-ninja** [comment]
This commit (https://github.com/kevinzg/facebook-scraper/commit/b4efc6c9164a3f166232660756af0e5a188ed95b), published in [v0.2.53](https://github.com/kevinzg/facebook-scraper/releases/tag/v0.2.53), makes browser-cookies3 an optional dependency, thus making lz4, and a C++ compiler, optional as well. Try `pip install facebook-scraper==0.2.53`

**Comment by HammerCod** [comment]
I've solved it installing Microsoft C++ build tools, thanks you buddy
