### ISSUE TITLE
time is not properly formatted from posts into into posts for groups

### ISSUE THREAD

**Issue by crroush** [kevinzg/facebook-scraper#67]
Time for posts from the current year do not include the current year in the post.  They are in the format of **May 29 at 1:35** 

The code is expecting you provide the year.
Second issue is for recent post they are relative to "current" time.  They show up as 2 mins or 4 hrs
I am fixing it locally on my version, I am not sure if you accept merge requests etc.

**Comment by kevinzg** [comment]
Yeah, a fix for that would be great!

**Comment by kevinzg** [comment]
Fixed with #135
