### ISSUE TITLE
Maltego version for Facebook scraper

### ISSUE THREAD

**Issue by potterthecop** [kevinzg/facebook-scraper#672]
Hello, Kevin!

Do you think that in the near future you could create a version of facebook scraper to integrate in Maltego, like the versions of Megadose user, here on github?

Thanks!

**Comment by neon-ninja** [comment]
Maltego isn't free software (https://www.maltego.com/pricing-plans/). The community version seems very limited, more like a trial version. This would be a barrier to both development and usage.
