### ISSUE TITLE
The library doesn't seem to extract all the comments

### ISSUE THREAD

**Issue by wahabaftab** [kevinzg/facebook-scraper#678]
Hi,
I am trying to run the following code and it extracts the comments and replies but the total comment count is larger than the sum of comments and replies extracted. Any reason why this is happening?

```
for post in get_posts('zongers', cookies='facebook_cookies.txt', extra_info=False, pages=30, options={"comments": True}):
    post_entry = post
    print('Actual num of comments:', post['comments'])
    print('Comments + replies:', len(post['comments_full']) + sum(len(c["replies"]) for c in post["comments_full"]))
```
```
Actual num of comments: 608
Comments + replies: 344
```

**Comment by wahabaftab** [comment]
I have checked and it seems it's only extracting the "most relevant" comments and not all the comments.

**Comment by neon-ninja** [comment]
It isn't possible to choose between "most relevant" or "all comments" on m.facebook.com AFAIK, only on facebook.com.

**Comment by wahabaftab** [comment]
I don't wanna choose, I just wanna extract all of them but that code doesn't do it, any ideas why?

**Comment by neon-ninja** [comment]
The scraper uses m.facebook.com. It's limited by the features available on m.facebook.com. This feature isn't available on m.facebook.com.

**Comment by wahabaftab** [comment]
Thanks that explains it.
