### ISSUE TITLE
json.decoder.JSONDecodeError: Extra data: line 1 column 4002 (char 4001)

### ISSUE THREAD

**Issue by tiln7** [kevinzg/facebook-scraper#68]
I am getting this error. Never happened before.

json.decoder.JSONDecodeError: Extra data: line 1 column 4002 (char 4001)

**Comment by kevinzg** [comment]
Please try with version 0.2.2a3 and enabling logging with
`enable_logging(level=logging.DEBUG)` and post back the results.

**Comment by neon-ninja** [comment]
@tiln7 are you still getting this error? If so, on which post?

**Comment by neon-ninja** [comment]
https://github.com/kevinzg/facebook-scraper/commit/caf89d711d187a6c33330efb6ef695dd45271cb4 should fix this

**Comment by MohammedNagdy** [comment]
I got this issue as well after it was working totally fine. I tried different versions. But there is no success.

**Comment by neon-ninja** [comment]
What code causes this error?

**Comment by MohammedNagdy** [comment]
The get posts function. I am not sure if it's an error triggered by the colab notebook I was using or what.

**Comment by neon-ninja** [comment]
With what arguments?
