### ISSUE TITLE
cannot get reactions

### ISSUE THREAD

**Issue by mgljinchin** [kevinzg/facebook-scraper#69]
Getting reactions is not working anymore.

**Comment by alejandrohdo** [comment]
It also throws me without reactions, even though I passed the **extra_info** parameter

**Comment by AlexCachia** [comment]
I also tried to run it with extra_info and it doesn't return the reactions :/

**Comment by FelipeAmaral13** [comment]
I had the same problem. I pass the extra_info = True parameter, but request more than 100 pages and do not return the reactions. Only returns with value of pages> = 10.

**Comment by ebergam** [comment]
Anyone has news on this? It seems like there is an amount of requests after which the reactions aren't yielded anymore.

**Comment by balazssandor** [comment]
Reactions are not collected usually. They are rarely present.

**Comment by neon-ninja** [comment]
Try with the latest version, this should be fixed now
