### ISSUE TITLE
Feature Request - Video 

### ISSUE THREAD

**Issue by Sarun1001** [kevinzg/facebook-scraper#7]
### Is it possible to provide video support with a post type parameter like in the original graph api
eg  ` 'type': video,` 
      `'source_url': link,`
Thank you

**Comment by andcha** [comment]
It would be awesome to have a link to the post's attached video.

**Comment by kevinzg** [comment]
We got video support in #74 
Try it with version 0.2.3a0 `pip install facebook-scraper==0.2.3a0`
