### ISSUE TITLE
Cannot get more than 20 posts !

### ISSUE THREAD

**Issue by widedM** [kevinzg/facebook-scraper#70]
Hi, im trying to get posts from some Facebook groups using this library but it **didn't gave me more than 20 posts** i don't know why !
for example:
```
 for post in get_posts(group=1024840684234688, pages=10):
    print(post)
```
=> The output: **20 posts only and usually** even that i putted pages=1 or pages=10

**Comment by kevinzg** [comment]
It seems your group is private, have you tried with using the login option?

**Comment by widedM** [comment]
It doesn't work with private groups. All the groups are public. I tried but
it doesn't work !

**Comment by neon-ninja** [comment]
```python
print(get_group_info("1024840684234688"))
```
returns
```python
{'id': '1024840684234688', 'name': 'Vente Pc Portable / Gamer / Fix', 'type': 'Private group', 'members': 51032}
```
This group is private. You would need to pass cookies to access it.
