### ISSUE TITLE
attempted relative import with no known parent package

### ISSUE THREAD

**Issue by pvita** [kevinzg/facebook-scraper#71]
Hi there,
I'm getting this error when I try to launch facebook.scraper.py

Can you help me?

> Traceback (most recent call last):
>   File "C:\Users\x\Downloads\facebook-scraper-master\facebook-scraper-master\facebook_scraper\facebook_scraper.py", line 10, in <module>
>     from . import utils
> ImportError: attempted relative import with no known parent package
>

**Comment by kevinzg** [comment]
Can you tell me your Python version and how are you launching the script?

**Comment by pvita** [comment]
Python 3.8 and I'm simply launching the module facebook_scraper.py

**Comment by kevinzg** [comment]
Try doing `python -m facebook_scraper` from your `C:\Users\x\Downloads\facebook-scraper-master\facebook-scraper-master` directory.

**Comment by pvita** [comment]
Thank you kevinzg, now it is working fine.
Just another question: why it doesn't work with groups? 
I tried this command

"python -m facebook_scraper -f prova.csv -p 100 groups/pomiglianodarco"

Feedback:
Couldn't get any posts.

Moreover, is there any chance to get comments?

Best

**Comment by kevinzg** [comment]
There wasn't an option for groups, I just added one, update your repo and do this:

`python -m facebook_scraper -f prova.csv -p 100 --group pomiglianodarco`

However scraping from groups is not stable right now, see #70 or #67.
There isn't comments scraping at this moment.

**Comment by neon-ninja** [comment]
As of https://github.com/kevinzg/facebook-scraper/pull/188 comment scraping is possible

**Comment by rjaxx-0900** [comment]
I am now having this issue and the method suggested above is not fixing it. Here is what the error generates:

MacBook-Pro:facebook_scraper redacted$ python __main__.py
Traceback (most recent call last):
  File "/Users/redacted/Documents/GitHub/facebook-scraper/facebook_scraper/__main__.py", line 10, in <module>
    from . import enable_logging, write_posts_to_csv, get_profile
ImportError: attempted relative import with no known parent package

Any ideas? Thanks!

**Comment by neon-ninja** [comment]
`__main__.py` isn't intended to be run in this manner. What are you trying to do?

**Comment by rjaxx-0900** [comment]
Whoops. Not sure what happened, there. This is what I intended to paste (I attempted to run the program using the example provided by the developer):

MacBook-Pro:facebook_scraper [REDACTED]$ python facebook_scraper.py --filename nintendo_page_posts.csv --pages 10 nintendo
Traceback (most recent call last):
  File "/Users/[REDACTED]/Documents/GitHub/facebook-scraper/facebook_scraper/facebook_scraper.py", line 17, in <module>
    from . import utils
ImportError: attempted relative import with no known parent package
MacBook-Pro:facebook_scraper [REDACTED]$ 

Honestly, just trying to get this thing running...

**Comment by neon-ninja** [comment]
Try run it from the parent directory

**Comment by rjaxx-0900** [comment]
Not sure if this helps, but here's the folder structure:

<img width="814" alt="Screen Shot 2022-09-01 at 4 40 16 PM" src="https://user-images.githubusercontent.com/112218066/188008794-6fa988d6-96d6-4c45-ad12-a79357a42495.png">

**Comment by DianaInka** [comment]
How did you get it running?
