### ISSUE TITLE
pages and posts_per_page seem to have no effect on user pages

### ISSUE THREAD

**Issue by curiousier-george** [kevinzg/facebook-scraper#717]
The parameters `pages` and `posts_per_page` of `get_posts()` seem to have no effect when getting posts from user pages. I'm not sure whether this is new behavior or not.

**Comment by curiousier-george** [comment]
Got confused while trying to track everything down - I already knew this and had reported it.

**Comment by neon-ninja** [comment]
This was discussed in https://github.com/kevinzg/facebook-scraper/issues/660
