### ISSUE TITLE
Cannot get more than 10 posts

### ISSUE THREAD

**Issue by tanmayjain69** [kevinzg/facebook-scraper#72]
I am trying to scrape one Facebook page which is public but cannot get more than 10 posts. I have tried it page numbers ranging from (1-10). It is working fine for some pages but giving error with this page.
```
for post in get_posts('memes', pages=100):
    print(post)
```

**Comment by kevinzg** [comment]
One of the pages is sending a 500 status but when using curl it is working just fine, that's weird.

**Comment by tanmayjain69** [comment]
Also, when I try it at different times, it gives me a different number of posts but a constant number for any number of pages.

**Comment by tanmayjain69** [comment]
> One of the pages is sending a 500 status but when using curl it is working just fine, that's weird.

I have also tried using sleep but it is not working. I am not getting how come it is working fine for other pages.

**Comment by neon-ninja** [comment]
```python
print(len(list(get_posts('memes', pages=10, timeout=60, options={"allow_extra_requests": False, "posts_per_page": 200}))))
```
returns 1802, so this seems fixed
