### ISSUE TITLE
Is there a way to list the profiles who reacted on a post?

### ISSUE THREAD

**Issue by eyalgolan** [kevinzg/facebook-scraper#722]
Tried doing the following:
`get_posts(post_urls=["https://www.facebook.com/<>/posts/<>/"], cookies="cookies.txt", extra_info=True, options={"reactors": True}).__next__()`

The result contained the number of reactions: `'reactions': {'like': 508, 'love': 12, 'haha': 148, 'care': 12, 'sad': 810, 'angry': 6}, '` but I want to list the people who reacted per reaction (how many people reacted with 'haha', for example).

Is that possible?

**Comment by neon-ninja** [comment]
The reactors would be under the `reactors` key, not `reactions`

**Comment by eyalgolan** [comment]
Running `pip uninstall `facebook-scraper` and then `pip install git+https://github.com/kevinzg/facebook-scraper.git` fixed this for me.
