### ISSUE TITLE
Text (caption) from scrapped posts is messy. How to get only the text or caption of each post? 

### ISSUE THREAD

**Issue by satriosadewo** [kevinzg/facebook-scraper#729]
Hi, 

I succeeded to scrap the posts from a public page (UNICEF). But, when I check the data, especially every cell in the text, post_text, and share_text column, the results are very messy. It also contains other text, characters, attributes, or captions of some next posts. 
Below is my code:

`post_df_full = pd.DataFrame(columns = [])`

````
for post in get_posts('unicef', cookies='cookies.txt', extra_info=True, pages=4):
    
    post_entry = post
    fb_post_df = pd.DataFrame.from_dict(post_entry, orient='index')
    fb_post_df = fb_post_df.transpose()
    post_df_full = post_df_full.append(fb_post_df)
    print(post['post_id']+' get')
````
`post_df_full`

At this point, I can scrape. But, when I check the first cell in the text column, 
```
text = post_df_full['text']
text.iloc[1,]
```
this is the result:

`'Climate change is here - and it\'s impacting children like this little one in Nicaragua, whose home was destroyed in a hurricane.\nGovernments must urgently increase investment in child-centred climate adaptations plans.\nThrough climate change, conflicts and COVID-19, UNICEF won\'t stop until we build a safe and sustainable future #ForEveryChild.\n1.5K\n33 Comments63 Shares\nLike\nShow more reactions\nComment\nShare\nLoading...\nTry Again\nCancel\nLoading...\nLoading...\nMPageLoadClientMetrics.logFirstPaint(true);requireLazy(["HasteSupportData"],function(m){m.handle({"gkxData":{"5241":{"result":true,"hash":"AT7o1bCQPGpf3ShEHQo"},"5919":{"result":false,"hash":"AT6PGptIPUYH051BPNw"},"676920":{"result":false,"hash":"AT497IX4gOFG8gZe_l0"},"708253":{"result":false,"hash":"AT5n4hBL3YTMnQWtlxE"},"996940":{"result":false,"hash":"AT7opYuEGy3sjG1auCU"},"1263340":{"result":false,"hash":"AT5bwizWgDaFQudmYxg"}}})});requireLazy(["TimeSliceImpl","ServerJS"],function(TimeSlice,ServerJS){(new ServerJS()).handle({"define":[["cr:696703",[],{"__rc":[null,"Aa0VRKXXeLP3Q26ktaBO0JWoS1HmNx6birBq98HRur2vhSUddgIgTM_PdHf474-0zVqfj54HLblWO1b3SAZkRnuL4sw"]},-1],["cr:717822",["TimeSliceImpl"],{"__rc":.....................................................'`

The actual text according to the Facebook page is like this:
**Climate change is here - and it's impacting children like this little one in Nicaragua, whose home was destroyed in a hurricane.
Governments must urgently increase investment in child-centred climate adaptations plans.
Through climate change, conflicts and COVID-19, UNICEF won't stop until we build a safe and sustainable future #ForEveryChild**

How to remove unnecessary text/character after a caption? so I will get only the caption (like in actual text above) of each post.

Thank you in advance to help me

**Comment by neon-ninja** [comment]
Try set your Facebook language to English
Try update lxml with `pip install -U lxml`

**Comment by satriosadewo** [comment]
> 

AMAZING! it works! Thank you so much, Nick!
