### ISSUE TITLE
no date for group posts

### ISSUE THREAD

**Issue by anyharris** [kevinzg/facebook-scraper#73]
Hello. Is the fix for getting group post dates still working? I always get `'time': None`

I am using python 3.8 and have tried the pypi build 0.2.2a0 (mentioned in #64) as well as the latest pypi release 0.2.2a3. I copied over the code from TestGetGroupPosts and get an AssertionError when I run it.

**Comment by kevinzg** [comment]
The fix didn't work for recent posts because the display format variates and the date parser isn't handling those formats. See #67.

**Comment by mellanon** [comment]
@kevinzg I implemented a fix to this over the weekend. It's using the same code as the page post date extractor. I ran the code over a large data set and it's working. Any reason why the approach is different between pages and groups?

**Comment by kevinzg** [comment]
Fixed with #135
