### ISSUE TITLE
Use url from request_url_callback raise error

### ISSUE THREAD

**Issue by Ianneee** [kevinzg/facebook-scraper#754]
I'm using the url from `request_url_callback` to continue scraping from the last position before ban but when i give it to `start_url` it raise a 500 error from fb.
The url i'm trying to use is this:
`https://m.facebook.com/page_content_list_view/more/?page_id=2275271592719723&start_cursor={"timeline_cursor":"AQHRhyEsClCGstBkqI-g0JAACe_YOdftWoJ-VPgEWwjgfr3U8vL-u4N5-BzHbRbfGioR0WozETGhhVferyGqYvi9iX4SYv0XNIAMv5P6PWg204C7zpYzSCfkIs25UmB1muns","timeline_section_cursor":null,"has_next_page":true}&num_to_fetch=50&surface_type=posts_tab`

and i'm receiving this error:
```python
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://m.facebook.com/page_content_list_view/more/?page_id=2275271592719723&start_cursor=%7Btimeline_cursor:AQHRhyEsClCGstBkqI-g0JAACe_YOdftWoJ-VPgEWwjgfr3U8vL-u4N5-BzHbRbfGioR0WozETGhhVferyGqYvi9iX4SYv0XNIAMv5P6PWg204C7zpYzSCfkIs25UmB1muns,timeline_section_cursor:null,has_next_page:true%7D&num_to_fetch=50&surface_type=posts_tab&locale=en_US
```

**Comment by neon-ninja** [comment]
What happens if you put that URL in your browser? It works fine in my browser

**Comment by Ianneee** [comment]
I can open it from the browser.
Checking the error i see there's `&locale=en_US` at the end of the url that is automatically added in some point of the request.

**Comment by Ianneee** [comment]
The problem are the doubles quotes, adding `\` before them solve the issue.
Thanks for your time.

**Comment by neon-ninja** [comment]
I see - as an alternative, you can use single quotes
