### ISSUE TITLE
Set user-agent from facebook-scraper CLI

### ISSUE THREAD

**Issue by TheodoreDA** [kevinzg/facebook-scraper#758]
I just started reading this project's documentation, and I wanted to fetch the last post of a group.
I wanted to try with the CLI, to get me an idea of how this project can be used. I kept running into the 

> Unsupported Browser

error. I started reading the code of the project, and saw where the default user-agent was set ([here](https://github.com/kevinzg/facebook-scraper/blob/f17d144a6cda05499c49104f85b18580467be8fa/facebook_scraper/facebook_scraper.py#L53)).
And with witch function I can override the user-agent ([here](https://github.com/kevinzg/facebook-scraper/blob/f17d144a6cda05499c49104f85b18580467be8fa/facebook_scraper/__init__.py#L63)).

Question is, can I override the user-agent by default from the CLI, as I am not using MacOS ?

**Comment by neon-ninja** [comment]
`Unsupported Browser` is just a warning, not an error. Did you still get posts extracted?

**Comment by TheodoreDA** [comment]
Sorry for the late reply. Yes, it still work, I didn't saw that it was only a warning
