### ISSUE TITLE
'NoneType' object has no attribute 'find' met

### ISSUE THREAD

**Issue by Sabutobi** [kevinzg/facebook-scraper#77]
Hi,all.
My code is:
```
from facebook_scraper import get_posts
for post in get_posts(account='PfleidererGroup'):
    print(post['text])
```
Problem is `'NoneType' object has no attribute 'find'`
I met this issue not on only one profile.
Maybe you'll have some ideas about how to resolve that.
Thanks a lot for your attention to my post.

**Comment by kevinzg** [comment]
Try with latest version (0.2.3) and enabling logging:
```python
import logging
from facebook_scraper import get_posts, enable_logging

enable_logging(logging.DEBUG)
list(get_posts(account='youraccount'))
```

**Comment by Sabutobi** [comment]
Hi @kevinzg 
I used default version defined in pip. Version 0.1.12.
After I've upgraded to 0.2.3 - all works fine. Thanks a lot for your help.

**Comment by Sabutobi** [comment]
Issue is resolved I'll close this ticket if you don't mind.
