### ISSUE TITLE
Can we get multiple posts data instead of latest single post in get_posts()

### ISSUE THREAD

**Issue by MukhlisRaza** [kevinzg/facebook-scraper#770]
Hi!
I am able to get the latest post on the page but I want to get all or more than 1 post data when I enter the page name into the get_posts() method. How do achieve this?? 
Can we achieve this with get_posts() or any other method?

Thanks in advance

**Comment by neon-ninja** [comment]
Try pass cookies as per the readme

**Comment by MukhlisRaza** [comment]
Returned the most recent record to me again as I pass cookies also. I have a cookies.txt file in the same directory and have data from the get cookies extension. In the below image, you can see a single post record. You can also check the below code
![post](https://user-images.githubusercontent.com/68111775/171780948-91678a01-bff0-4dc4-869d-f676a83e515e.PNG)

**Code**
from typing import Union
from fastapi import FastAPI
from facebook_scraper import get_posts
app = FastAPI()

@app.get("/")
def read_root():
    return {"Hello": "World"}

@app.get("/{page_id}")
def scrap_item(page_id: str):
    for post in get_posts(page_id, pages=2, cookies='cookies.txt', options={"posts_per_page": 20}):
        return {"posts": post}

**Comment by neon-ninja** [comment]
I'm unable to reproduce this problem. The code:

```python
print(len(list(get_posts("Bata", pages=2, cookies='cookies.json', options={"posts_per_page": 20, "allow_extra_requests": False}))))
```
outputs `21` for me

**Comment by MukhlisRaza** [comment]
Thanks @neon-ninja I got the point
