### ISSUE TITLE
scraping limitations

### ISSUE THREAD

**Issue by AcidkoHorkaCokolada** [kevinzg/facebook-scraper#771]
Hi Everyone,

what comments can be scrapped? its seems im able to get only most relevant comments without full threads(replies)

**Comment by dihiaselma** [comment]
I have the same problem. I released that I can't scrape all the comments and replies of a page.
I have also another issue: when I specify the cookies.txt file in get_posts, I can gather just the posts (no comments returned). 
I used cookies.txt chrome extension to generate the cookies file.  
Please anyone to explain us how to generate the right cookies.txt, and how to use it to expand the data to extract ?

**Comment by neon-ninja** [comment]
@AcidkoHorkaCokolada The scraper uses m.facebook.com, so it's limited by the functionality available there. As such, only most relevant comments are available. RE: missing replies, this looks like a duplicate of https://github.com/kevinzg/facebook-scraper/issues/769, try update lxml with `pip install -U lxml`.

@dihiaselma duplicate of https://github.com/kevinzg/facebook-scraper/issues/764#issuecomment-1148583171, I replied in that issue

**Comment by AcidkoHorkaCokolada** [comment]
thank you
