### ISSUE TITLE
Archive facebook account

### ISSUE THREAD

**Issue by potterthecop** [kevinzg/facebook-scraper#777]
Hello, Kevin!
It is possible to create a functionality to archive a facebook wall profile and save it as Html or Pdf?
Thanks!

**Comment by neon-ninja** [comment]
Sure, you could use requests-html .render() (https://requests.readthedocs.io/projects/requests-html/en/latest/#requests_html.HTML.render) for this. Example:

```python
from facebook_scraper import _scraper
from facebook_scraper import *

set_cookies("cookies.json")
r = _scraper.get("Nintendo")
r.html.render(scrolldown=10, sleep=1)
with open("Nintendo.html", "w") as f:
    f.write(r.html.html)
```

**Comment by potterthecop** [comment]
Thanks, Kevin for the response.
First i encountered an error but i resolved it by adding encoding="utf-8" to this line of code:
`with open("test.html", "w", encoding="utf-8") as f:`

I ran the code again, it generates the html file but when I opened it, i get the **"Allow the use of cookies from Facebook"** message, although i passed the cookies as a json file.
Also i uninstalled / installed the repo and i'm using the latest version.

And i don't know what to do next :)

Thanks for the help!

**Comment by neon-ninja** [comment]
Try click allow

**Comment by potterthecop** [comment]
I tried clicking, nothing happens. 
I'm connecting from Romania, by using a VPN. The account that i want to archive is on Romania also so i don't think it's gdpr related.

When i first run this code i noticed that it downloaded a chromium, on this path: C:\Users\_____\AppData\Local\pyppeteer\pyppeteer\local-chromium\588429\chrome-win32

I don't know if you find this info useful but i shared it anyway :)

**Comment by neon-ninja** [comment]
Try click allow on m.facebook.com I mean, not in your downloaded HTML

**Comment by potterthecop** [comment]
Oh, sorry for that.
I thought about that but i don't know how to show the browser, because it starts hidden. Can you give me a helping hand?
Thanks for all the patience!

**Comment by neon-ninja** [comment]
Can you upload the HTML please?

**Comment by potterthecop** [comment]
Sure, @neon-ninja :
[Sample.zip](https://github.com/kevinzg/facebook-scraper/files/8924796/Sample.zip)

**Comment by potterthecop** [comment]
Any news on this issue, @kevinzg or @neon-ninja ? 
Thanks :)

**Comment by neon-ninja** [comment]
Hmm, looks like `.render()` doesn't pass the cookies like I thought it did. You could try update to the latest master version of requests-html with `pip install git+https://github.com/psf/requests-html.git`, then add in the new `send_cookies_session` argument like so:

```python
from facebook_scraper import _scraper
from facebook_scraper import *

set_cookies("cookies.json")
r = _scraper.get("Nintendo")
r.html.render(scrolldown=10, sleep=1, send_cookies_session=True)
with open("Nintendo.html", "w") as f:
    f.write(r.html.html)
```

**Comment by potterthecop** [comment]
Thanks, @neon-ninja , it worked!!
So first, I uninstalled requests-html and after that I wrote the command pip install git+https://github.com/psf/requests-html.git.
Run the code again and got the profile saved.

Thaks alot!
