### ISSUE TITLE
Couldn't get any posts

### ISSUE THREAD

**Issue by dennisangemi** [kevinzg/facebook-scraper#794]
Hi! Thx for this tool. I launched via cli

```
facebook-scraper -f dennis.csv -p 10 dennisangemi15
```
in order to scrape [my profile](https://facebook.com/dennisangemi15) data but someting went wrong:
```
Couldn't get any posts.
```

Hope this can be fixed ;)

**Comment by neon-ninja** [comment]
Try pass cookies as per the readme

**Comment by dennisangemi** [comment]
Thank u very much! **Sorry** for this question.

Now it **works** ;)

Can I upload my cookies.txt file to github or it contains personal data that shouldn't be published?

**Comment by dennisangemi** [comment]
p.s. maybe u can add the suggestion "Pass cookies" as message in the terminal when someone want to scrape profile data

**Comment by neon-ninja** [comment]
Anyone who has your cookies is essentially logged into your Facebook account, and can make posts or message your friends on messenger. So probably not a good idea to upload your cookies.

**Comment by dennisangemi** [comment]
> Anyone who has your cookies is essentially logged into your Facebook account, and can make posts or message your friends on messenger. So probably not a good idea to upload your cookies.

LOOL, thx for your answer! I won't publish anything haha
