### ISSUE TITLE
Following count of the Public Page seems wrong

### ISSUE THREAD

**Issue by jasonren0403** [kevinzg/facebook-scraper#795]
I am using the 0.2.57 version of facebook-scraper and I want to get the page following & follower stat. 
I just ran the code below
```    
set_user_agent(
        "Mozilla/5.0 (iPhone; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Mobile/15E148 Safari/604.1")
i = get_page_info(account='Reuters', cookies='./cookies_fb.json')
print(i)
```
and the output `i` has got {'Following_count': 53}, instead of `22`.
I got into your source code, and saw that the following count of the page came from the `/{account}?v=following` page, (now redirects to `timeline/app_collection/` page), and by counting all following elements(by css selector '.item[data-sigil="marea"]') of the page, I can get 22 items! The number count is really confusing here.
![FB has wrote '53' items](https://user-images.githubusercontent.com/40999116/177141206-0498bee0-c8b8-453c-b0f5-aa45ae184f22.png)
![but there were '22' items](https://user-images.githubusercontent.com/40999116/177141301-7a2f652f-504c-41dc-8d5d-aee06bfac632.png)

**Comment by neon-ninja** [comment]
![image](https://user-images.githubusercontent.com/3378822/180094046-3e50534c-4b72-449d-8dba-156bdd5bf173.png)
facebook-scraper is reading the number in the top right here, which is 53. Some of the pages Reuters is following must not be public.
