### ISSUE TITLE
Specifying group id on `get_posts_by_search`

### ISSUE THREAD

**Issue by BrianZbr** [kevinzg/facebook-scraper#812]
I'm having trouble getting the group ID parameter on `get_posts_by_search` to work as expected. [The comment on line 305](https://github.com/kevinzg/facebook-scraper/blob/9f184edf4fd726a15d8b33ae9dbd47d670092c9a/facebook_scraper/__init__.py#L305) mentions it, but I don't see the `if` statement I would expect to be handling it. When I try it, I get general results from the search string, nothing from the group I specify. I also tried setting the group with quotes to make it a string even though the code says it should be int.  Am I just doing something wrong here? 

For example, with the correct USERNAME and PASSWORD values: 

``` python
from facebook_scraper get_posts_by_search
for post in get_posts_by_search("pdf", group= 204394701361682, pages=3, credentials=(USERNAME, PASSWORD)):
     print(post['post_id'], post['text']
```

**Comment by neon-ninja** [comment]
`get_posts_by_search` is intended for searching posts across the entirety of Facebook, there's no way to limit it to a specific group. I would recommend using `get_posts` to retrieve all posts, and filtering them yourself

**Comment by BrianZbr** [comment]
> there's no way to limit it to a specific group

So the group argument servers no purpose then, or am I missing something? Perhaps it should be removed, or the comment clarified?

> I would recommend using get_posts to retrieve all posts

I've increased the page limit to 100 but I get back 21 posts every time. How many posts should be possible and how high do I need to increase the page limit? Is there something else I could be doing wrong?

**Comment by neon-ninja** [comment]
Agreed, https://github.com/kevinzg/facebook-scraper/commit/e833d392f5379336afa10f897ee06d0849b5cfe0 should make it clearer

Is 204394701361682 the group you're having this problem with? The code:

```python
posts = list(get_posts(group=204394701361682, pages=3, options={"allow_extra_requests": False}))
print(len(posts))
```
returns 63 for me, with or without cookies. Do you get something different?

**Comment by BrianZbr** [comment]
> https://github.com/kevinzg/facebook-scraper/commit/e833d392f5379336afa10f897ee06d0849b5cfe0 should make it clearer

Indeed it does.

> Is 204394701361682 the group you're having this problem with?

Nope, it's a private group and I just re-read the line in the Readme that says `Group scraping may return only one page and not work on private groups.` so I think that's my answer. 

Closing this out... big thanks as always!
