### ISSUE TITLE
can't get posts from a public page

### ISSUE THREAD

**Issue by LW6EGE** [kevinzg/facebook-scraper#82]
Hi, this is my first issue in a github. I apologize if i didn't followed any rules.

I ran this script (short version) a many times a few weeks ago  and it's worked without problem.
I use google colab.

########
 !pip install facebook-scraper
from facebook_scraper import get_posts

for post in get_posts('/municipiobahia/', pages=1):
   try:
    fecha= post["time"]-datetime.timedelta(hours=3) #ajuste horario -3
   except TypeError: pass 
   #print (fecha)
   posteo= post["text"]
   posteo = posteo.replace('\n', ' ')
   comentarios_n= post["comments"]
   reacciones_total= post["likes"]
   compartidos= post["shares"]
########

but I receive this error

---------------------------------------------------------------------------

gaierror                                  Traceback (most recent call last)

/usr/local/lib/python3.6/dist-packages/urllib3/connection.py in _new_conn(self)
    158         try:
--> 159             conn = connection.create_connection(
    160                 (self._dns_host, self.port), self.timeout, **extra_kw

17 frames

gaierror: [Errno -5] No address associated with hostname

During handling of the above exception, another exception occurred:

NewConnectionError                        Traceback (most recent call last)

NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f08f00ad518>: Failed to establish a new connection: [Errno -5] No address associated with hostname

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)

MaxRetryError: HTTPSConnectionPool(host='pg', port=443): Max retries exceeded with url: /municipiobahia//posts/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f08f00ad518>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)

/usr/local/lib/python3.6/dist-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    514                 raise SSLError(e, request=request)
    515 
--> 516             raise ConnectionError(e, request=request)
    517 
    518         except ClosedPoolError as e:

ConnectionError: HTTPSConnectionPool(host='pg', port=443): Max retries exceeded with url: /municipiobahia//posts/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f08f00ad518>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))

Any ideas? 
Thanks in advance.

**Comment by LW6EGE** [comment]
I have been ""solved"" this problem installing a previous version (0.1.12)  but i don't understand what was the mistake.

**Comment by kevinzg** [comment]
Remove the slashes from `'/municipiobahia/'`

**Comment by LW6EGE** [comment]
it's work fine, Thank you !
