### ISSUE TITLE
continue scraping after temp ban

### ISSUE THREAD

**Issue by RRaphaell** [kevinzg/facebook-scraper#821]
is there any way to continue page scraping after specific post URL

**Comment by jasonren0403** [comment]
[](https://github.com/kevinzg/facebook-scraper/issues/310#issuecomment-852652846)
You may be looking for `request_url_callback`.

**Comment by RRaphaell** [comment]
> [#310 (comment)](https://github.com/kevinzg/facebook-scraper/issues/310#issuecomment-852652846) You may be looking for `request_url_callback` in #310

thanks. I'm pretty new here and I'm interested in what is "page" parameter in get_posts and how many posts are on each "page"? I'm little confused about pages and posts_per_page parameters

**Comment by neon-ninja** [comment]
`pages` tells the scraper how many pages to fetch before terminating. `posts_per_page` defaults to 4, and can be safely increased to ~200 before causing server errors.

**Comment by RRaphaell** [comment]
so page_limit=None and posts_per_page=200 means to scrape infinitely right?

**Comment by neon-ninja** [comment]
Yes
