### ISSUE TITLE
Error in method get_posts when searching by URL_post from Spain

### ISSUE THREAD

**Issue by algarcser** [kevinzg/facebook-scraper#834]
I been searching over the documentation or other issues to see if i could find something similar, but i have not found so. The main problem that i have is when searching over a specific post given a URL with the method get_posts it is not capable of finding such post and it gives me the following error
`HTTPError: 404 Client Error: Not Found for url: https://m.facebook.com/h?locale=en_US`

I think it is related to the locale parameter as the post i am searching is from Spain. I provide the URL of the post i am searching for:  "https://www.facebook.com/32719473447/photos/a.10157360206483448/10159971007903448/"

I could not find another example of the option **post_urls** for the method **get_posts**, so i am not sure if it is because i did not introduce the parameters correctly. 

The following code is what i am executing:
`for post in get_posts(post_urls = "https://www.facebook.com/32719473447/photos/a.10157360206483448/10159971007903448/",
                      credentials=("****", "****"),
                      options={'comments': True, "reactors": True, "allow_extra_requests": True,}):
    print(post)`

I would be really grateful if i could get some guidance as to how to solve this issue.

**Comment by neon-ninja** [comment]
post_urls should be a list, not a single string. Try `for post in get_posts(post_urls = ["https://www.facebook.com/32719473447/photos/a.10157360206483448/10159971007903448/"], credentials=("****", "****"), options={'comments': True, "reactors": True, "allow_extra_requests": True,}): print(post)` instead

**Comment by algarcser** [comment]
Thank you. It was because of that, 
i did not realized that i had to use a list to contain it.
