### ISSUE TITLE
Hey, is everything okay?

### ISSUE THREAD

**Issue by atkinsvh** [kevinzg/facebook-scraper#837]
I was working through the code last night and found it fairly easy to deal with but today none of the code that I wrote is working. Did the module crash or something?

import pprint
from facebook_scraper import get_posts

for x in get_posts("MetroMikeOfficial", pages=10):
         pprint(x)
         
from facebook_scraper import _scraper
from facebook_scraper import *

set_cookies("facebook.com_cookies.txt")
for post in get_posts("UberEU/community"):
    print(post)

    from pprint import pprint
    from facebook_scraper import _scraper
    from facebook_scraper import *
    from facebook_scraper import get_posts
    from facebook_scraper import set_cookies
    import browser_cookie3

    cookies = list(browser_cookie3.chrome())

    set_cookies(cookies)
    for post in get_posts('MetroMikeOfficial', pages=10):
        print(post['text'][:50])

    """
    from facebook_scraper import get_profile
    get_profile("anndrew.watts1", cookies="facebook.com_cookies.txt")

    from facebook_scraper import get_profile
    print(get_profile("anndrew.watts1", cookies="facebook.com_cookies.txt"))

    from pprint import pprint
    from facebook_scraper import _scraper
    from facebook_scraper import *

    set_cookies("facebook.com_cookies.txt")
    for post in get_posts("MetroMikeOfficial", page=10):
        pprint(post['text'][:100])

    from pprint import pprint
    from facebook_scraper import set_cookies
    from facebook_scraper import get_profile
    from facebook_scraper import *

    set_cookies("facebook.com_cookies.txt")
    pprint(get_profile("anndrew.watts1"))

    import pandas as pd
    from facebook_scraper import get_posts
    from facebook_scraper import set_cookies

    set_cookies("facebook.com_cookies.txt")

    d = []
    for post in get_posts("MetroMikeOfficial", pages=10):
        d.append({'time': post['time'], 
                  'post_id': post['post_id'], 
                  'text': post['text'][:20000], 
                  'like':post['likes'], 
                  'comment':post['comments'],
                  'share': post['shares'] , 
                  'URL':post['post_url'], 
                  'link':post['link']})

**Comment by neon-ninja** [comment]
What error are you getting?

**Comment by atkinsvh** [comment]
from facebook_scraper import get_posts
from facebook_scraper import set_cookies
    
set_cookies('cookies.txt')
for post in get_posts("MetroMikeOfficial",cookies="cookies.txt", pages=10):
    print(post['text'][:100])


runs but doesn't print

**Comment by neon-ninja** [comment]
It's working fine for me. Try restart your Python kernel

**Comment by atkinsvh** [comment]
Restarted. Same issue. Will run and not print. I switched to pprint yesterday and that worked but now it is not.
Also,
from facebook_scraper import get_profile
print(get_profile("anndrew.watts1", cookies="cookies.txt"))

returns error 

has_more = self.more_url_regex.search(self.element.html)

AttributeError: 'NoneType' object has no attribute 'html'

**Comment by neon-ninja** [comment]
I already fixed this in https://github.com/kevinzg/facebook-scraper/commit/8fd973b40553e7cb23aef3a86f74f3d3ac973788, try update to the latest master branch

**Comment by atkinsvh** [comment]
I updated earlier tonight and tried again and found the same error message. Also tried the previous content again. I cleaned up the code a little bit after I found #%% sections. 

from pprint import pprint
from facebook_scraper import get_posts
from facebook_scraper import set_cookies
    
set_cookies('cookies.txt')
for post in get_posts("MetroMikeOfficial",cookies="cookies.txt", pages=10):
    pprint(post['text'][:100])
#%%

import pandas as pd
d = []
for post in get_posts("MetroMikeOfficial", pages=10):
    d.append({'time': post['time'], 
              'post_id': post['post_id'], 
              'text': post['text'][:20000], 
              'like':post['likes'], 
              'comment':post['comments'],
              'share': post['shares'] , 
              'URL':post['post_url'], 
              'link':post['link']})

Obj1= pd.DataFrame(d)

#%%
from facebook_scraper import get_profile
print(get_profile("anndrew.watts1", cookies="cookies.txt"))

**Comment by atkinsvh** [comment]
I work for a convention center show series and being able to upload a dictionary of usernames of pages to see everyone's latest posts is very important. Work smarter not harder!
