### ISSUE TITLE
[ERROR] HTTPError: 500 Server Error: Internal Server Error for url

### ISSUE THREAD

**Issue by samsebree** [kevinzg/facebook-scraper#85]
I have been relying on this library for a long time to scrape facebook posts. Woke up to errors today, though I didn't change any code on my end. Running in python 3.8 on AWS lambda.

Receiving:

[ERROR] HTTPError: 500 Server Error: Internal Server Error for url: https://m.facebook.com/page_content_list_view/more/?page_id=PAGE_ID_HERE&start_cursor=%7B%22timeline_cursor%22%3A%22AQHRRU6YdraeL3jqyTfGrkWFfkzU6mdk4efP0SBWEc1XyNP1UsT-yGnhcTZReJKsv60TXkajDGUU583BFmsU4592ZZXDuzVO1dR6zWO7dI-0MowWFDu1RdF2K-2pIzq3hC2L%22%2C%22timeline_section_cursor%22%3Anull%2C%22has_next_page%22%3Atrue%7D&num_to_fetch=4&surface_type=posts_tab

(Where PAGE_ID_HERE is the page ID, it has been changed for privacy)

Made sure to updated facebook-scraper to the latest version (0.2.3), unfortunately the error still throws. 
Here is the stack trace:

  File "/var/task/facebook_scraper/facebook_scraper.py", line 95, in _generic_get_posts
    for i, page in zip(counter, iter_pages_fn()):
  File "/var/task/facebook_scraper/page_iterators.py", line 30, in generic_iter_pages
    response = request_fn(next_url)
  File "/var/task/facebook_scraper/facebook_scraper.py", line 58, in get
    response.raise_for_status()
  File "/var/task/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

Ideas:

1. My first idea was that there was something unique about the pages this error was getting thrown on (private pages, pages with weird properties), but this is not the case, it throws for all pages scraped

2. My second thought was that this was a proxy issue. It is pretty common for proxies to be needed when scraping social sites. I am not currently using proxies and I am doing a lot of scraping. Perhaps I should try integrating proxies?

3. Facebook has changed their API/exposed data in some way.

**Comment by samsebree** [comment]
Just wanted to do a quick followup. Any update on this?

**Comment by kevinzg** [comment]
Have you tried from your personal computer? or from a different IP?
Can you share one of the page where it is failing? I try with some pages and didn't got that error.

**Comment by Matcap97** [comment]
Hi, I have the same problem with some pages, it can be caused by some special characters. There is any update?

**Comment by balazssandor** [comment]
Failing with HTTP 500 for page `libertatea` and not only.

**Comment by neon-ninja** [comment]
```python
print(len(list(get_posts(
    "libertatea",
    page_limit = 20,
    timeout = 60,
    cookies = "cookies.txt",
    options = {"allow_extra_requests": False}
))))
```
outputs `78`, so this seems fixed
