### ISSUE TITLE
Your request couldn't be processed

### ISSUE THREAD

**Issue by sinanajluan** [kevinzg/facebook-scraper#858]
Traceback (most recent call last):
  File "C:\Users\Lenovo T440p\PycharmProjects\facebook-scraper\ShkrimiPostimeveFacebookNeFile.py", line 14, in <module>
    for post in get_posts('topchannel/posts', pages=20):
  File "C:\Users\Lenovo T440p\PycharmProjects\facebook-scraper\facebook_scraper\facebook_scraper.py", line 1115, in _generic_get_posts
    for i, page in zip(counter, iter_pages_fn()):
  File "C:\Users\Lenovo T440p\PycharmProjects\facebook-scraper\facebook_scraper\page_iterators.py", line 87, in generic_iter_pages
    response = request_fn(next_url)
  File "C:\Users\Lenovo T440p\PycharmProjects\facebook-scraper\facebook_scraper\facebook_scraper.py", line 928, in get
    raise exceptions.UnexpectedResponse("Your request couldn't be processed")
facebook_scraper.exceptions.UnexpectedResponse: Your request couldn't be processed

**Comment by jeffsnack** [comment]
Same questions
maybe i have to change my proxy or cookies?
I try to do,but it doesn't work
anybody know how can i do?
`import requests
from http import cookiejar
import facebook_scraper as fb
file ='facebook.com_cookies.txt'
cookie = cookiejar.MozillaCookieJar()
cookie.load(file)
cookies =requests.utils.dict_from_cookiejar(cookie)
#print(cookies)
fb.set_proxy('http://133.18.173.186:8080')
fb.set_cookies(cookies)`

**Comment by Suizer** [comment]
Same problem here

**Comment by jangdmn** [comment]
Same

**Comment by kostyakoz** [comment]
Same, seems like scraper is dead :(

**Comment by nikbpetrov** [comment]
Same issue; worked fine yesterday.

**Comment by SerafinGranados** [comment]
I had the same result, so I instead changed the is_logged_in url, I set that to the main facebook (how many people hit that page), I also changed the session cookies:

```
"Accept": "*/*",
"Connection": "keep-alive",
"Accept-Encoding": "gzip,deflate",
"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8"
```
that worked for me, can someone else test the same?

**Comment by kostyakoz** [comment]
@SerafinGranados can you please describe more on what you’ve changed? Where is `is_logged_in`?

**Comment by nikbpetrov** [comment]
@SerafinGranados That worked, thanks!

Details: open the facebook_scrape.py file. Locate the is_logged_in function and change to: (just remove the `m.` in facebook URL)

```python
def is_logged_in(self) -> bool:
        try:
            self.get('https://facebook.com/settings')
            return True
        except exceptions.LoginRequired:
            return False
```

Now to change the default headers, simply go to the top where the FacebookScraper class is defined and change to:

```python
default_headers = {
        "Accept": "*/*",
        "Connection": "keep-alive",
        "Accept-Encoding": "gzip,deflate",
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8"
    }
```

**Comment by sinanajluan** [comment]
@SerafinGranados can you help us with the piece of code to change and where, please?

**Comment by SerafinGranados** [comment]
> 

try to search for the blocks of code that @nikbpetrov showed

**Comment by jeffsnack** [comment]
@nikbpetrov 

Don't change user agent?I'm a windows and chrome user,so I wonder that if work?

**Comment by jeffsnack** [comment]
@nikbpetrov 
Thanks,bro.

I can work it

**Comment by kostyakoz** [comment]
@nikbpetrov thanks, seems like it working for me 👍

**Comment by SerafinGranados** [comment]
I think we might close this issue

**Comment by mossmoss** [comment]
@SerafinGranados @nikbpetrov 

This is working for me too, at least for the moment. 

I had a comma following the ""User-Agent" value so kept it. The example doesn't show it. 

Can someone explain why this is working? It seems some headers were changed, added, removed, and a URL was changed. 

Off topic, but - does anyone know of  something that works for Instagram? Not too long ago I could see json here: https://www.instagram.com/username/?__a=1

**Comment by SerafinGranados** [comment]
Long ago in another team we created some big scrapers for other applications, we learned that great pages with great information changes his html structure with time, so they all see patterns which can help them to detect and block malicious behaviours. So that's why I decided to change some of these configurations. 

For instagram I use another repository but it is in php, I recomend to search and do the test&error, that's how I found this repo

**Comment by Ianneee** [comment]
> 

Thanks for your help.

Can i ask you wich repo are you using for instagram? Thanks

**Comment by kevalnagda** [comment]
I am still facing the same issue. Is anyone else facing it too?

**Comment by SerafinGranados** [comment]
raiym/instagram-php-scraper
hope this helps to you @Ianneee

**Comment by sinanajluan** [comment]
@SerafinGranados , @nikbpetrov thank you!
