### ISSUE TITLE
Request url callback with post_urls (get_posts)

### ISSUE THREAD

**Issue by Ianneee** [kevinzg/facebook-scraper#884]
Is it possible to use `request_url_callback` in  `get_posts` when using `post_urls=[ <post_id> ]`?
I receive this error:
```Python
TypeError: get_posts_by_url() got an unexpected keyword argument 'start_url'
```
I want to extract big quantity of comments from posts and i'm looking a way to recover my work from bans.
Here how i'm launching the scraper:

```Python
for post in facebook_scraper.get_posts(
    post_urls=[post_ids],
    cookies=cookies_file,
    start_url=start_url,
    request_url_callback=handle_pagination_url,
    options={
        "comments": True,
        "comments": "generator",
        "allow_extra_requests": True,
        "comment_reactors": True,
        "reactors": False,
        "reactions": True:
    },
):

   # Extract comments
```

**Comment by neon-ninja** [comment]
This doesn't make any sense, as the start url would just be one of the post ids in your list. You would just filter your list based on what you've already seen

**Comment by Ianneee** [comment]
Sorry but I was deleting the question because I'm looking for something related to comments and not posts... I had no expectation that you would answer me already at this time.
