### ISSUE TITLE
Scraping reactions is not working anymore. 

### ISSUE THREAD

**Issue by starspoint** [kevinzg/facebook-scraper#89]
Recently scraping reactions is not working anymore. Moreover it throws error in the code. 
Please refer the image below
![image](https://user-images.githubusercontent.com/13492875/87743994-dc5ddd80-c81c-11ea-9050-e99f3532cbf0.png)

@kevinzg  do you think should we fix, remove or suppress?

**Comment by kevinzg** [comment]
I added a warning in case the reactions weren't extracted.
We still need to figure out why they aren't being extracted.

**Comment by starspoint** [comment]
I guess the reason is the page is using graphql + ajax to make the call. It requires user login to get the details

**Comment by kevinzg** [comment]
Fixed in #90, released as version 0.2.6.
