### ISSUE TITLE
Is it possible to get a specific post  in 2 weeks ago?

### ISSUE THREAD

**Issue by kwakwakwa** [kevinzg/facebook-scraper#91]
This library is great and might I ask is it possible to get a specific post 2 weeks ago?

For example , 
Post ID: 3222682844482813
URL: https://www.facebook.com/Nintendo/posts/3222682844482813

Thank you very much.

**Comment by neon-ninja** [comment]
As of https://github.com/kevinzg/facebook-scraper/pull/184 now it is
