### ISSUE TITLE
Feature to extract post from a facebook story page rather than from account

### ISSUE THREAD

**Issue by STG284** [kevinzg/facebook-scraper#92]
For example to extract from https://m.facebook.com/story.php?story_fbid=10165158992115725&id=153080620724 this page instead of scraping from DonaldTrump/posts

**Comment by neon-ninja** [comment]
this is now possible as of https://github.com/kevinzg/facebook-scraper/pull/184

**Comment by neon-ninja** [comment]
duplicate of https://github.com/kevinzg/facebook-scraper/issues/92
