### ISSUE TITLE
"Your Account Has Been Disabled" - Temporarily Banned

### ISSUE THREAD

**Issue by GrimesSheenaLana** [kevinzg/facebook-scraper#923]
Hello guys! I really love how facebook-scraper helped people to parse data.

I am currently working on a project that needs to fetch facebook comments during the covid period (from Jan 2020 to Oct 2021). This means I need to fetch a large amount of data (~1000 posts). When I tried to increase the pages to 100 and posts per page to 30, I got the error to be "Temporarily Banned".

**May I ask**:

1. How to solve this issue and reactivate the account.
2. Is there any options to set the date range when fetching the posts? I only need posts during the covid period (from Jan 2020 to Oct 2021), but I think the default fetching always starts with the latest posts.

Thank you!

**Comment by ReemOmer** [comment]
@GrimesSheenaLana did you find any workaround to solve this issue?
