### ISSUE TITLE
Paragraph breaks are not recognised

### ISSUE THREAD

**Issue by TheMulti0** [kevinzg/facebook-scraper#94]
Hey,

I appreciate the work on this scraper, it does a terrific job, however, although it does recognise line breaks, it fails to show paragraph breaks. 

I believe this is a simple fix, instead of only appending `node.text` in `extractors.extract_text`, append `node.text + \n`.
https://github.com/kevinzg/facebook-scraper/blob/8936b378c60f06556ad0d561407909d6de6a80a2/facebook_scraper/extractors.py#L160
https://github.com/kevinzg/facebook-scraper/blob/8936b378c60f06556ad0d561407909d6de6a80a2/facebook_scraper/extractors.py#L162

Thanks!

**Comment by kevinzg** [comment]
Published fix as version 0.2.7.
