### ISSUE TITLE
Browser Login requires to change password

### ISSUE THREAD

**Issue by dungdl** [kevinzg/facebook-scraper#959]
I'm using `facebook-scraper` version `0.2.59` and providing my clone FB account's credentials to the Python app.
My problem is every time I start a new session of the app and the notification of using the Browser to log in shows up, I go to the Browser and after verifying it's me, FB requires me to change my FB password to finish the process.
Has anyone encountered this situation before? Do you know if there are any FB account settings that should be noticed?
Thank you!

**Comment by ReemOmer** [comment]
Not sure how you passed your credentials, but have you tried using the cookies options in the get_posts function? You can do that after login from your browser to Facebook, then using a cookie manager add-on to export your cookies. Later you will pass the location of the exported cookies to your function in the cookies parameter:

`
for post in get_posts(fbpage_name, cookies = cookies_file):
`

**Comment by dungdl** [comment]
Thank you
 I'll give it a shot
