### ISSUE TITLE
How to write the cookies.txt file in get_profile?

### ISSUE THREAD

**Issue by MazenTayseer** [kevinzg/facebook-scraper#967]
as mentioned, `get_profile("zuck", cookies="cookies.txt")`
how to write the cookies.txt file properly for it to work, as I want to extract gender and date of birth?

**Comment by ReemOmer** [comment]
Cookies can be downloaded directly from the browser using Cookie manager ad-on, refer to [959](https://github.com/kevinzg/facebook-scraper/issues/959).
