### ISSUE TITLE
Get_posts not getting reactions

### ISSUE THREAD

**Issue by Alanjv05** [kevinzg/facebook-scraper#968]
I've been using the scraper with no problem but today suddenly facebook logged me out and then the scraper kept getting the posts but without the reactions.

Any solution? Thank you

**Comment by ReemOmer** [comment]
In the options of the get_posts function, you should set  `"reactors": True`.

**Comment by Alanjv05** [comment]
> In the options of the get_posts function, you should set `"reactors": True`. Refer to [679](https://github.com/kevinzg/facebook-scraper/issues/679).

Thank you

**Comment by AparnaVinit** [comment]
Doesn't working
