### ISSUE TITLE
Facebook is giving a captcha 

### ISSUE THREAD

**Issue by Aarron-shaw** [kevinzg/facebook-scraper#99]
Will this resolve in time? How do I resolve this. 

I've attempted to use proxies but I can not understand how to implement them, does anyone have any examples? 

I've attempted several times but can't figure it out.

**Comment by lazanet** [comment]
I'm having same the issue. 

This breaks extracting single post, so `post_text` returns `None` (but doesn't throw an error)
https://github.com/kevinzg/facebook-scraper/blob/1bd66ac08e851a1a7364b21c6cb5bf0e6dfa8bc7/facebook_scraper/extractors.py#L141-L146

You can trigger it by rapidly reloading post page (`https://m.facebook.com/story.php?story_fbid=...`)
![captcha](https://i.imgur.com/DD4cAkk.png)

Captcha is stored as plain image which can be fetched using `#captcha img` selector. 
Result should be sent as `captcha_response` in POST request to the same page. 

Note that several CSRF tokens might be used here (in my example they are `lsd` and `jazoest` as well as `captcha_persist_data`).

Relevant HTML response can be seen [here](https://pastebin.com/8mfTGgXq).

**Comment by kevinzg** [comment]
Great report!
Any suggestion on how to handle them?

**Comment by lazanet** [comment]
My idea was that we could do something like:

```python
if "Security check" in response.html.find('title', first=True).text:
    img = fetchCaptcha(response)
    captchaFormParams = fetchCaptchaFormParams(response)
    solution = solveCaptcha(img)
    response = sendCaptcha(url, solution, formParams)
    element = response.html.find('.story_body_container', first=True)
```
on line 145. Some of [these captcha solvers](https://github.com/topics/captcha-solving?l=python) could be utilized.

**Comment by neon-ninja** [comment]
I don't think Facebook serves captchas anymore, possibly because they're too easily solved. Instead, you just get HTML that says "you’re temporarily blocked", for which the scraper should throw an exception
